### ISSUE TITLE
[addtool] xnLinkFinder

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#100]
[link]https://github.com/xnl-h4ck3r/xnLinkFinder[/link]
[short_descr] A python tool used to discover endpoints (and potential parameters) for a given target [/short_descr]
[tags]linkfinder,param_discover,param_mining[/tags]
[long_descr]his is a tool used to discover endpoints (and potential parameters) for a given target. It can find them by:

    crawling a target (pass a domain/URL)
    crawling multiple targets (pass a file of domains/URLs)
    searching files in a given directory (pass a directory name)
    get them from a Burp project (pass location of a Burp XML file)
    get them from an OWASP ZAP project (pass location of a ZAP ASCII message file)
    processing a waymore results directory (searching archived response files from waymore -mode R and also requesting URLs from waymore.txt and the original URLs from index.txt - see waymore README.md)

The python script is based on the link finding capabilities of my Burp extension GAP. As a starting point, I took the amazing tool LinkFinder by Gerben Javado, and used the Regex for finding links, but with additional improvements to find even more.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207291760-02ed3ccb-4b92-4531-92c1-4da36e476743.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/xnlinkfinder

Thank you!
