### ISSUE TITLE
[addtool] OSINTui

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#1005]
[homepage]https://github.com/wssheldon/osintui [/homepage]
[tags]lOSINT[/tags]
[short_descr]OSINT from your favorite services in a friendly terminal user interface - integrations for Virustotal, Shodan, and Censys
[/short_descr]
[image]
![image](https://user-images.githubusercontent.com/53378318/230302725-ac597f37-3774-4553-819a-e125f9570c11.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/osintui

Thank you for your contribution!
