### ISSUE TITLE
[addtool] JWT Tool

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#101]
[link]https://github.com/ticarpi/jwt_tool[/link]
[short_descr]A toolkit for testing, tweaking and cracking JSON Web Tokens [/short_descr]
[tags]jwt[/tags]
[long_descr]
jwt_tool.py is a toolkit for validating, forging, scanning and tampering JWTs (JSON Web Tokens).
This tool is written for pentesters, who need to check the strength of the tokens in use, and their susceptibility to known attacks. A range of tampering, signing and verifying options are available to help delve deeper into the potential weaknesses present in some JWT libraries[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207293496-5fd8e4f8-301d-4cd8-8de4-3ca1c8f413ea.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/jwt-tool

Thank you!
