### ISSUE TITLE
[addtool] Slurp

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#102]
[link]https://github.com/0xbharath/slurp[/link]
[short_descr] A blazing fast & feature rich Amazon S3 bucket enumerator. [/short_descr]
[tags]s3,aws[/tags]
[long_descr]Blackbox/whitebox S3 bucket enumerator.
Features

    Scan via domain(s); you can target a single domain or a list of domains
    Scan via keyword(s); you can target a single keyword or a list of keywords
    Scan via AWS credentials; you can target your own AWS account to see which buckets have been exposed
    Colorized output for visual grep
    Currently generates over 28,000 permutations per domain and keyword (thanks to @jakewarren and @random-robbie)
    Punycode support for internationalized domains
    Strong copyleft license (GPLv3)[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207294188-8ecb6d6c-561b-4246-97c0-f6fa1d58687e.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/slurp

Thank you!
