### ISSUE TITLE
[addtool] AWS Sensitive Permissions

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1020]
[homepage] https://github.com/carlospolop/aws_sensitive_permissions [/homepage]
[tags] all,aws,cloud,permissions,scanning [/tags]
[short_descr] This script enumerates the permissions of all the AWS principals of an account. [/short_descr]
[image] https://user-images.githubusercontent.com/5957301/230714986-385c86bc-2331-4651-8366-7643b20a83d4.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/aws-sensitive-permissions

Thank you for your contribution!
