### ISSUE TITLE
[addtool] InsiderPhD

### ISSUE THREAD

**Issue by naveend3v** [gwen001/offsectools_www#1021]
[homepage]https://www.youtube.com/@InsiderPhD/videos[/homepage]
[extra_link]https://insiderphd.dev/[/extra_link]
[tags]training,BugBounty,hacker,learning,recon,tools[/tags]
[short_descr]InsiderPhD YouTube channel[/short_descr]
[long_descr]One of the most famous hacker in the community, who often shares learning tips for Bug bounty, web application pen-testing, bug bounty methodologies, etc.[/long_descr]
[image]https://i.imgur.com/YCZ0jWY.png[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: short_descr, homepage, tags

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by naveend3v** [comment]
[homepage]https://www.youtube.com/@InsiderPhD/videos
[extra_link]https://insiderphd.dev/
[tags]training,bugbounty,hacker,learning,recon,tools
[short_descr]InsiderPhD YouTube channel
[long_descr]One of the most famous hacker in the community, who often shares learning tips for Bug bounty, web application pen-testing, bug bounty methodologies, etc.
[image] <img width="675" alt="InsiderPhD" src="https://user-images.githubusercontent.com/115933783/230727210-ccdd1710-692b-410f-afaf-39dd2ed72938.png">

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/insiderphd

Thank you for your contribution!
