### ISSUE TITLE
[addtool] HackerSploit

### ISSUE THREAD

**Issue by naveend3v** [gwen001/offsectools_www#1022]
[homepage]https://www.youtube.com/@HackerSploit/videos[/homepage]
[extra_link]https://hackersploit.org[/extra_link]
[tags]bugbounty,redteam,youtube,offensiveSecurity,learning,youtube[/tags]
[short_descr]HackerSploit YouTube Channel[/short_descr]
[long_descr]HackerSploit is the leading provider of free Infosec and cybersecurity training tutorials for Linux, web application pen-testing, and network pen-testing on youtube.[/long_descr]
[image]https://i.imgur.com/V7XC5Mn.png[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: short_descr, homepage, tags, picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by naveend3v** [comment]
[homepage]https://www.youtube.com/@HackerSploit/videos[/homepage]
[extra_link]https://hackersploit.org[/extra_link]
[tags]bugbounty,redteam,youtube,offensiveSecurity,learning,youtube[/tags]
[short_descr]HackerSploit YouTube Channel[/short_descr]
[long_descr]HackerSploit is the leading provider of free Infosec and cybersecurity training tutorials for Linux, web application pen-testing, and network pen-testing on youtube.[/long_descr]
[image]https://i.imgur.com/V7XC5Mn.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hackersploit

Thank you for your contribution!
