### ISSUE TITLE
[addtool] Bug Bounty Reports Explained

### ISSUE THREAD

**Issue by naveend3v** [gwen001/offsectools_www#1023]
[homepage]https://www.youtube.com/@BugBountyReportsExplained/videos[/homepage]
[extra_link]https://www.bugbountyexplained.com[/extra_link]
[tags]training,BugBounty,hacker,learning,recon,tools[/tags]
[short_descr]Bug Bounty Reports Explained YouTube Channel.[/short_descr]
[long_descr]One of the most famous hacker in the community, who explains critical bug bounty reports and vulnerabilities in a more practical way[/long_descr] 
[image]https://i.imgur.com/CEvvtxP.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/bug-bounty-reports-explained

Thank you for your contribution!
