### ISSUE TITLE
[addtool] lsassy

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1029]
[homepage] Python tool to remotely extract credentials on a set of hosts. [/homepage]
[link] https://github.com/Hackndo/lsassy [/link]
[tags] lsassy, python, credentils, extract, AD [/tags]
[short_descr] This tool uses [impacket](https://github.com/SecureAuthCorp/impacket) project to remotely read necessary bytes in lsass dump and [pypykatz](https://github.com/skelsec/pypykatz) to extract credentials. 

lsassy works with python >= 3.7 [/short_descr]

[image] 
![image](https://user-images.githubusercontent.com/98208035/230766224-b9a184db-d36e-46b6-bb31-f86f8ff624b7.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/lsassy

Thank you for your contribution!
