### ISSUE TITLE
[addtool] spaces-finder

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#103]
[link]https://github.com/appsecco/spaces-finder[/link]
[short_descr] A tool to hunt for publicly accessible DigitalOcean Spaces.[/short_descr]
[tags]digitalocean,enumeration[/tags]
[long_descr]Spaces finder is a tool to quickly enumerate DigitalOcean Spaces to look for loot. It's similar to a subdomain bruteforcer but is made specifically for DigitalOcean Spaces and also has some extra features that allow you to grep for delicious files as well as download interesting files if you're not afraid to quickly fill up your hard drive.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207294608-af2c3d98-f245-462e-a293-36e3891fc86f.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/spaces-finder

Thank you!
