### ISSUE TITLE
[addtool] wmiexec-Pro

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1030]
[homepage] New generation of wmiexec.py. [/homepage]
[tags] wmiexec, impacket, python [/tags]
[link] https://github.com/XiaoliChan/wmiexec-Pro [/link]
[short_descr]The new generation of wmiexec.py, more new features, whole the operations only work with port 135 (don't need smb connection) for AV evasion in lateral movement (Windows Defender, HuoRong, 360)[/short_descr]

[long_descr]
## Features : 
- Main feature: Only need port 135.
- New module: AMSI bypass
- New module: File transfer
- New module: Remote enable RDP via wmi class method
- New module: Windows firewall abusing
- New module: Eventlog looping cleaning
- New module: Remote enable WinRM without touching CMD
- Enhancement: Get command execution output in new way
- Enhancement: Execute vbs file    [/long_descr] 

[image] 
![image](https://user-images.githubusercontent.com/98208035/230921964-c22e410e-e3f2-4b88-98ea-9f8755bfae6e.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Please take care to follow the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) for your future submissions, or use the issue template created for that purpose to avoid any mistake.
You can also check one of the issue already closed to see how it's supposed to be.

Thank you for your understanding.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wmiexec-pro

Thank you for your contribution!
