### ISSUE TITLE
[addtool] nmapAutomater.sh

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1031]
[homepage]Now Automate You Nmap Scanning[/homepage]
[link]https://github.com/21y4d/nmapAutomator [/link]
[tags] nmap, portscanning, scanner [/tags]
[short_descr] A script you can run in the background! [/short_descr]
[long_descr]The main goal for this script is to automate the process of enumeration & recon that is run every time, and instead focus our attention on real pentesting.
This will ensure two things:

Automate nmap scans.
Always have some recon running in the background.
Once initial ports are found 'in 5-10 seconds', we can start manually looking into those ports, and let the rest run in the background with no interaction from our side whatsoever.
[/long_descr] 
[image]
![nmapAutomator](https://i.imgur.com/3cMJIPr.gif)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
