### ISSUE TITLE
[addtool] MalBuzz

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1036]
[homepage]  A handy tool to help you analyze malware. [/homepage]

[link]  https://github.com/NomanProdhan/malbuzz  [/link]

[tags] malware, malbuzz [/tags]

[short_descr] It's a handy tool to help you analyze malware. You can use this tool to query your malware samples using different hashes or find all other samples using YARA rules, CalmAV signatures, etc. This tool is based on MalwareBazaar.

#### Requirements : 
- curl (available in most Linux distros)
- jq
- sha256sum (available in most Linux distros)
 [/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/231107019-00362298-be10-49f1-83f6-f666bf2f1ae2.png)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/malbuzz

Thank you for your contribution!
