### ISSUE TITLE
[addtool] WebScrape

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1037]
[homepage] A web scraper which scrapes mail ID's and phone numbers from the websites. [/homepage]
[link] https://github.com/3xploitGuy/webscrape [/link]

[tags] website, enumeration, email, numbers, scraper [/tags]

[short_descr] 
It is a web scraper written in bash with all possible error handling which scrapes mail ID's and phone numbers from the websites.

#### What is Web Scraping ?
Web Scraping also termed Web Data Extraction or Web Harvesting it is a technique employed to extract large amounts of data from websites whereby the data is extracted and saved to a local file in your computer for many uses.

[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/231113596-1d7091fc-a577-4560-8656-cacebc2eba61.png)

[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/webscrape

Thank you for your contribution!

**Comment by gwen001** [comment]
Please take care to follow the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) for your future submissions, or use the issue template created for that purpose to avoid any mistake.
You can also check one of the issue already closed to see how it's supposed to be.

Thank you for your understanding.
