### ISSUE TITLE
[addtool] QuadraInspect

### ISSUE THREAD

**Issue by morpheuslord** [gwen001/offsectools_www#1040]
[homepage]QuadraInspect[/homepage]
[extra_link] https://github.com/morpheuslord/QuadraInspect [/extra_link]
[tags] apk, android, code-analysis, reverse-engineering[/tags]
[short_descr]QuadraInspect provides a comprehensive approach to the vulnerability analysis of Android applications.[/short_descr]
[long_descr]QuadraInspect is an Android framework that integrates AndroPass, APKUtil, RMS, and MobFS, providing a powerful tool for analyzing the security of Android applications. AndroPass is a tool that focuses on analyzing the security of Android applications' authentication and authorization mechanisms, while APKUtil is a tool that extracts valuable information from an APK file. Lastly, MobFS and RMS facilitate the analysis of an application's filesystem by mounting its storage in a virtual environment.[/long_descr] 
[image] 
![Screenshot 2023-04-02 134324](https://user-images.githubusercontent.com/70637311/231222945-cdcc39e3-d902-4358-b575-230164b4dad5.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Please take care to follow the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) for your future submissions, or use the issue template created for that purpose to avoid any mistake.
You can also check one of the issue already closed to see how it's supposed to be.

Thank you for your understanding.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/quadrainspect

Thank you for your contribution!
