### ISSUE TITLE
[addtool] GodPotato

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1042]
[homepage] If you have "**ImpersonatePrivilege**" permission, then you are "**NT AUTHORITY\SYSTEM**" [/homepage]
[link] https://github.com/BeichenDream/GodPotato [/link]

[tags] potato, godpotato, windows, privesc [/tags]

[short_descr]

Based on the history of Potato privilege escalation for 6 years, from the beginning of RottenPotato to the end of JuicyPotatoNG, I discovered a new technology by researching DCOM, which enables privilege escalation in Windows 2012 - Windows 2022, now as long as you have "ImpersonatePrivilege" permission. Then you are "NT AUTHORITY\SYSTEM", usually WEB services and database services have "ImpersonatePrivilege" permissions.

Potato privilege escalation is usually used when we obtain WEB/database privileges. We can elevate a service user with low privileges to "NT AUTHORITY\SYSTEM" privileges. However, the historical Potato has no way to run on the latest Windows system. When I was researching DCOM, I found a new method that can perform privilege escalation. There are some defects in rpcss when dealing with oxid, and rpcss is a service that must be opened by the system. , so it can run on almost any Windows OS, I named it GodPotato

[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/231499351-dccb46a0-6257-4cb2-8526-abacc9347559.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Like all your contributions you don't respect the expected format of the issue as explained in the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

The `homepage` tag is for a link to the tool not a description.
The `short_descr` tag if for a short description of the tool (100 chars max.) not a long text.
The `long_descr` tag if for a long description of the tool.
The `link` tag is not considered at all.

Please use the issue template created for that purpose to avoid any mistake.
You can also check one of the past issue already closed to see how it's supposed to be.

For now I'll put your contributions in stand by mode until you fix them. It's too much work for me to manually edit all of them.

Thank you for your understanding.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
