### ISSUE TITLE
[addtool] EndExt

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1043]
[homepage] Tool for extracting all the possible endpoints from the JS files [/homepage]

[link]  https://github.com/SirBugs/endext  [/link]

[tags]  [/tags]

[short_descr]
EndExt is a .go tool for extracting all the possible endpoints from the JS files

When you crawll all the JS files from waybackruls for example, or even collecting the JS files urls from your target website's home source page .. If the website was using API system and you wanna look for all the endpoints in the JS files, cuz u may find something hidden here or there .. That's why i made this tool .. I give it the JS files urls .. It graps all the possible endpoints or urls or paths in the submitted JS files for me ..

[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/231503563-4d8e3b9a-db7b-40cc-8dd6-2f1a39585fbc.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Like all your contributions you don't respect the expected format of the issue as explained in the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

The `homepage` tag is for a link to the tool not a description.
The `short_descr` tag if for a short description of the tool (100 chars max.) not a long text.
The `long_descr` tag if for a long description of the tool.
The `link` tag is not considered at all.

Please use the issue template created for that purpose to avoid any mistake.
You can also check one of the past issue already closed to see how it's supposed to be.

For now I'll put your contributions in stand by mode until you fix them. It's too much work for me to manually edit all of them.

Thank you for your understanding.
