### ISSUE TITLE
[addtool] Nmap-API

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1044]
[homepage] https://github.com/morpheuslord/Nmap-API [/homepage]
[tags] all,nmap,API,scan [/tags]
[short_descr] Uses Python 3.10, Debian, python-Nmap, and Flask framework to create a Nmap API that can do scans. [/short_descr]
[image] 
![image](https://user-images.githubusercontent.com/5957301/231926376-9d8ee729-df25-4013-a92c-65f66e51a336.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/nmap-api

Thank you for your contribution!
