### ISSUE TITLE
[addtool] Comperio

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1047]
[homepage] https://github.com/felipecaon/comperio [/homepage]
[tags] all,osint,usernames,social [/tags]
[short_descr] OSINT tool to find usernames across 80+ social media and social networking sites. [/short_descr]
[image] 
![image](https://user-images.githubusercontent.com/5957301/232262856-527d04cf-3ca4-4b37-a715-215f3a45f51e.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/comperio

Thank you for your contribution!
