### ISSUE TITLE
[addtool] autowpscan

### ISSUE THREAD

**Issue by password123456** [gwen001/offsectools_www#1048]
[homepage]https://github.com/password123456/autowpscan[/homepage]
[tags]wordpress,wpscan,automation wpscan[/tags]
[short_descr]An automated tool that automatically scanning a list of multiple websites with wordpress at once[/short_descr]
[long_descr]This tool takes a list of multiple websites created with wordpress, lists them according to a predefined format, and uses wpscan to perform the scanning.

Nothing special, Just simple a list of multiple websites scanner with wpscan. If you're good with code, I'm sure you can implement more sophisticated automation (e.g. Telegram bots, automatic checks on deployment via the Asset Information Report API, etc), or if you're thinking about your own DAST, this can help you with the initial development design.

If you want to extend it further, you could create an administrative web UI and create self-service checks on the web UI, so that you can perform checks on demand.[/long_descr] 
[image]https://github.com/password123456/autowpscan/blob/main/autowpscan.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/autowpscan

Thank you for your contribution!
