### ISSUE TITLE
[addtool] LinkedInDumper

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1053]
[homepage] Python 3 script to dump company employees from #LinkedIn API.  [/homepage]
[tags] LinkedIn, username, enumeration, passiv  [/tags]
[link] https://github.com/l4rm4nd/LinkedInDumper [/link]

[short_descr] 

LinkedInDumper is a Python 3 script that dumps employee data from the LinkedIn social networking platform.

The results contain firstname, lastname, position (title), location and a user's profile link. Only 2 API calls are required to retrieve all employees if the company does not have more than 10 employees. Otherwise, we have to paginate through the API results. With the --email-format CLI flag one can define a Python string format to auto generate email addresses based on the retrieved first and last name.

[/short_descr] 

[image] 
![image](https://user-images.githubusercontent.com/98208035/233422385-a005734f-dd07-4121-bc23-5ec1d95f53c1.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/linkedindumper

Thank you for your contribution!
