### ISSUE TITLE
[addtool] LDAPNomNom

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1054]
[homepage] https://github.com/lkarlslund/ldapnomnom [/homepage]

[tags] ldap, Activedirectory, username, bruteforcing [/tags]

[short_descr]  Anonymously bruteforce Active Directory usernames from Domain Controllers by abusing LDAP Ping requests (cLDAP)

Looks for enabled normal user accounts. No Windows audit logs generated. High speed ~ up to 10K/sec - go beyond 25K/sec with multiple servers! [/short_descr]

[long_descr]

- Tries to autodetect DC from environment variables on domain joined machines or falls back to machine hostname FQDN DNS suffix
- Reads usernames to test from stdin (default) or file
- Outputs to stdout (default) or file
- Parallelized, multiple connections to multiple servers (defaults to 8 servers, 8 connections per server)
- Shows progressbar if you're using both input and output files
- Evasive maneuvers: Use --throttle 20 for a 20ms delay between each request (slows everything down to a crawl)
- Evasive maneuvers: Use --maxrequests 1000 to close connection and reconnect after 1000 requests in each connection (try to avoid detection based on traffic volume)

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/233543102-5531488e-d718-4784-86c9-59538244223a.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ldapnomnom

Thank you for your contribution!
