### ISSUE TITLE
[addtool] xsshunter

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1056]
[homepage]
https://github.com/rs-loves-bugs/xsshunter
[/homepage]

[tags]
 xss
[/tags]

[short_descr]
The fastest way to set up XSS Hunter to test and find blind cross-site scripting vulnerabilities.
[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/233545353-2b71621b-8f60-4337-b529-e077465cbb8f.png)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: homepage

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/xsshunter

Thank you for your contribution!
