### ISSUE TITLE
[addtool] xsshunter

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1057]
[homepage]

 Newly Modified version : https://github.com/rs-loves-bugs/xsshunter 

[/homepage] 

[extra_link]

Older but the Original version : https://github.com/trufflesecurity/xsshunter

[/extra_link]

[tags] xss, xsshunter [/tags]

[short_descr]

The fastest way to set up XSS Hunter to test and find blind cross-site scripting vulnerabilities.

[/short_descr]

[long_descr]

### Requirements
docker and docker-compose installed
Host with at least 2 GB of RAM
A hostname (e.g. host.example.com) which you can map to your server's IP (have DNS control for)
[For Email Notifications] To receive email notifications of XSS payload fires you'll need an email account with valid SMTP credentials. You can use many regular email accounts like Gmail for this purpose. This is not required if you don't want email notifications.

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/233545353-2b71621b-8f60-4337-b529-e077465cbb8f.png)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: homepage

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Problem occured with the following fields:
- homepage should be a link

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Problem occured with the following fields:
- homepage should be a link

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Problem occured with the following fields:
- homepage should be a link

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose).

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `homepage` should be a link

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
