### ISSUE TITLE
[addtool] gotator

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#106]
[link]https://github.com/Josue87/gotator[/link]
[short_descr] Gotator is a tool to generate DNS wordlists through permutations. [/short_descr]
[tags]dns,subdomain,recon[/tags]
[long_descr] Gotator is a tool to generate DNS wordlists through permutations. [/long_descr]

![image](https://user-images.githubusercontent.com/32585833/207296349-1473c309-3e68-4a4f-81de-44382e654d8d.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/gotator

Thank you!
