### ISSUE TITLE
[addtool] Brute-Hacking-Framework

### ISSUE THREAD

**Issue by morpheuslord** [gwen001/offsectools_www#1060]
[homepage] https://github.com/morpheuslord/Brute-Hacking-Framework-SourceCode [/homepage]
[extra_link] https://www.youtube.com/watch?v=5tC7vXub2Us [/extra_link]
[extra_link] https://www.youtube.com/watch?v=FTGpkr8pN6Q [/extra_link]
[extra_link] https://www.youtube.com/watch?v=FTGpkr8pN6Q [/extra_link]
[tags] all, offensive, framework, scanner [/tags]
[short_descr] A framework including all the tools that work on Windows. [/short_descr]
[long_descr] The Brute Hacking framework is my version of PentestBox with updated tools and services but also with a few more updates of tools and an updated interface. [/long_descr]
[image] 
![Screenshot 2023-04-22 203615](https://user-images.githubusercontent.com/70637311/233792401-11bb562a-3f28-4e80-b6ec-2a9e541d1047.png)
 [/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `homepage` should be a link

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Problem with the bot, sorry it's fixed now.
