### ISSUE TITLE
[addtool] IAMagic

### ISSUE THREAD

**Issue by Pyr0sec** [gwen001/offsectools_www#1070]
[homepage]https://github.com/Pyr0sec/IAMagic[/homepage]
[tags]aws,iam,scanner,cloud,accesskeys[/tags]
[short_descr]Advanced AWS Access Credentials Scanner[/short_descr]
[long_descr]IAMagic scans and enumerates AWS access credentials and displays information like all the permissions policies attached to the account, buckets, running instances etc.[/long_descr] 
![IAMagic](https://user-images.githubusercontent.com/74669749/234543018-551adce9-af93-4cf1-9f48-82d4d2adec57.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/iamagic

Thank you for your contribution!

**Comment by Pyr0sec** [comment]
Thanks for accepting 💯
