### ISSUE TITLE
[addtool] GhostTrack

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1073]
[homepage]  https://github.com/HunxByts/GhostTrack  [/homepage]

[tags] osint, informationgathering, location, mobilenumber [/tags]

[short_descr] Useful tool to track location or mobile number, so this tool can be called osint or also information gathering [/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/235144621-0b00eb2e-bfaf-4b42-8f1e-9cae8ff89c82.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ghosttrack

Thank you for your contribution!
