### ISSUE TITLE
[addtool] Spoofy

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1074]
[homepage] https://github.com/MattKeeley/Spoofy [/homepage]

[tags] python, spoofy, domains [/tags]

[short_descr] 
A program that checks if a list of domains can be spoofed based on SPF and DMARC records.
 [/short_descr]

[image] 
![image](https://user-images.githubusercontent.com/98208035/235145614-52654c32-6649-4e2c-a5c3-58925cd25ec7.png)
![image](https://user-images.githubusercontent.com/98208035/235145635-c71f5edd-f27c-44a8-b09b-86d84be6f00f.png)

[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/493
