### ISSUE TITLE
[addtool] wildcrawl

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1075]
[homepage]  https://github.com/NeverWonderLand/wildcrawl  [/homepage]

[tags]  
bash, 
crawler
[/tags]

[short_descr]
Bash script that crawls a target URL and everything around it to get a better image of what is tied to a website.
[/short_descr]

[long_descr]
- - -
![image](https://user-images.githubusercontent.com/98208035/235146897-f0fbca32-e54a-4ea9-bc54-7617ff902454.png)

#### Here's a summary of what the script does:

- Crawls the target URL using Hakrawler .
- Removes duplicate links.
- Extracts all files of certain types (e.g., PDF, DOC, ZIP, JPG) and saves them to a separate file.
- Extracts each domain from the link crawled and removes duplicates.
- Filters out certain domains (e.g., Facebook, Twitter, LinkedIn).
- Extract records (AAAA, CNAME, NS, etc)
- Extract DNS by fetching the certificate.
- Crawl again but this time using Lynx on the domain tied to the main one.
- Gets main IPs of all domains.
- Extracts the title of each domain and IP.
- Filters out any results that have a title starting with "404".
- Search emails from each domain.
- Retrieves server banner.

At the end, the tool gives you 3 options;
- Injection
- HTTP-ENUM
- Port Scan

<hr><br>

**At the end you will have these files saved in /scan_1, /scan_2, etc.**

- crawl.txt  
- domains.txt  
- files.txt  
- final_result.txt  
- injection_point.txt  
- ips.txt  
- unique_urls.txt
- sqlmap.txt - If you run sqlmap
- nmap.txt - If you run Nmap

![image](https://user-images.githubusercontent.com/98208035/235146778-97eb2cb4-d69b-414b-945a-769f061f928b.png)

[/long_descr] 

[image]

![image](https://user-images.githubusercontent.com/98208035/235147031-e9f64cca-3ce5-4f24-ae62-a9747f44f5bc.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wildcrawl

Thank you for your contribution!
