### ISSUE TITLE
[addtool] ReverseKit

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1078]
[homepage]
https://github.com/zer0condition/ReverseKit
[/homepage]

[tags]
reverseengineering, RE, ReverseKit
[/tags]

[short_descr]
A Dynamic Reverse Engineering Toolkit
[/short_descr]

[long_descr]
<p>ReverseKit is a comprehensive toolkit designed to aid reverse engineers in the process of dynamic RE. With a wide range of features and functionalities, it provides an easy-to-use interface and helps you intercept, analyze, and manipulate code and data during runtime.</p>

<h2>Features</h2>
<ul>
  <li>Imports information - along with DLL name, function name, and address.</li>
  <li>Intercept all system calls via an instrumentation callback.</li>
  <li>Intercept all commands executed - system(), ShellExecuteEx(), etc.</li>
  <li>Intercept all thread creations - APIs like std::thread, CreateThread(), etc.</li>
  <li>Intercept URLs - APIs like UrlDownloadToFileA and InternetOpenUrlA, etc.</li>
  <li>Threads - lists thread ids along with cpu usage, allows you to suspend them with a button.</li>
  <li>Bypass common debugger checks - CheckRemoteDebugger() and IsDebuggerPresent().</li>
  <li>Anti-BSOD for common usermode BSOD methods which abuse RtlAdjustPrivilege.</li>
  <li>Easy-to-use interface powered by ImGui.</li>
  <li>Hook library with a normal JMP hook and trampoline hook.</li>
</ul>
<h2>Getting Started</h2>
<p>To get started with ReverseKit, you can clone this repository and build the project. Once the build is complete, you can inject the tool using ReverseKit Loader, or any prefered injector and start using it to analyze binaries.</p>
<h2>Usage</h2>
<p>ReverseKit provides a user-friendly interface that enables you to easily intercept, analyze, and manipulate code and data during runtime. With the wide range of features and functionalities, you can:</p>
<ul>
  <li>Monitor and intercept system calls and API functions</li>
  <li>Monitor CPU usage by active threads and option to suspend</li>
  <li>Analyze network traffic and intercept URLs</li>
  <li>Analyze and manipulate thread creations</li>
  <li>Hook into binary code and redirect execution flow</li>
  <li>Bypass common debugger checks</li>
</ul>
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235294903-f7a8eb34-6833-42f6-bcd5-574c53e45a75.png)

![image](https://user-images.githubusercontent.com/98208035/235294884-c422ffde-a6de-4e43-ae0d-0455c093524a.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/reversekit

Thank you for your contribution!
