### ISSUE TITLE
[addtool] github-subdomains

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#108]
[link]https://github.com/gwen001/github-subdomains[/link]
[short_descr] Find subdomains on GitHub. [/short_descr]
[tags]github,subdomain,recon[/tags]
[long_descr] Find subdomains on GitHub. [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207299246-2e5514f5-5735-4b78-b893-7722ca464994.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/github-subdomains

Thank you!
