### ISSUE TITLE
[addtool] Pymeta

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1080]
[homepage]
https://github.com/m8sec/pymeta
[/homepage]

[tags]
python, metadate, enumeration, 
[/tags]

[short_descr]
Pymeta will search the web for files on a domain to download and extract metadata. This technique can be used to identify: domains, usernames, software/version numbers and naming conventions.
[/short_descr]

[long_descr]
# PyMeta

PyMeta is a Python3 rewrite of the tool [PowerMeta](https://github.com/dafthack/PowerMeta), created by [dafthack](https://twitter.com/dafthack) in PowerShell. It uses specially crafted search queries to identify and download the following file types (**pdf, xls, xlsx, csv, doc, docx, ppt, pptx**) from a given domain using Google and Bing scraping.

Once downloaded, metadata is extracted from these files using Phil Harvey's [exiftool](https://sno.phy.queensu.ca/~phil/exiftool/) and added to a ```.csv``` report.  Alternatively, Pymeta can be pointed at a directory to extract metadata from files manually downloaded using the ```-dir``` command line argument. See the [Usage](#Usage), or [All Options](#All-Options) section for more information.

#### Why?
Metadata is a common place for penetration testers and red teamers to find: domains, user accounts, naming conventions, software/version numbers, and more!

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235295410-1db382c1-504f-4f5a-ab89-a6fec7cb7bc0.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pymeta

Thank you for your contribution!
