### ISSUE TITLE
[addtool] PyShell

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1083]
[homepage]
https://github.com/JoelGMSec/PyShell
[/homepage]

[tags]
python, webshell, multiplatform
[/tags]

[short_descr]
PyShell is Multiplatform #Python #WebShell. This tool helps you to obtain a shell-like interface on a web server to be remotely accessed. 
[/short_descr]

[long_descr]
<p align="center"><img width=450 alt="PyShell" src="https://github.com/JoelGMSec/PyShell/blob/main/PyShell.png"></p>

# PyShell
**PyShell** is Multiplatform Python WebShell. This tool helps you to obtain a shell-like interface on a web server to be remotely accessed. Unlike other webshells, the main goal of the tool is to use as little code as possible on the server side, regardless of the language used or the operating system of the server.

Thanks to this, you can use different types of shells (aspx, php, jsp, sh, py...) both in Windows and Linux, with command history, upload and download files and even, moving through directories as if it were a standard shell.

# Requirements
- Python 3
- Install requirements.txt

# Download
It is recommended to clone the complete repository or download the zip file.
You can do this by running the following command:
```
git clone https://github.com/JoelGMSec/PyShell
```

# Usage
```
./PyShell.py -h


  ██████ ▓██   ░██  ██████  ██░ ██ ▓█████  ██▓     ██▓
 ▓██░  ██▒██░   ██▒██    ▒ ▓██  ██▒▓██    ▓██▒    ▓██▒
 ▓██░  ██▒ ██  ██░░ ▓███   ▒██████░▒████  ▒██░    ▒██░
 ▒██████ ▒ ░████▓░  ▒   ██▒░██ ░██ ▒██    ▒██░    ▒██░
 ▒██▒ ░  ░ ░ ██▒▓░▒██████▒▒░██▒░██▓░█████▒░██████▒░██████▒
 ▒██░ ░  ░  ██▒▒▒ ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒░░ ▒░ ░░ ▒░▓  ░░ ▒░▓  ░
 ░▒ ░     ▓██ ░▒░ ░ ░▒    ░ ▒ ░ ░ ░ ░ ░  ░░ ░ ▒  ░░ ░ ▒  ░
 ░░   ░   ▒ ▒ ░░  ░  ░  ░   ░  ░░ ░         ░ ░     ░ ░
 ░        ░             ░      ░      ░       ░          ░

  -------------- by @JoelGMSec & @3v4Si0N ---------------

usage: pyshell.py [-h] [-a AUTH] [-c COOKIES] [-p PARAM] [-pi] [-ifs] [-su] [-ps] url method

positional arguments:
  url                   Webshell URL
  method                HTTP Method to execute command (GET or POST)

optional arguments:
  -h, --help            show this help message and exit
  -a AUTH, --auth AUTH  Authorization header to use on each request
  -c COOKIES, --cookies COOKIES
                        Cookie header to use on each request
  -p PARAM, --param PARAM
                        Parameter to use with custom WebShell
  -pi, --pipe           Pipe all commands after parameter
  -ifs, --ifs           Replace all white spaces with Internal Field Separator
  -su, --sudo           Sudo command execution (Only on Linux hosts)
  -ps, --PowerShell     PowerShell command execution (Only on Windows hosts)
```

### The detailed guide of use can be found at the following link:

https://darkbyte.net/pyshell-multiplatform-python-webshell

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235295976-137f835b-d56a-49a2-874d-e6cba905d064.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pyshell

Thank you for your contribution!
