### ISSUE TITLE
[addtool] hfuzz

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1084]
[homepage]
https://github.com/thehlopster/hfuzz
[/homepage]

[tags]
ffuf, hfuzz, fuzzing, wordlist
[/tags]

[short_descr]
Wordlist for web fuzzing, made from a variety of reliable sources including: result from my pentests, git.rip, ChatGPT, Lex, nuclei templates, web-scanners, seclist, bo0m, and more.
[/short_descr]

[long_descr]
# hfuzz
![image](https://user-images.githubusercontent.com/98208035/235296154-74e215f8-5016-4bc8-8ea9-5dd07fd81bf3.png)

## Wordlist for web fuzzing, made from a variety of reliable sources including: 
 - result from my pentests
 - git.rip
 - ChatGPT
 - Lex
 - nuclei templates
 - web-scanners
 - seclist
 - bo0om
 
 Todo:
 - h1 reports
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235296202-a5e4d069-fc91-4ea6-8a19-483efad7fba4.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
