### ISSUE TITLE
[addtool] CeWLeR

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1090]
[homepage]
https://github.com/roys/cewler
[/homepage]

[tags]
cewl, cewler, wordlist, generator
[/tags]

[short_descr]
Custom Word List generator Redefined. CeWL alternative in Python, (https://t.me/hackgit) based on the Scrapy framework.
[/short_descr]

[long_descr]
- - -
# CeWLeR - Custom Word List generator Redefined
_CeWLeR_ crawls from a specified URL and collects words to create a custom wordlist.

It's a great tool for security testers and bug bounty hunters. The lists can be used for password cracking, subdomain enumeration, directory and file brute forcing, API endpoint discovery, etc. It's good to have an additional target specific wordlist that is different than what everybody else use.

_CeWLeR_ was sort of originally inspired by the really nice tool [CeWL](https://github.com/digininja/CeWL). I had some challenges with _CeWL_ on a site I wanted a wordlist from, but without any Ruby experience I didn't know how to contribute or work around it. So instead I created a custom wordlist generator in Python to get the job done.

## Features
- Generates custom wordlists by scraping words from web sites
- A lot of options:
  - Output to screen or file
  - Can stay within subdomain, or visit sibling and child subdomains, or visit anything within the same top domain
  - Can stay within a certain depth of a website
  - Speed can be controlled
  - Word length and casing can be configured
  - JavaScript and CSS can be included
  - Crawled URLs can be output to separate file
  - Scraped e-mail addresses can also be output to separate file
  - ++
- Using the excellent [Scrapy](https://scrapy.org) framework for scraping and using the beautiful [rich](https://github.com/Textualize/rich) library for terminal output

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235306891-e7517b5e-a946-4ebf-bb65-a54755237cba.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cewler

Thank you for your contribution!
