### ISSUE TITLE
[addtool] PowerMayhem

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1094]
[homepage]
https://github.com/jungawagat/powermayhem
[/homepage]

[tags]
bash, powershell
[/tags]

[short_descr]
Something more powerful...It's Black-Magic!!
[/short_descr]

[long_descr]
[![forthebadge](https://forthebadge.com/images/badges/powered-by-black-magic.svg)](https://forthebadge.com)

# PowerMayhem
![image](https://user-images.githubusercontent.com/98208035/235307973-38f583d1-0511-4545-b9fd-f08d7b91216e.png)

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235307970-71517c5a-7feb-4e32-b26d-6a6a82d4aa6d.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/powermayhem

Thank you for your contribution!
