### ISSUE TITLE
[addtool]  Crlfi

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1097]
[homepage]
https://github.com/karthi-the-hacker/crlfi
[/homepage]

[tags]
crlf, crlfi
[/tags]

[short_descr]
CRLF Bug scanner for WebPentesters and Bugbounty Hunters.
[/short_descr]

[long_descr]

<p align="center">
<img src="https://github.com/karthi-the-hacker/crlfi/raw/main/images/logo.gif" ><br>

</p>

> CRLF Bug scanner for WebPentesters and Bugbounty Hunters

## Prerequisites 
 
 - NodeJs 

## Installation and Example
1. Install NodeJS [Instructions Here](https://nodejs.org/en/download/package-manager/) (If you can't figure this out, you shouldn't really be using this)
    - Linux, Mac, Windows
        - `npm install crlfi -g`
    - Github
        - click [HERE](https://github.com/karthi-the-hacker/athenaa.git) for downloads

2. Open terminal now type  `crlfi`

3. Example
    - input
        - `crlfi -i urls.txt`
    - output
        - `crlfi -i urls.txt -o out.txt`

#### Usages 📚 :
```sh
    $ crlfi [option]

      Usage: crlfi [options]

      Options:
        -h, --help     Show help                           
        -V, --version  Show version number                    
        -i, --input    <filename> Input file name  
        -o, --output   <filename> output file name  
```
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235338478-4efe5921-3d1f-420e-936c-f73fa6a0821b.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/crlfi

Thank you for your contribution!
