### ISSUE TITLE
[addtool] Hashcat

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#110]
[link]https://github.com/hashcat/hashcat[/link]
[short_descr] World's fastest and most advanced password recovery utility [/short_descr]
[tags]password,crack,hashcat,bruteforce[/tags]
[long_descr]hashcat is the world's fastest and most advanced password recovery utility, supporting five unique modes of attack for over 300 highly-optimized hashing algorithms. hashcat currently supports CPUs, GPUs, and other hardware accelerators on Linux, Windows, and macOS, and has facilities to help enable distributed password cracking.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207300513-4d37e0d5-d3f8-4593-81f1-02c72dc5590b.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/hashcat

Thank you!
