### ISSUE TITLE
[addtool] hrekt

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1104]
[homepage]
https://github.com/ethicalhackingplayground/hrekt
[/homepage]

[tags]
prober, rust, bugbounty
[/tags]

[short_descr]
A really fast http prober.
[/short_descr]

[long_descr]
---

<p align="center">
  <a href="#installation">Install</a> •
  <a href="#usage">Usage</a> •
  <a href="#examples">Examples</a> •
  <a href="#fyi">FYI</a> •
  <a href="#contributing">Contributing</a> •
  <a href="#license">License</a> •
  <a href="https://discord.gg/MQWCem5b">Join Discord</a> 
</p>

---

#### Fresh Installs
```bash
$ cargo build -r
$ mv target/release/hrekt /bin/hrekt
```

#### Already been installed
```bash
$ cargo build -r
$ mv target/release/hrekt /<user>/.cargo/bin/
```

Make sure to replace `<user>` with your username.

Can only be compiled locally right now.

## Usage

```bash
USAGE:
    hrekt [OPTIONS]

OPTIONS:
    -r, --rate <rate>
            Maximum in-flight requests per second [default: 1000]

    -c, --concurrency <concurrency>
            The amount of concurrent requests [default: 100]

    -t, --timeout <timeout>
            The delay between each request [default: 3]

    -w, --workers <workers>
            The amount of workers [default: 1]

    -p, --ports <ports>
            the ports to probe default is (80,443) [default: 80,443]

    -b, --body-regex <body-regex>
            regex to be used to match a specific pattern in the response [default: ]

    -h, --header-regex <header-regex>
            regex to be used to match a specific pattern in the header [default: ]

    -i, --title
            display the page titles

    -d, --tech-detect
            display the technology used

    -q, --silent
            suppress output

    -l, --follow-redirects
            follow http redirects

        --help
            Print help information

    -V, --version
            Print version information
```

---

#### Display titles

```bash
cat subs.txt | hrekt --title
```

#### Probe ports

```bash
cat subs.txt | hrekt --ports 443,80,9200 
```

#### Display technologies

```bash
cat subs.txt | hrekt --tech-detect
```

#### Probe the response body

```bash
cat subs.txt | hrekt --body-regex 'href="\/content\/dam.*'
```

#### Probe the headers

```bash
cat subs.txt | hrekt --header-regex 'Server:.*'
```

## FYI
It's advisable to only use tech detection when needed, as it tends to result in slow discoveries because we use chromium based detection.

---

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235602239-c52fa3fc-0ba6-47b0-92d0-d88b393ee057.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
