### ISSUE TITLE
[addtool] Moriarty Project

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1106]
[homepage]
https://github.com/AzizKpln/Moriarty-Project
[/homepage]

[tags]
osint, recon, number, phonenumber
[/tags]

[short_descr]
A powerful web based phone number investigation tool. It has 6 features and it allows you to choose either all features, or the features you like. You can visit documentation page to learn more about features.
[/short_descr]

[long_descr]
![image](https://user-images.githubusercontent.com/98208035/235604575-d6c28a7e-3b73-432b-9f19-f3c1c9242362.png)

### About
Moriarty Project is a powerful web based phone number investigation tool. It has 6 features and it allows you to choose either all features, or the features you like. You can visit documentation page to learn more about features.

### Situation
Social Media Stuck Issue Fixed.

### Current Features
- Tries To Find The Owner Of The Given Phone Number.
- Tries To Find The Spam Risk Situation Of The Given Phone Number.
- Tries To Get Links Related With The Given Number.
- Tries To Find Comments That's Been Made For The Given Number.
- Tries To Find Social Media Platforms Connected With The Phone Number.

### Anti Features & Future Developments
- This tool doesn't support mobile based usage*(termux,kali nethunter etc.)*
- I might make another tool for mobile OS based usage. But currently it's not supported.
- SocialMedia feature doesn't provide the accounts that's belong to the phone number owner.
- This tool doesn't provide tracking/hacking or anything that could harm/endanger the owner. It's just an investigation tool.

### Installation
````sh

sudo apt install git -y
git clone https://github.com/AzizKpln/Moriarty-Project
cd Moriarty-Project/ && bash install.sh
bash run.sh

````

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235604523-a59f2ace-3137-4798-8064-68aaf24f1d2b.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
