### ISSUE TITLE
[addtool] WebSieve

### ISSUE THREAD

**Issue by secnextechnologies** [gwen001/offsectools_www#1107]
[homepage]
https://github.com/secnextechnologies/WebSieve
[/homepage]
[tags]
url extract, url extractor, websieve, website scanner, website crawler
[/tags]
[short_descr]
Extract Unique URLs from a Webpage
[/short_descr]
[long_descr]
"Websieve" is the name of the Python script that extracts unique URLs from a given webpage. It is a combination of the words "web" (referring to the internet) and "sieve" (a tool used to filter out unwanted particles from a mixture). The name suggests that the script is used to filter out All URLs from a webpage and extract only the ones that are unique and relevant. This Python script extracts all unique URLs from a given webpage and outputs them to the console or to a file. It uses the requests module to send a GET request to the specified URL and the BeautifulSoup module to parse the HTML content of the response.
[/long_descr] 
[image]
![image](https://user-images.githubusercontent.com/102068563/235606015-7a2c8a93-c4bd-41b9-bca0-5f7253cd74e8.png)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `picture` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by secnextechnologies** [comment]
check now

**Comment by secnextechnologies** [comment]
check now
