### ISSUE TITLE
[addtool] subnerium

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1109]
[homepage]
https://github.com/d3f1ne/subnerium
[/homepage]

[tags]
subnerium, subdomain, enumeration, recon
[/tags]

[short_descr]
A fast passive subdomain enumeration tool that uses various sources to gather data.
[/short_descr]

[long_descr]
![python](http://forthebadge.com/images/badges/made-with-python.svg)
![love](http://forthebadge.com/images/badges/built-with-love.svg)

![image](https://user-images.githubusercontent.com/98208035/235606346-4b79be9e-68d9-482f-9ca3-d68a3fdef1fb.png)

subnerium is a fast passive subdomain enumeration tool that uses various sources to gather data.<br>
All requests are made through yaml templates, to see more see the documentation:

## Download

```
git clone https://github.com/d3f1ne/subnerium
```

## Install

You can install it by typing:

```
pip3 install -r requirements.txt
chmod +x install.sh
sudo ./install.sh
```

## Run

```
Note: Use API keys to get great results.
subnerium -h
```

## APIs Used

- [alienvault](https://github.com/d3f1ne/subnerium)
- [anubis](https://github.com/d3f1ne/subnerium)
- [binaryedge](https://github.com/d3f1ne/subnerium)
- [cerspotter](https://github.com/d3f1ne/subnerium)
- [crtsh](https://github.com/d3f1ne/subnerium)
- [hackertarget](https://github.com/d3f1ne/subnerium)
- [rapiddns](https://github.com/d3f1ne/subnerium)
- [securitytrails](https://github.com/d3f1ne/subnerium)
- [urlscan](https://github.com/d3f1ne/subnerium)
- [virustotal](https://github.com/d3f1ne/subnerium)
- [webarchive](https://github.com/d3f1ne/subnerium)
- [whoisxml](https://github.com/d3f1ne/subnerium)

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235606330-8eac2a00-b730-4afa-b7ed-ffc937117bd0.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/subnerium

Thank you for your contribution!
