### ISSUE TITLE
[addtool] Feroxbuster

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#111]
[link]https://github.com/epi052/feroxbuster[/link]
[short_descr] A fast, simple, recursive content discovery tool written in Rust. [/short_descr]
[tags]directories,fuzzing,endpoints[/tags]
[long_descr]feroxbuster uses brute force combined with a wordlist to search for unlinked content in target directories. These resources may store sensitive information about web applications and operational systems, such as source code, credentials, internal network addressing, etc...

This attack is also known as Predictable Resource Location, File Enumeration, Directory Enumeration, and Resource Enumeration.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207301838-026baae2-c47d-4a4c-8304-39180bfbb139.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/feroxbuster

Thank you!
