### ISSUE TITLE
[addtool] certmon

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1114]
[homepage] https://github.com/corelan/certmon [/homepage]
[tags] all,certificate,expiration,monitor [/tags]
[short_descr] certmon.py is a simple certificate expiration monitor script. [/short_descr]
[image] 
![image](https://user-images.githubusercontent.com/5957301/235856277-8bc28c00-95a3-4ac8-8477-fd2903993114.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/certmon

Thank you for your contribution!
