### ISSUE TITLE
[addtool] Tmux

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1117]
[homepage]
https://github.com/tmux/tmux
[/homepage]

[tags]
tmux, terminal, enumaltor
[/tags]

[short_descr]
Tmux is a terminal multiplexer !!
[/short_descr]

[long_descr]
## Welcome to tmux!
tmux is a terminal multiplexer. It lets you switch easily between several programs in one terminal, detach them (they keep running in the background) and reattach them to a different terminal.

**Download** tmux 3.3a here (changes in this version).

See:
	- the getting started guide;
	- how to install tmux;
	- the tmux(1) manual page;
	- and the README.

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/235872221-f6828501-96de-4782-a299-ec7072c2574c.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1117

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
