### ISSUE TITLE
[addtool] httpx

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#112]
[link]https://github.com/projectdiscovery/httpx[/link]
[short_descr] httpx is a fast and multi-purpose HTTP toolkit that allows running multiple probes using the retryablehttp library. [/short_descr]
[tags]projectdiscovery,probing[/tags]
[long_descr]httpx is a fast and multi-purpose HTTP toolkit that allows running multiple probes using the retryablehttp library. It is designed to maintain result reliability with an increased number of threads.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207307104-050add3a-6be9-49d1-9341-68ccf0e997af.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/httpx

Thank you!
