### ISSUE TITLE
[addtool] interactsh

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#113]
[link]https://github.com/projectdiscovery/interactsh[/link]
[short_descr] An OOB interaction gathering server and client library [/short_descr]
[tags]projectdiscovery,oob[/tags]
[long_descr]Interactsh is an open-source tool for detecting out-of-band interactions. It is a tool designed to detect vulnerabilities that cause external interactions.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207307587-8d875551-064d-4c5c-87e2-39f895490201.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/interactsh

Thank you!
