### ISSUE TITLE
[addtool] REcollapse

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1131]
[link] https://github.com/0xacb/recollapse [/link]
[link] https://0xacb.com/2022/11/21/recollapse/ [/link]

[tags] regex, fuzzing, normalization, waf-bypass[/tags]

[short_descr] Helper tool for black-box regex fuzzing.   [/short_descr]

[long_descr]
REcollapse is a helper tool for black-box regex fuzzing to bypass validations and discover normalizations in web applications.
It can also be helpful to bypass WAFs and weak vulnerability mitigations. For more information, take a look at the REcollapse blog post.
The goal of this tool is to generate payloads for testing. Actual fuzzing shall be done with other tools like Burp (intruder), ffuf, or similar.
[/long_descr] 

[image] 
![image](https://user-images.githubusercontent.com/98208035/236385226-f2a9a52c-46d8-47d8-9e14-202ff88d7380.png)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/91
