### ISSUE TITLE
[addtool] RESTler

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1133]
[link] https://github.com/microsoft/restler-fuzzer [/link]

[tags] rest, api, fuzzing [/tags]

[short_descr] RESTler is the first stateful REST API fuzzing tool for automatically testing cloud services through their REST APIs and finding security and reliability bugs in these services.  [/short_descr]

[long_descr]  
## What is RESTler?

RESTler is the first stateful REST API fuzzing tool for automatically testing cloud services through their REST APIs and finding security and reliability bugs in these services. For a given cloud service with an OpenAPI (formerly Swagger) specification, RESTler analyzes its entire specification, and then generates and executes tests that exercise the service through its REST API.

RESTler intelligently infers producer-consumer dependencies among request types from the OpenAPI definition. During testing, it checks for specific classes of bugs and dynamically learns how the service behaves from prior service responses. This intelligence allows RESTler to explore deeper service states reachable only through specific request sequences and to find more bugs.

[/long_descr] 

[image]  
![image](https://user-images.githubusercontent.com/98208035/236386782-873d6c2d-bc48-4bb4-83a3-56e19e93f3d8.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/restler

Thank you for your contribution!
