### ISSUE TITLE
[addtool] whatsapp-osint

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1134]
[link] https://github.com/jasperan/whatsapp-osint [/link]

[tags] whatsapp, osint [/tags]

[short_descr] Logs online/offline events from ANYONE in the world. [/short_descr]

[image]   
![image](https://user-images.githubusercontent.com/98208035/236387308-250bc37b-53b8-43f7-9ca9-2b80d691082b.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
