### ISSUE TITLE
[addtool] hardCIDR

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1135]
[link] https://github.com/trustedsec/hardcidr [/link]

[tags] cidr, enumeration [/tags]

[short_descr] Discover the netblocks, or ranges, (in CIDR notation) owned by the target organization during the intelligence gathering phase of a penetration test. [/short_descr]

[long_descr]  
## Background
A Linux Bash script to discover the netblocks, or ranges, (in CIDR notation) owned by the target organization during the intelligence gathering phase of a penetration test. This information is maintained by the five Regional Internet Registries (RIRs):

ARIN (North America)
RIPE (Europe/Asia/Middle East)
APNIC (Asia/Pacific)
LACNIC (Latin America)
AfriNIC (Africa)

In addition to netblocks and IP addresses, Autonomous System Numbers (ASNs) are also of interest. ASNs are used as part of the Border Gateway Protocol (BGP) for uniquely identifying each network on the Internet. Target organizations may have their own ASNs due to the size of their network or as a result of redundant service paths from peered service providers. These ASNs will reveal additional netblocks owned by the organization.
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236388000-297ce09f-474d-4c30-af4c-007d938e3f46.png)

[/image]

[image]
![image](https://user-images.githubusercontent.com/98208035/236388091-3936d5c3-01cf-472a-a003-8686d699c20e.png)

[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/735
