### ISSUE TITLE
[addtool] wstunnel

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1137]
[link]  https://github.com/erebe/wstunnel     [/link]

[tags] tunnel [/tags]

[short_descr] Tunneling over websocket protocol - Static binary available [/short_descr]

[long_descr] Most of the time when you are using a public network, you are behind some kind of firewall or proxy. One of their purpose is to constrain you to only use certain kind of protocols. Nowadays, the most widespread protocol is http and is de facto allowed by third party equipment.

This tool understands this fact and uses the websocket protocol which is compatible with http in order to bypass firewalls and proxies. Wstunnel allows you to tunnel what ever traffic you want. [/long_descr] 

[image]  
![image](https://user-images.githubusercontent.com/98208035/236388585-df3c1ad6-2035-4ecd-bc46-ba603ce947a4.png)

[/image]

[image]  
![image](https://user-images.githubusercontent.com/98208035/236388496-1813330a-4687-48c7-ab8a-47f0b987706a.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wstunnel

Thank you for your contribution!
