### ISSUE TITLE
[addtool] SpiderSuite

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1138]
[link] https://github.com/3nock/SpiderSuite [/link]

[tags] crawler, gui, recon, webcrawler [/tags]

[short_descr] 
Advance web spider/crawler for cyber security professionals

[/short_descr]

[long_descr]     
## SpiderSuite : 

An advance cross-platform and multi-feature GUI web spider/crawler for cyber security proffesionals. Spider Suite can be used for attack surface mapping and analysis.
For more information visit SpiderSuite's [website](https://SpiderSuite.github.io).

[/long_descr] 

[image]  
![image](https://user-images.githubusercontent.com/98208035/236389954-6477b968-7dae-4dac-ba48-02d4ab021f23.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/spidersuite

Thank you for your contribution!
