### ISSUE TITLE
[addtool] mapcidr

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#114]
[link]https://github.com/projectdiscovery/mapcidr[/link]
[short_descr] Small utility program to perform multiple operations for a given subnet/CIDR ranges. [/short_descr]
[tags]projectdiscovery,cidr[/tags]
[long_descr]mapCIDR is developed to ease load distribution for mass scanning operations, it can be used both as a library and as independent CLI tool.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207307954-e6b5a374-a67b-485e-aee4-d8fb03fcd722.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/mapcidr

Thank you!
