### ISSUE TITLE
[addtool] Hash Muncher

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1140]
[link] https://github.com/lkarlslund/hashmuncher  [/link]

[tags]  NetNTLMv2, ETW, Windows  [/tags]

[short_descr] Grab NetNTLMv2 hashes using ETW with administrative rights on Windows [/short_descr]

[long_descr]     
# Hash Muncher

*Grab NetNTLMv2 hashes using ETW with administrative rights on Windows*

- Uses Event Tracing for Windows (ETW) to get access to raw packet data for SMB authentication packets
- Decodes NTLM message types 2 and 3
- Outputs to stdout
- Press Ctrl-C to stop processing
- Crack hashes with HashCat using -m 5600
[/long_descr] 

[image]   
![image](https://user-images.githubusercontent.com/98208035/236392778-d0182aa7-99e3-4dd8-92e4-ac45ff5147c6.png)

[/image]
[image]   
![image](https://user-images.githubusercontent.com/98208035/236392859-cda6d29e-4e07-477f-ac74-6a66cbff5311.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hash-muncher

Thank you for your contribution!
