### ISSUE TITLE
[addtool] hash-hound

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1145]
[link] https://github.com/hac01/Hash-hound [/link]
[tags] hash, identifier [/tags]
[short_descr] A simple python script to identify different hashes [/short_descr]
[image]
![image](https://user-images.githubusercontent.com/98208035/236613298-36f11631-4603-409a-a48c-e568a0cccd60.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
