### ISSUE TITLE
[addtool] katana

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#115]
[link]https://github.com/projectdiscovery/katana[/link]
[short_descr]A next-generation crawling and spidering framework.[/short_descr]
[tags]projectdiscovery,crawler,recon[/tags]
[long_descr]A next-generation crawling and spidering framework.katana requires url or endpoint to crawl and accepts single or multiple inputs.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207309321-a4157590-ff0b-4043-9328-379be3884b3a.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/katana

Thank you!
