### ISSUE TITLE
[addtool] RootKits-List-Download

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1150]
[link] https://github.com/d30sa1/RootKits-List-Download [/link]

[tags] rootkits [/tags]

[short_descr] The list of all rootkits found so far on github and other sites. [/short_descr]

[image] ![image](https://user-images.githubusercontent.com/98208035/236664494-09695816-4946-4504-be2e-ab212715612e.png) [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
