### ISSUE TITLE
[addtool] Awesome-CobaltStrike

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1151]
[link] https://github.com/zer0yu/Awesome-CobaltStrike [/link]

[tags] CobaltStrike, resources, c2  [/tags]

[short_descr] List of Awesome CobaltStrike Resources [/short_descr]

[long_descr]

• The first part is a collection of quality articles about Cobalt Strike.
• The third part is about the integration of the new features BOF resources.
• This project is to solve the problem of not finding the right aggressor script or BOF when it is needed.

[/long_descr] 

[image]   
![image](https://user-images.githubusercontent.com/98208035/236665555-9ef54ab9-fddf-412f-9c66-a68f53b7a66b.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/awesome-cobaltstrike

Thank you for your contribution!
