### ISSUE TITLE
[addtool] Socialhunte

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1152]
[link] https://github.com/utkusen/socialhunter [/link]

[tags] Crawler, broken-link [/tags]

[short_descr] Crawls the website and finds broken social media links that can be hijacked. [/short_descr]

[long_descr] 
Crawls the given URL and finds broken social media links that can be hijacked. Broken social links may allow an attacker to conduct phishing attacks. It also can cost a loss of the company's reputation. Broken social media hijack issues are usually accepted on the bug bounty programs.

Currently, it supports Twitter, Facebook, Instagram and Tiktok without any API keys.

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236665826-da3dc7d2-ab61-473e-b621-6658b82ffd09.png)

![image](https://camo.githubusercontent.com/65bbd741a7a85edfd02cd1b08d28c021a33eeda8f30f37855ee26f02f028ba1c/68747470733a2f2f61736369696e656d612e6f72672f612f77594d565849484378784f423351505771344665384164766e2e737667)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/socialhunter

Thank you for your contribution!
