### ISSUE TITLE
[addtool] Kscan

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1154]
[link]
https://github.com/lcvvvv/kscan/
[/link]
[link]
https://github.com/lcvvvv/kscan/blob/master/README_ENG.md
[/link]

[tags]
portscan, scanner
[/tags]

[short_descr]
Kscan is an all-round scanner developed purely in Go, with functions such as port scanning, protocol detection, fingerprint recognition, and brute force cracking. 
[/short_descr]

[long_descr]
- - -
```console
 _   __
|#| /#/ Lightweight Asset Mapping Tool by: kv2	
|#|/#/   _____  _____     *     _   _
|#.#/   /Edge/ /Forum|   /#\   |#\ |#|
|##|   |#|___  |#|      /###\  |##\|#|
|#.#\   \#####\|#|     /#/_\#\ |#.#.#|
|#|\#\ /\___|#||#|____/#/###\#\|#|\##|
|#| \#\\#####/ \#####/#/     \#\#| \#|

```

Kscan is an asset mapping tool that can perform port scanning, TCP fingerprinting and banner capture for specified assets, and obtain as much port information as possible without sending more packets. It can perform automatic brute force cracking on scan results, and is the first open source RDP brute force cracking tool on the go platform.

[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236757302-5c7ef10e-38cc-4bd2-b654-2f9ead8c9c19.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/kscan

Thank you for your contribution!
