### ISSUE TITLE
[addtool] Klyda

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1155]
[link]
https://github.com/Xeonrx/Klyda
[/link]

[tags]
bruteforcing, passwords
[/tags]

[short_descr]
Highly configurable script for dictionary/spray attacks against online web applications.
[/short_descr]

[long_descr]
The Klyda project has been created to aid in quick credential based attacks against online web applications.
Klyda supports the use from simple password sprays, to large multithreaded dictionary attacks.

Klyda is a new project, and I am looking for any contributions. Any help is very appreciated.
Klyda offers simple, easy to remember usage; however, still offers configurability for your needs:

- Mulithreaded tasks
- Combine wordlists for larger scale attacks
- Blacklisting data to narrow down results
- Limit thread speed for sneaky purposes
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236758072-09380bda-fc30-4172-a9bb-5b918043b8f6.png)
[/image]

[image]
![image](https://user-images.githubusercontent.com/98208035/236758107-81398536-7b78-45c0-9ec3-298da2bf19fd.png)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/klyda

Thank you for your contribution!
