### ISSUE TITLE
[addtool] OSCP-Reporting

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1156]
[link]
https://github.com/Syslifters/OSCP-Reporting
[/link]
[link]
https://cloud.sysreptor.com/oscp/signup/
[/link]
[link]
https://docs.sysreptor.com/
[/link]

[tags]
Reporting
[/tags]

[short_descr]
Offensive Security OSCP, OSWE, OSCE, OSEE, OSWP Exam and Lab Reporting / Note-Taking Tool
[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/236759828-f42b6ddd-51b2-4a27-927b-aef893e1d051.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1156
