### ISSUE TITLE
[addtool] Offsec Youtube Channel

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1157]
[link]
https://www.youtube.com/@OffSecTraining
[/link]

[tags]
learning, training
[/tags]

[short_descr]
Offensive Security Official Youtube Channel.
[/short_descr]

[image]
![image](https://user-images.githubusercontent.com/98208035/236764383-4cd6dc3c-66f0-488a-8c89-75d61e0580f8.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/offensive-security

Thank you for your contribution!
