### ISSUE TITLE
[addtool] John Hammond Youtube Channel

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1158]
[link]
https://www.youtube.com/@_JohnHammond
[/link]

[tags]
learning, training
[/tags]

[short_descr]
Free cybersecurity education, without the fluff.
[/short_descr]

[long_descr]
John Hammond is a well-known cybersecurity expert and a popular YouTuber who creates videos on various topics related to information security, ethical hacking, and penetration testing. His YouTube channel primarily focuses on teaching ethical hacking and cybersecurity skills to beginners and intermediate-level learners.

On his channel, John provides in-depth tutorials, practical demonstrations, and hands-on exercises that help viewers understand various cybersecurity concepts and techniques. He also shares his knowledge and experience in the field, and regularly reviews security tools and products to help viewers make informed decisions.

Overall, John Hammond's YouTube channel is an excellent resource for anyone interested in learning more about cybersecurity, ethical hacking, and related topics.
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236766168-d96d1b41-993d-4e54-a630-d020a4f20c8d.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/john-hammond

Thank you for your contribution!
