### ISSUE TITLE
[addtool] NetworkChuck

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1159]
[link]
https://www.youtube.com/@NetworkChuck
[/link]

[tags]
learning, training, resources
[/tags]

[short_descr]
Network Chuck teaches networking and cybersecurity.
[/short_descr]

[long_descr]
Network Chuck is a popular YouTuber and network engineer who creates videos on various topics related to networking, cybersecurity, and cloud computing. His YouTube channel primarily focuses on teaching these technical subjects to beginners and intermediate-level learners.

On his channel, Network Chuck provides practical demonstrations and step-by-step tutorials that help viewers understand complex networking and cybersecurity concepts. He also shares his experiences and insights from his work as a network engineer and provides valuable tips and tricks for viewers to excel in their careers.

In addition to technical content, Network Chuck also creates motivational and inspirational videos that encourage viewers to pursue their passions and achieve their goals. He shares his personal story of how he transitioned from a retail job to a successful career in IT, inspiring others to follow their dreams and pursue a career in the tech industry.

Overall, Network Chuck's YouTube channel is a valuable resource for anyone interested in learning more about networking, cybersecurity, and cloud computing, and for those who seek motivation and inspiration to pursue their dreams.
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236767290-fcff0c4f-2ef0-49b9-b989-7580f2bf3ac5.png)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/networkchuck

Thank you for your contribution!
