### ISSUE TITLE
[addtool] uncover

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#116]
[link]https://github.com/projectdiscovery/uncover[/link]
[short_descr]Quickly discover exposed hosts on the internet using multiple search engines. [/short_descr]
[tags]projectdiscovery,recon,assetdiscovery[/tags]
[long_descr]uncover is a go wrapper using APIs of well known search engines to quickly discover exposed hosts on the internet. It is built with automation in mind, so you can query it and utilize the results with your current pipeline tools.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207309781-4c155430-c634-481c-93d4-72d4539f34db.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/uncover

Thank you!
