### ISSUE TITLE
[addtool] Ippsec

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1160]
[link]
https://www.youtube.com/@ippsec
[/link]

[link]
https://ippsec.rocks
[/link]

[tags]
learning, training, resources
[/tags]

[short_descr]

IPPSEC's YouTube channel offers educational content on cybersecurity and hacking.
[/short_descr]

[long_descr]

IPPSEC is a highly regarded cybersecurity expert and YouTuber who creates educational content on hacking, penetration testing, and other technical security topics. His YouTube channel features comprehensive walkthroughs of real-world hacking scenarios, providing viewers with practical insights and strategies for improving their cybersecurity skills. IPPSEC's engaging teaching style and attention to detail make his content accessible and valuable to both beginners and experienced cybersecurity professionals alike. With his dedication to sharing knowledge and promoting a better understanding of cybersecurity, IPPSEC's YouTube channel is an excellent resource for anyone looking to learn more about this exciting and ever-evolving field. His Channel has almost every HackTheBox Machines walkthrough.
[/long_descr] 

[image]
![image](https://user-images.githubusercontent.com/98208035/236769054-158b73cb-79d9-47d1-835a-70b90093a186.png)
[/image]

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
