### ISSUE TITLE
[addtool] Tool nuclei-wordfence-cve

### ISSUE THREAD

**Issue by topscoder** [gwen001/offsectools_www#1161]
[link]https://github.com/topscoder/nuclei-wordfence-cve[/link]
[tags]nuclei,wordfence,wordpress,cve,vuln[/tags]
[short_descr]A big collection of Nuclei templates dedicated to WordPress core, plugins and themes vulnerabilities. Updated every day.[/short_descr]
[long_descr]As wordfence.com publishes new CVE's and related vulnerabitlities of WordPress, this project aims to collect those CVE's and create Nuclei templates out of them.[/long_descr] 
[image]https://user-images.githubusercontent.com/86197446/225912783-bb6c5fa9-ce45-488b-a1fd-5af705b7cced.jpg[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by topscoder** [comment]
[link] https://github.com/topscoder/nuclei-wordfence-cve [/link]
[tags] nuclei,wordfence,wordpress,cve,vuln [/tags]
[short_descr] A big collection of Nuclei templates dedicated to WordPress core, plugins and themes vulnerabilities. Updated every day. [/short_descr]
[long_descr] As wordfence.com publishes new CVE's and related vulnerabitlities of WordPress, this project aims to collect those CVE's and create Nuclei templates out of them. [/long_descr]
[image] https://user-images.githubusercontent.com/86197446/225912783-bb6c5fa9-ce45-488b-a1fd-5af705b7cced.jpg [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/nuclei-wordfence-cve

Thank you for your contribution!
