### ISSUE TITLE
[addtool] Tool Haylxon

### ISSUE THREAD

**Issue by pwnwriter** [gwen001/offsectools_www#1162]
[link] 
https://github.com/pwnwriter/haylxon 
[/link]

[link]
https://crates.io/crates/hxn 
[/link]

[link] 
https://aur.archlinux.org/packages/haylxon  
[/link]

[tags] 
osint,screenshot-utility, bug-hunting-tool, recon  
[/tags]

[short_descr]
Blazing-fast tool to grab screenshots of your domain list right from terminal. 
[/short_descr]

[long_descr]
Haylxon is a tool embodying the [K1SS](https://en.wikipedia.org/wiki/KISS_principle) philosophy that allows you to take screenshots of webpages/URLs at lightning-fast speeds using chrome's headless feature in backend.
[/long_descr] 

[image]
https://0x0.st/HZ3e.png   
[/image]

![image](https://user-images.githubusercontent.com/90331517/236869522-160bedc7-c5e1-4add-afcc-8d30616064ae.png)

**Comment by pwnwriter** [comment]
[link] 
https://github.com/pwnwriter/haylxon 
[/link]

[link]
https://crates.io/crates/hxn 
[/link]

[link] 
https://aur.archlinux.org/packages/haylxon  
[/link]

[tags] 
osint,screenshot-utility, bug-hunting-tool, recon  
[/tags]

[short_descr]
Blazing-fast tool to grab screenshots of your domain list right from terminal. 
[/short_descr]

[long_descr]
Haylxon is a tool embodying the [K1SS](https://en.wikipedia.org/wiki/KISS_principle) philosophy that allows you to take screenshots of webpages/URLs at lightning-fast speeds using chrome's headless feature in backend.
[/long_descr] 

[image]
https://0x0.st/HZ3e.png   
[/image]

![image](https://user-images.githubusercontent.com/90331517/236869522-160bedc7-c5e1-4add-afcc-8d30616064ae.png)

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/haylxon

Thank you for your contribution!
