### ISSUE TITLE
[addtool] octosql

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1166]
[link] https://github.com/cube2222/octosql [/link]
[tags] all,sql,database [/tags]
[short_descr] OctoSQL is predominantly a CLI tool which lets you query a plethora of databases and file formats. [/short_descr]
[image] https://github.com/cube2222/octosql/raw/main/images/octosql-demo.gif [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/octosql

Thank you for your contribution!
