### ISSUE TITLE
[addtool] BugBountyScanner

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1169]
[link] https://github.com/chvancooten/BugBountyScanner [/link]
[tags] all,bugbounty,scanner [/tags]
[short_descr] A Bash script and Docker image for Bug Bounty reconnaissance, intended for headless use. [/short_descr]
[image] 
https://user-images.githubusercontent.com/5957301/237298753-c58e811b-290c-4034-a71c-7a06afe480f1.png
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/bugbountyscanner

Thank you for your contribution!
