### ISSUE TITLE
[addtool] cloudlist

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#117]
[link]https://github.com/projectdiscovery/cloudlist[/link]
[short_descr] Cloudlist is a tool for listing Assets from multiple Cloud Providers. [/short_descr]
[tags]projectdiscovery,aws,gcp,azure[/tags]
[long_descr]Cloudlist is a multi-cloud tool for getting Assets from Cloud Providers. This is intended to be used by the blue team to augment Attack Surface Management efforts by maintaining a centralized list of assets across multiple clouds with very little configuration efforts.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207310030-39a14d41-e77d-4264-8ba8-4814effd8532.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/cloudlist

Thank you!
