### ISSUE TITLE
[addtool] Jeeves

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1170]
[link] https://github.com/ferreiraklet/Jeeves [/link]
[tags] all,sql,sqli,injection [/tags]
[short_descr] Jeeves is made for looking to Time-Based Blind SQLInjection through recon. [/short_descr]
[image] https://github.com/ferreiraklet/Jeeves/raw/main/gojayyyy.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
