### ISSUE TITLE
[addtool] Wolfy

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1172]
[link] https://github.com/ferreiraklet/wolfy [/link]
[tags] all,AV,bypass [/tags]
[short_descr] Wolfy is a tool which bypass AVs by using a crypter + the tool Condor from mrempy/Condor [/short_descr]
[image] https://github.com/ferreiraklet/wolfy/blob/main/images/wolfy.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
