### ISSUE TITLE
[addtool] Airixss

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1175]
[link] https://github.com/ferreiraklet/airixss [/link]
[tags] all,xss,endpoints,recon [/tags]
[short_descr] Airixss is for checking reflection in recon process to find possible xss vulnerable endpoints. [/short_descr]
[image] https://github-production-user-asset-6210df.s3.amazonaws.com/5957301/237304368-37e1d168-f35a-4773-8592-885d4a40a7d6.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
