### ISSUE TITLE
[addtool] icmpdoor

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1177]
[link] https://github.com/krabelize/icmpdoor [/link]
[tags] all,icmp,reverseshell,shell [/tags]
[short_descr] icmpdoor is an ICMP rev shell written in Python3 and scapy. [/short_descr]
[image] https://github-production-user-asset-6210df.s3.amazonaws.com/5957301/237306598-043a878d-cc8a-4488-825e-ae0d4b96b772.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/icmpdoor

Thank you for your contribution!
