### ISSUE TITLE
[addtool] icmp_shell

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1178]
[link] https://github.com/sin5678/icmp_shell [/link]
[tags] all,icmp,shell [/tags]
[short_descr] shell over icmp, server run at linux and client run at windows [/short_descr]
[image] https://github-production-user-asset-6210df.s3.amazonaws.com/5957301/237307345-bb513fa0-5d73-4f1c-9197-33fbeec8b053.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
