### ISSUE TITLE
[addtool] Scopein

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1179]
[link] https://github.com/ferreiraklet/scopein [/link]
[tags] all,recon,scan,scope [/tags]
[short_descr] Scopein only brings to you urls in scope, easing recon and avoiding scanning out of scope websites. [/short_descr]
[image] https://github-production-user-asset-6210df.s3.amazonaws.com/5957301/237308417-fba9b3d6-47e2-41bd-8177-561c41b677d4.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/scopein

Thank you for your contribution!
