### ISSUE TITLE
[addtool] proxify

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#118]
[link]https://github.com/projectdiscovery/proxify[/link]
[short_descr] Swiss Army knife Proxy tool for HTTP/HTTPS traffic capture, manipulation, and replay on the go. [/short_descr]
[tags]projectdiscovery,proxy[/tags]
[long_descr]Swiss Army Knife Proxy for rapid deployments. Supports multiple operations such as request/response dump, filtering and manipulation via DSL language, upstream HTTP/Socks5 proxy. Additionally, a replay utility allows to import the dumped traffic (request/responses with correct domain name) into BurpSuite or any other proxy by simply setting the upstream proxy to proxify.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207310440-d937748f-9b1a-4cc5-8a58-78b8a01d4e4a.png)

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/proxify

Thank you!
