### ISSUE TITLE
[addtool] Invoke-ADEnum

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1185]
[link]
https://github.com/Leo4j/Invoke-ADEnum
[/link]

[tags]
activedirectory
[/tags]

[short_descr]
Active Directory Enumerator - Automate Active Directory Enumeration using PowerView
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/48493a09-91d8-4932-9426-fc67b347ec58)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/invoke-adenum

Thank you for your contribution!
