### ISSUE TITLE
[addtool] API-fuzzer

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1187]
[link]
https://github.com/Fuzzapi/API-fuzzer
[/link]

[tags]
api, fuzzing
[/tags]

[short_descr]
It allows to fuzz request attributes using common pentesting techniques and lists vulnerabilities.
[/short_descr]

[long_descr]
`API_Fuzzer` gem accepts a API request as input and returns vulnerabilities possible in the API. Following are the main check involved in API_Fuzzer gem

- Cross-site scripting vulnerability
- SQL injection
- Blind SQL injection
- XML External entity vulnerability
- IDOR (in specific cases)
- API Rate Limiting
- Open redirect vulnerabilities
- Information Disclosure flaws
- Info leakage through headers
- Cross-site request forgery vulnerability
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/65c7fcf6-d3a2-4a72-a12f-5c6f39c9da67)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/api-fuzzer

Thank you for your contribution!
