### ISSUE TITLE
[addtool] ApkHack-BackDoor

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1189]
[link]
https://github.com/BitWalls-ops/ApkHack-BackDoor
[/link]

[tags]
apk, backdoor
[/tags]

[short_descr]
ApkHack-BackDoor is a shell script that simplifies the process of adding a backdoor to any Android APK file.
[/short_descr]

[long_descr]
ApkHack-BackDoor is a shell script that simplifies the process of adding a backdoor to any Android APK file. Users of this shell script should have working knowledge of any Linux distribution, Bash, Metasploit, Apktool, the Android SDK, smali, etc.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a8be8be5-2aea-4a47-b860-b6bcb3b59e3d)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
