### ISSUE TITLE
[addtool] GetLAPSPassword

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1190]
[link]
https://github.com/dru1d-foofus/GetLAPSPassword
[/link]

[tags]
activedirectory
[/tags]

[short_descr]
A LAPS dumper written using the impacket library.
[/short_descr]

[long_descr]
A feeble attempt at writing a LAPS dumping tool that supports both NTLM and Kerberos auth using the impacket library.

Initial structure of this tool was taken from the impacket example GetADUsers.py (https://github.com/fortra/impacket/raw/master/examples/GetADUsers.py) and the LDAP queries were taken from https://github.com/n00py/LAPSDumper/.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/0094f878-c65d-46dd-a934-33c16103a3ce)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
