### ISSUE TITLE
[addtool] Reflector

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1191]
[link]
https://github.com/aliyugombe/reflector
[/link]

[tags]
xss, reflected-xss
[/tags]

[short_descr]
Reflector is cli tool written using golang to test for reflected parameters in list of urls to test for reflected xss
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/3095d290-08e1-4b9c-b9d0-53eff492b7d9)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
