### ISSUE TITLE
[addtool] docker-osmedeus v4

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1192]
[link]
https://github.com/mablanco/docker-osmedeus
[/link]

[tags]
docker, reconnaissance
[/tags]

[short_descr]
Docker image for Osmedeus, a fully automated offensive security tool for reconnaissance and vulnerability scanning
[/short_descr]

[long_descr]
Docker image for Osmedeus, a fully automated offensive security tool for reconnaissance and vulnerability scanning (https://github.com/j3ssie/Osmedeus). This image is built upon Debian's Bullseye slim image.

On 1st January 2022, Osmedeus' main developer (j3ssie) launched a beta of the new 4.0 version, which superseeds the previous v2 based on Django. While this README covers v4, the [READMEv2](https://github.com/mablanco/docker-osmedeus/blob/master/READMEv2.md) file covers both the 1.5 and the 2.x versions.

From v4.0.0 on, the Docker image latest tag references the newest 4.x available version.

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/bb0b5e37-be5e-4bcb-b668-f805c45ae2bf)

[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/125f94a6-f86a-429d-891c-d8abb654fb92)

[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/068e9e3c-f830-4ab9-a21a-1bd05f424b44)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
