### ISSUE TITLE
[addtool] HBSQLI

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1193]
[link]
https://github.com/SAPT01/HBSQLI
[/link]

[tags]
sqli
[/tags]

[short_descr]
Automated Tool for Testing Header Based Blind SQL Injection
[/short_descr]

[long_descr]
HBSQLI is an automated command-line tool for performing Header Based Blind SQL injection attacks on web applications. It automates the process of detecting Header Based Blind SQL injection vulnerabilities, making it easier for security researchers , penetration testers & bug bounty hunters to test the security of web applications.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/505e0a39-d18a-411e-9192-4a9ba69a6b2c)
[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hbsqli

Thank you for your contribution!
