### ISSUE TITLE
[addtool] Gowhois

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1194]
[link]
https://github.com/famasoon/gowhois
[/link]

[tags]
whois, enumeration
[/tags]

[short_descr]
whois command implemented by golang with awesome whois servers list
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9156c455-942d-439f-9511-8e2bda098e8f)

[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/gowhois

Thank you for your contribution!
