### ISSUE TITLE
[addtool] wpfinger

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1197]
[link]
https://github.com/LeakIX/wpfinger
[/link]

[tags]
wordpress, scanner
[/tags]

[short_descr]
wpfinger is a red-team WordPress scanning tool.
[/short_descr]

[long_descr]
## Features

- Core version detection
- Plugin scanning through fingerprinting
- Vulnerability output, using database from [Wordfence](https://www.wordfence.com/intelligence-documentation/v2-accessing-and-consuming-the-vulnerability-data-feed/)
- Written in Go, So it's very fast!
[/long_descr] 

[image]
![](https://camo.githubusercontent.com/b351cc46fa7dd24647ddc95a7c5ff281aa40c253880e5e4fdf037d5f6ec360ce/68747470733a2f2f6d656469612e6c65616b69782e6e65742f777066696e6765722e676966)

[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e9e975bb-8f33-4f23-97a3-34bbf03491d0)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wpfinger

Thank you for your contribution!
