### ISSUE TITLE
[addtool] DorkGPT

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1198]
[link] https://www.dorkgpt.com/ [/link]
[tags] all,dork,gpt,google [/tags]
[short_descr] Generate Google Dorks with AI [/short_descr]
[image] ![image](https://github.com/gwen001/offsectools_www/assets/5957301/10e2477d-8489-45b3-993c-65d537dcc0ae) [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/dorkgpt

Thank you for your contribution!

**Comment by euriconicacio** [comment]
Why, @gwen001 ?
