### ISSUE TITLE
[addtool] docker_nginx_logger

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1201]
[link] https://github.com/therceman/docker_nginx_logger [/link]
[tags] all,nginx,logger,docker [/tags]
[short_descr] Nginx Request Logger Server [Docker Version] [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/a5bf001d-0d2c-4a13-a5b4-80a830ef7291)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by euriconicacio** [comment]
Why, @gwen001 ?
