### ISSUE TITLE
[addtool] HTTP-traceroute

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1207]
[link] https://github.com/PaulSec/HTTP-traceroute [/link]
[tags] all,http,traceroute,go [/tags]
[short_descr] HTTP-traceroute in Go [/short_descr]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/5957301/142023fa-bb6f-4386-9b99-ddf3d2ce7118)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/http-traceroute

Thank you for your contribution!
