### ISSUE TITLE
[addtool] What is this browser?

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1209]
[link] https://github.com/PaulSec/what-is-this-browser [/link]
[tags] all,script,browser,agent [/tags]
[short_descr] From a simple User-Agent, it tells you what might be the browser, version and platform used. [/short_descr]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/5957301/5608aaab-3f5e-4384-8a82-5d02c152af9c)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by euriconicacio** [comment]
Why, @gwen001?
