### ISSUE TITLE
[addtool] Dir-Xcan

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1212]
[link] https://github.com/NoobieDog/Dir-Xcan [/link]
[tags] all,directory,scanner,python [/tags]
[short_descr] Dir-Xcan6 is a free and open-source scanner based on OWASP's DirBuster that is now closed. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/fa974b08-e6b4-48e5-ab1a-b41cd67bff5d)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by euriconicacio** [comment]
Why, @gwen001 ?
