### ISSUE TITLE
[addtool] PTF

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1213]
[link] https://github.com/trustedsec/ptf [/link]
[tags] all,ptf,pentest,framework [/tags]
[short_descr] The Penetration Testers Framework (PTF) is a way for modular support for up-to-date tools. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/b67c49f5-df9a-4936-a31f-8318857a6a88)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ptf

Thank you for your contribution!
