### ISSUE TITLE
[addtool] orpheus

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1215]
[link] https://github.com/trustedsec/orpheus [/link]
[tags] all,kerberos,bypass,kdc,encryption [/tags]
[short_descr] Bypassing Kerberoast Detections with Modified KDC Options and Encryption Types [/short_descr]
[image] https://raw.githubusercontent.com/trustedsec/orpheus/main/orpheus.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
