### ISSUE TITLE
[addtool] SeeYouCM-Thief

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1216]
[link] https://github.com/trustedsec/SeeYouCM-Thief [/link]
[tags] all,configuration,ssh,credentials,parser,cisco [/tags]
[short_descr] Automatically download and parse conf files from Cisco phone systems searching for SSH credentials. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/6154ec0a-6360-4865-af53-b6c433052293)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
