### ISSUE TITLE
[addtool] SysWhispers

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1217]
[link] https://github.com/jthuraisamy/SysWhispers [/link]
[tags] all,evasion,syscalls [/tags]
[short_descr] SysWhispers helps with evasion by generating header/ASM files that can use with direct system calls. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/f37ac658-9810-4c36-a666-478b4045a8dc)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/syswhispers

Thank you for your contribution!
