### ISSUE TITLE
[addtool] deser-node

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1218]
[link] https://github.com/klezVirus/deser-node [/link]
[tags] all,node,deserialization [/tags]
[short_descr] Deser-node is a script to automatically generate serialized payloads for NodeJS driven applications. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/37947158-25ff-407f-b25b-e190555f8a14)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/deser-node

Thank you for your contribution!
