### ISSUE TITLE
[addtool] chameleon

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1219]
[link] https://github.com/klezVirus/chameleon [/link]
[tags] all,powershell,obfuscator [/tags]
[short_descr] Chameleon is yet another PowerShell obfuscation tool designed to bypass AMSI and antiviruses. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/b1ccfe3b-258e-4661-a5ba-5d2ab7f533bd)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
