### ISSUE TITLE
[addtool] smbcrawler

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1221]
[link]
https://github.com/SySS-Research/smbcrawler
[/link]

[tags]
smb, crawler
[/tags]

[short_descr]
smbcrawler is no-nonsense tool that takes credentials and a list of hosts and 'crawls' (or 'spiders') through those shares.
[/short_descr]

[long_descr]
Features:

- takes host names, IP addresses, IP ranges, or an nmap xml file as input
- checks permissions (check for 'write' permissions is opt-in, because it requires creating an empty directory on the share)
- crawling depth is customizable
- threaded
- outputs machine-readable formats
- pass-the-hash support
- auto-download interesting files
- report potential secrets
- pausable
- interactively skips single shares and hosts

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/20655ae8-57e9-4114-9071-ae451dedb757)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: http://localhost:3000/tool/smbcrawler

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/smbcrawler

Thank you for your contribution!
