### ISSUE TITLE
[addtool] Prenum

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1222]
[link]
https://github.com/4ndr34z/prenum
[/link]

[tags]
windows, activedirectory
[/tags]

[short_descr]
The perils of the Pre-Windows 2000 compatible access group in a Windows Domain.
[/short_descr]

[long_descr]
Functions : 

=> Full AMSI-Bypass
=> Reflectively loading Rubeus and Certify
=> Enumerate and test all computers in AD; check if their password is the same as the computername
=> Enumerate all users in AD; check if the password is blank
=> Passwordspray all users in AD
=> Request Kerberos TGT for computer and/or user-accounts found vulnerable (Using Rubeus)
=> Test for vulnerable certificate templates (Using Certify)
=> Do simple LDAP searches
=> Run any Rubeus command
=> Run any Certify command

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/56423e9e-e1c5-4541-802e-199777a9bf04)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: http://localhost:3000/tool/prenum

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/prenum

Thank you for your contribution!
