### ISSUE TITLE
[addtool] XXElixir

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1224]
[link]
https://github.com/kljunowsky/XXElixir
[/link]

[tags]
xxe, file-upload
[/tags]

[short_descr]
This tool is designed to test for file upload and XXE vulnerabilities by poisoning XLSX files.
[/short_descr]

[long_descr]
This tool is designed to test for file upload and XXE (XML External Entity) vulnerabilities by poisoning an XLSX file. It allows the user to inject custom XML content or specify an out-of-band URL to retrieve data from an external entity. The tool works by unzipping the input XLSX file, modifying the workbook.xml file to include the user-specified XML content or URL, and then zipping the modified directory back into a new XLSX file. The resulting file can be used to test for file upload and XXE vulnerabilities in web applications that accept XLSX files.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/5fad1e11-0fa5-410f-a0c8-708bedff75e8)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/xxelixir

Thank you for your contribution!
