### ISSUE TITLE
[addtool] HardHat C2

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1228]
[link]
https://github.com/DragoQCC/HardHatC2
[/link]

[tags]
c2, framework
[/tags]

[short_descr]
A cross-platform, collaborative, Command & Control framework designed for red teaming and ease of use.
[/short_descr]

[long_descr]
Disclaimer:
HardHat is a multiplayer C# .NET-based command and control framework. Designed to aid in red team engagements and penetration testing. HardHat aims to improve the quality of life factors during engagements by providing an easy-to-use but still robust C2 framework.
It contains three primary components, an ASP.NET teamserver, a blazor .NET client, and C# based implants.

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9ab4da89-e823-4c0f-b01b-03ea3eadeb62)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/08a0c471-93c9-48dc-9803-60f4eef147a2)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/8df9c783-2861-43f3-bc83-e4877d098289)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hardhat-c2

Thank you for your contribution!
