### ISSUE TITLE
[addtool] Poastal

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1229]
[link]
https://github.com/jakecreps/poastal
[/link]

[tags]
emails, osint
[/tags]

[short_descr]
Poastal - the Email OSINT tool
[/short_descr]

[long_descr]
Poastal is an email OSINT tool that provides valuable information on any email address. With Poastal, you can easily input an email address and it will quickly answer several questions, providing you with crucial information.

✨Features : 
=> Determine the name of the person who has the email.
=> Check if the email is deliverable or not.
=> Find out if the email is disposable or not.
=> Identify if the email is considered spam.
=> Check if the email is registered on popular platforms such as Facebook, Twitter, Snapchat, Parler, Rumble, MeWe, Imgur, Adobe, Wordpress, and Duolingo.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6b341774-833b-4423-bd5d-6745d79d04a4)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e26652dd-ac93-4766-a478-4379f90466e5)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/poastal

Thank you for your contribution!
