### ISSUE TITLE
[addtool] js-xss

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1235]
[link] https://github.com/leizongmin/js-xss [/link]
[link] https://jsxss.com/en/index.html [/link]
[tags] all,xss,javascript,js [/tags]
[short_descr] Sanitize untrusted HTML (to prevent XSS) with a configuration specified by a Whitelist. [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/301ed06f-c706-4391-bd27-218de60d1bf4)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
