### ISSUE TITLE
[addtool] XssPy

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1236]
[link] https://github.com/faizann24/XssPy [/link]
[tags] all,xss,python [/tags]
[short_descr] XssPy - Web Application XSS Scanner [/short_descr]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/5957301/6495e7f9-bc97-4de2-8589-ce8d7e5c76eb)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
