### ISSUE TITLE
[addtool]  csprecon

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1237]
[link]
https://github.com/edoardottt/csprecon
[/link]

[tags]
bug-bounty, subdomains, domains
[/tags]

[short_descr]
Discover new target domains using Content Security Policy
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/dbb895fe-bce6-4cdb-8f43-447878f6a934)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/421
