### ISSUE TITLE
[addtool] CypherDog 4.3

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1241]
[link]
https://github.com/SadProcessor/CypherDog
[/link]

[tags]
activedirectory
[/tags]

[short_descr]
PoSh BloodHound Dog Whisperer
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/c21eeb5b-cda2-447a-8a34-423967eae456)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cypherdog

Thank you for your contribution!
