### ISSUE TITLE
[addtool] Proving Grounds

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1243]
[link]
https://www.offsec.com/labs/individual/
[/link]

[link]
https://portal.offsec.com/labs/play
[/link]

[link]
https://portal.offsec.com/labs/practice
[/link]

[tags]
resources, learn, train
[/tags]

[short_descr]
Offensive Security’s Proving Grounds training labs.
[/short_descr]

[long_descr]
Practice your pentesting skills in a standalone, private lab environment with the additions of PG Play and PG Practice to Offensive Security’s Proving Grounds training labs.

* With PG Play, students will receive three daily hours of free, dedicated access to the VulnHub community generated Linux machines.

* A subscription to PG Practice includes all the features of PG Play plus additional Windows and Linux machines developed by OffSec experts with unlimited time on any targets.

Learn, have fun, and sharpen your hacking skills with new machines added monthly.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b68727f4-d5e0-4d80-93c3-261f47bcc21a)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
