### ISSUE TITLE
[addtool] adPEAS

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1246]
[link]
https://github.com/61106960/adpeas
[/link]

[tags]
activedirectory, privilege-escalation
[/tags]

[short_descr]
Powershell tool to automate Active Directory enumeration.
[/short_descr]

[long_descr]
adPEAS is a Powershell tool to automate Active Directory enumeration. In fact, adPEAS is like a wrapper for different other cool projects like

PowerView
PoshADCS
Bloodhound
and some own written lines of code
As said, adPEAS is a wrapper for other tools. They are almost all written in pure Powershell but some of them are included as compressed binary blob or C# code.

adPEAS-Light is a version without Bloodhound and it is more likely that it will not blocked by an AV solution.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/93827f0d-ab20-402d-9a78-c7b41f0f6b74)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/adpeas

Thank you for your contribution!
