### ISSUE TITLE
[addtool] PassMute

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1249]
[link]
https://github.com/HITH-Hackerinthehouse/PassMute
[/link]

[tags]
password-generator, password, mutation
[/tags]

[short_descr]
PassMute - A Password Trasmutation/Mutator tool
[/short_descr]

[long_descr]
This is a command-line tool written in Python that applies one or more transmutation rules to a given password or a list of passwords read from one or more files. The tool can be used to generate transformed passwords for security testing or research purposes. Also, while you doing pentesting it will be very useful tool for you to brute force the passwords!!

How Passmute can also help to secure our passwords more?
PassMute can help to generate strong and complex passwords by applying different transformation rules to the input password. However, password security also depends on other factors such as the length of the password, randomness, and avoiding common phrases or patterns.

The transformation rules include:
[+] reverse: reverses the password string
[+] uppercase: converts the password to uppercase letters
[+] lowercase: converts the password to lowercase letters
[+] swapcase: swaps the case of each letter in the password
[+] capitalize: capitalizes the first letter of the password
[+] leet: replaces some letters in the password with their leet equivalents
[+] strip: removes all whitespace characters from the password

The tool can also write the transformed passwords to an output file and run the transformation process in parallel using multiple threads.

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/973a7512-688f-4f42-9a54-4cc9f7b91a59)

[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7c0b8f8f-bd26-4909-a312-51481bf2c2e0)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
