### ISSUE TITLE
[addtool] Fresh Resolvers

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1250]
[link]
https://github.com/Findomain/fresh-resolvers
[/link]

[tags]
DNS, resolvers
[/tags]

[short_descr]
List of fresh DNS resolvers updated every 12h.
[/short_descr]

[long_descr]
Uses [DNS Validator](https://github.com/vortexau/dnsvalidator) to generate a list of fresh working DNS resolvers every day.

List should reliably stay updated by utilizing a scheduled Github action instead of having to rely on something like an external VPS.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/41944fe7-9512-49f9-bff7-c2911ba4b7bf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/fresh-resolvers

Thank you for your contribution!
