### ISSUE TITLE
[addtool] SysReptor

### ISSUE THREAD

**Issue by cmahrl** [gwen001/offsectools_www#1265]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]https://docs.sysreptor.com/[/link]
[link]https://github.com/Syslifters/sysreptor[/link]
[link]https://github.com/Syslifters/OffSec-Reporting[/link]
[tags]reports,organizer,collaboration,resources,utils[/tags]
[short_descr]Easy and customisable pentest report creator based on simple web technologies.[/short_descr]
[long_descr]SysReptor is a fully customisable, offensive security reporting tool designed for pentesters, red teamers and other security-related people alike. You can create designs based on simple HTML and CSS, write your reports in user-friendly Markdown and convert them to PDF with just a single click, in the cloud or on-premise![/long_descr] 
[image]https://docs.sysreptor.com/images/logo-invert.svg[/image]
[image]https://docs.sysreptor.com/images/logo.svg[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by cmahrl** [comment]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]Homepage/Docs: https://docs.sysreptor.com/[/link]
[link]GitHub-Repo: https://github.com/Syslifters/sysreptor[/link]
[link]Dedicated OffSec-Repo: https://github.com/Syslifters/OffSec-Reporting[/link]
[tags]list of tags separated by comma: reports,organizer,collaboration,resources,utils[/tags]
[short_descr]Easy and customisable pentest report creator based on simple web technologies.[/short_descr]
[long_descr]SysReptor is a fully customisable, offensive security reporting tool designed for pentesters, red teamers and other security-related people alike. You can create designs based on simple HTML and CSS, write your reports in user-friendly Markdown and convert them to PDF with just a single click, in the cloud or on-premise![/long_descr] 
[image]https://docs.sysreptor.com/images/logo-invert.svg[/image]
[image]https://docs.sysreptor.com/images/logo.svg[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/sysreptor

Thank you for your contribution!

**Comment by cmahrl** [comment]
Hi @gwen001, unfortunately it is the wrong logo. Could you please use the following image:

https://camo.githubusercontent.com/4119add457af411ce17532d296242258bdba347f8aad52e1bab4e8e0f665f99f/68747470733a2f2f646f63732e737973726570746f722e636f6d2f696d616765732f6c6f676f2d696e766572742d776974682d746578742e706e67

Thank you!
