### ISSUE TITLE
[addtool] Depix

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#1266]
[link] https://github.com/beurtschipper/Depix [/link]
[tags] all,credentials,image,pixel [/tags]
[short_descr] Depix is a tool for recovering passwords from pixelized screenshots. [/short_descr]
[image] https://github.com/beurtschipper/Depix/raw/main/docs/img/Recovering_prototype_latest.png [/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/220
