### ISSUE TITLE
[addtool] Ethiack

### ISSUE THREAD

**Issue by matosdfm** [gwen001/offsectools_www#1273]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]https://ethiack.com/[/link]
[tags]blackbox,ethical,automated,AI[/tags]
[short_descr]Preemptively attack your assets and identify vulnerabilities with Autonomous Ethical Hacking[/short_descr]
[image]https://ethiack.com/img/logo.svg[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
