### ISSUE TITLE
[addtool] qsreplace

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#128]
[link]https://github.com/tomnomnom/qsreplace[/link]
[short_descr] Accept URLs on stdin, replace all query string values with a user-supplied value [/short_descr]
[tags]fuzzing[/tags]
[long_descr]Accept URLs on stdin, replace all query string values with a user-supplied value, only output each combination of query string parameters once per host and path.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207495143-bc0c3246-7547-48e9-93f3-ed216ab01117.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/qsreplace

Thank you!
