### ISSUE TITLE
[addtool] Chameleon

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1281]
[link]
https://github.com/iustin24/chameleon
[/link]

[tags]
fingerprint, enumeration
[/tags]

[short_descr]
Chameleon provides better content discovery by using wappalyzer's set of technology fingerprints alongside custom wordlists tailored to each detected technologies.
[/short_descr]

[long_descr]
The tool is highly customizable and allows users to add in their own custom wordlists, extensions or fingerprints.

The full documentation is available on: https://youst.in/posts/context-aware-conent-discovery-with-chameleon/
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/551f40b9-4fe6-4b37-8bd4-563b7e533c29)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1219
