### ISSUE TITLE
[addtool] ScrapingKit

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1286]
[link]
https://github.com/LaresLLC/ScrapingKit
[/link]

[tags]
activedirectory
[/tags]

[short_descr]
Scraping Kit is made up of several tools for scraping services for keywords, useful for initial enumeration of Domain Controllers or if you have popped a user's desktop and their outlook client.
[/short_descr]

[long_descr]
Scraping Kit is made up of several tools for scraping services for keywords, useful for initial enumeration of Domain Controllers or if you have popped a user's desktop, their outlook client. Each component has a function currently supports scraping and emailing the contents to a designated email address for easy exfiltration.

The kit contains two tools currently with more to come in the coming months and more customisation options.
=> SharpScrapeKit
=> PSScrapeKit

What it is ? 
It helps identify files that contain specific keywords in both emails via the Outlook desk app, and the local domain controller via the Policies and Scripts directories within the SYSVOL folder of an Active Directory domain. It then provides information about the matches and can be used to hunt for potential words such as username and password present in those files.

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6c0002b4-a919-4917-9328-c7cfab39e90d)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
