### ISSUE TITLE
[addtool] CRTER

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1287]
[link]
https://github.com/Micro0x00/CRTER
[/link]

[tags]
domains, subdomains
[/tags]

[short_descr]
This script reads a text file containing domains, fetches the subdomains from crt.sh
[/short_descr]

[long_descr]
CRTER is a command-line tool for fetching subdomains using the CRT.SH certificate search engine. It allows you to provide a list of domain names or fully-qualified domain names (FQDNs) and retrieve the associated subdomains. The tool fetches the subdomains from CRT.SH and saves them to an output file.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ff734050-3845-40d0-be32-5d33374d1b51)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
