### ISSUE TITLE
[addtool] HALA

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1288]
[link]
https://github.com/whalebone7/Hala
[/link]

[tags]
xss, reflected-xss
[/tags]

[short_descr]
HALA offers a powerful capability that enables you to identify reflected parameters within the response, providing valuable assistance in your testing and hacking endeavors.
[/short_descr]

[long_descr]
This tool leverages the power of the waybackurls utility to fetch URLs associated with the target domain. It intelligently filters the fetched URLs using bash scripting techniques to avoid duplicates.

Next, Hala utilizes the httpx tool to determine if the obtained URLs are alive and accessible. This step ensures that only active paths are considered for further analysis, enhancing the efficiency of the process.

Once the live paths are identified, Hala proceeds to launch its parameter discovery mechanism. This comprehensive feature allows Hala to automatically search for and analyze various parameters present in the identified URLs.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/443b0422-9855-4de3-9258-c939c35c4853)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
