### ISSUE TITLE
[addtool] WhatMail

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1289]
[link]
https://github.com/z0m31en7/WhatMail
[/link]

[tags]
enumeration, osint, digital-forensics, investigation
[/tags]

[short_descr]
A command-line tool that analyzes the header of an email and provides detailed information about various fields.
[/short_descr]

[long_descr]
WhatMail is a command-line tool that analyzes the header of an email and provides detailed information about various fields. It extracts commonly recognized email header fields such as To From Subject Date Delivered-To as well as useful fields like Message-ID Return-Path Reply-To X-Headers MIME Version Content Type Received-SPF DKIM Signature Authentication-Results X-Mailer and DMARC Results.

This tool is useful for forensic analysis investigating email authenticity understanding email routing and gathering information about the email sender and recipient. The output is presented in a tabular format making it easy to read and analyze.

💻 Filters Supported:

[+]  Message-ID
[+]  Return-Path
[+]  Reply-To
[+]  X-Headers
[+]  MIME Version
[+]  Content Type
[+]  Received-SPF
[+]  DKIM Signature
[+]  Authentication Results
[+]  X-Mailer
[+]  DMARC Results
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/3901e228-2594-4e2d-91d3-72584e174a13)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e8869ae4-39ba-4c7b-bb30-097687b35664)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f184c595-5794-4830-a2a5-4e526cfe775c)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
