### ISSUE TITLE
[addtool] ParamSpider

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#129]
[link]https://github.com/devanshbatham/ParamSpider[/link]
[short_descr] Mining parameters from dark corners of Web Archives [/short_descr]
[tags]crawler,endpoints[/tags]
[long_descr]

    Finds parameters from web archives of the entered domain.

    Finds parameters from subdomains as well.

    Gives support to exclude urls with specific extensions.

    Saves the output result in a nice and clean manner.

    It mines the parameters from web archives (without interacting with the target host)
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207495307-434b5482-ad4b-46ce-ab7b-1e904cd19ce1.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
