### ISSUE TITLE
[addtool] AllForOne

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1290]
[link]
https://github.com/AggressiveUser/AllForOne
[/link]

[tags]
Nuclei, yaml
[/tags]

[short_descr]
AllForOne - Nuclei Template Collector
[/short_descr]

[long_descr]
🚀 This repository contains a Python script that allows bug bounty hunters and security researchers to collect all Nuclei YAML templates from various public repositories, helping to streamline the process of downloading multiple templates using just a single repository.

How it Works ⚙️
The script leverages the GitHub repositories which containing Nuclei Templates. It will clones them to your local machine, and extracts the templates, organizing them for easy access.

[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/dc19d175-5ec4-4d65-99fa-1f008c5c938e)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1264
