### ISSUE TITLE
[addtool] Depix

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1292]
[link]
https://github.com/beurtschipper/Depix
[/link]

[tags]
screenshot, enumeartion
[/tags]

[short_descr]
Recovers passwords from pixelized screenshots
[/short_descr]

[long_descr]
Depix is a tool for recovering passwords from pixelized screenshots.

This implementation works on pixelized images that were created with a linear box filter.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f0493e9c-180d-4a4b-965f-48c2315007d3)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/220
