### ISSUE TITLE
[addtool] EnumStrike

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1293]
[link]
https://github.com/DallasFR/EnumStrike
[/link]

[tags]
enumeration, domain
[/tags]

[short_descr]
Cobalt Strike Aggressor script to automate host and domain enumeration.
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f23428ae-1a96-4ccc-91f2-f70a7b869d3a)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
