### ISSUE TITLE
[addtool] ProcOpen-PHP-Webshell

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1295]
[link]
https://github.com/d4rkiZ/ProcOpen-PHP-Webshell
[/link]

[tags]
php, reverse-shell
[/tags]

[short_descr]
Experience the power of a PHP webshell designed to overcome the limitations of blacklisted system/exec functions.
[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/069afa3f-366f-4f2b-9436-86768c99fb06)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
