### ISSUE TITLE
[addtool] Damn Vulnerable Bank

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1297]
[link]
https://github.com/rewanthtammana/Damn-Vulnerable-Bank
[/link]

[tags]
resources, learn, train
[/tags]

[short_descr]
Damn Vulnerable Bank is designed to be an intentionally vulnerable android application. This provides an interface to assess your android application security hacking skills.
[/short_descr]

[long_descr]
Guide: https://rewanthtammana[.]com/damn-vulnerable-bank/

"Damn Vulnerable Bank" is designed to be an intentionally vulnerable android application.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a8ac6aaf-d686-468c-924b-e34ff5870895)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/damn-vulnerable-bank

Thank you for your contribution!
