### ISSUE TITLE
[addtool] RegStrike

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1303]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://... (required)[/link]
[link]another link: https://... (optional)[/link]
[link]another link: https://... (optional)[/link]
[tags]list of tags separated by comma: tag1,tag2,tag3... (required)[/tags]
[short_descr]short description of the tool (max:100) (required)[/short_descr]
[long_descr]a bigger description (optional, but nice to have)[/long_descr] 
[image]a link or an attached image (required)[/image]
[image]another link or an attached image (optional)[/image]
[image]another link or an attached image (optional)[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.
