### ISSUE TITLE
[addtool] Eyeballer

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1305]
[link]
https://github.com/BishopFox/eyeballer
[/link]

[tags]
scanner, screenshot
[/tags]

[short_descr]
Convolutional neural network for analyzing pentest screenshots
[/short_descr]

[long_descr]
Eyeballer is meant for large-scope network penetration tests where you need to find "interesting" targets from a huge set of web-based hosts. Go ahead and use your favorite screenshotting tool like normal (EyeWitness or GoWitness) and then run them through Eyeballer to tell you what's likely to contain vulnerabilities, and what isn't.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/731f9013-0c96-4a11-bfcb-4bd6ac71fa3f)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/218
