### ISSUE TITLE
[addtool] HackBrowserData

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1306]
[link]
https://github.com/moonD4rk/HackBrowserData
[/link]

[tags]
browser
[/tags]

[short_descr]
Decrypt passwords/cookies/history/bookmarks from the browser.
[/short_descr]

[long_descr]

HackBrowserData is a command-line tool for decrypting and exporting browser data ( passwords, history, cookies, bookmarks, credit cards, download records, localStorage and extension ) from the browser. It supports the most popular browsers on the market and runs on Windows, macOS and Linux.
[/long_descr] 

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e7aa9406-e85e-4c7f-8250-663c07e9f8ae)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hackbrowserdata

Thank you for your contribution!
