### ISSUE TITLE
[addtool] Synergy-httpx

### ISSUE THREAD

**Issue by t3l3machus** [gwen001/offsectools_www#1309]
[link] https://github.com/t3l3machus/Synergy-httpx [/link]
[link] https://www.youtube.com/watch?v=1l5UlG_R_Fc [/link]
[tags] redteam,payloads,rubber-ducky,attiny85,badusb [/tags]
[short_descr] Http(s) server designed to host resources dynamically or act as a receiver for POST data intercepts.[/short_descr]
[long_descr]  
A Python http(s) server designed to assist in red teaming activities such as receiving intercepted data via POST requests and serving content dynamically (e.g. payloads).

I find this tool handy when performing USB-based attacks during physical pentests (Rubber ducky / BadUSB / ATtiny85, etc). Check out the ATtiny85_templates folder for some handy .ino templates to load on your microcontrollers.  
[/long_descr] 
[image] https://user-images.githubusercontent.com/75489922/243343284-da99aaf9-b385-4f33-931e-db6a01dd16b1.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/synergy-httpx

Thank you for your contribution!
