### ISSUE TITLE
[addtool] OSINT-SPY

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1310]
[link]
https://github.com/SharadKumar97/OSINT-SPY
[/link]
[tags]
osint, email, domain, ip-address
[/tags]
[short_descr]
Performs OSINT scan on email/domain/ip_address/organization using OSINT-SPY. 
[/short_descr]
[long_descr]
It can be used by Data Miners, Infosec Researchers, Penetration Testers and cyber crime investigator in order to find deep information about their target. 

Overview of this tool:
=> Perform scan on IP Address / domain / email address / BTC(bitcoin) address / device
=> Find out latest bitcoin block information
=> List out all the ciphers supported by web servers.
=> SSL heart bleed scan
=> Analyze malware or malicous file remotely

[/long_descr] 
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ea560bba-14eb-4bc3-90a6-79f31c187b6f)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/osint-spy

Thank you for your contribution!
