### ISSUE TITLE
[addtool] NODESUB

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1311]
[link]
https://github.com/pikpikcu/nodesub
[/link]
[tags]
subdomain, domain
[/tags]
[short_descr]
Nodesub is a command-line tool for finding subdomains in bug bounty programs
[/short_descr]
[long_descr]
Features: 
[+] Perform subdomain enumeration using CIDR notation (Support input list).
[+] Perform subdomain enumeration using ASN (Support input list).
[+] Perform subdomain enumeration using a list of domains.

[/long_descr] 
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/28653da7-f1a1-4de7-8e8e-6b9c8595a64a)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
