### ISSUE TITLE
[addtool] AndroSet

### ISSUE THREAD

**Issue by Anof-cyber** [gwen001/offsectools_www#1317]
[homepage] https://github.com/Anof-cyber/Androset [/homepage]
[tags] android, burpsuite, utils [/tags]
[short_descr] Automated script to convert and push Burp Suite certificate in Android, and modify Android's IP table to redirect all traffic to Burp Suite. [/short_descr] 
[image] https://repository-images.githubusercontent.com/573752426/d8ae543c-2a14-4889-b39e-17c880ac4e2e [/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/androset

Thank you for your contribution!
