### ISSUE TITLE
[addtool] onedrive_user_enum

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1319]
[link]
https://github.com/nyxgeek/onedrive_user_enum
[/link]
[tags]
windows, microsoft, 365, onedrive, user, enumaeration
[/tags]
[short_descr]
Pentest tool to enumerate valid o365 users.
[/short_descr]
[long_descr]
Now featuring:
[+] Local Database (sqlite3)
[+] Auto-lookup of tenants (thanks @DrAzureAD and @thetechr0mancer)
[+] Read in file OR folder of files
[+] Append -- easily create 'jsmith1' 'jsmith2' sprays
[+] Skip-Tried (de-dupe) -- remove previously tried usernames
[+] Kill-After -- cancel a userlist if no usernames identified within 'x' attempts
[/long_descr] 
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/03dc1035-bdf7-4a7a-9ce7-8f5cd5778bcf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/onedrive_user_enum

Thank you for your contribution!
