### ISSUE TITLE
[addtool] IsmailScript

### ISSUE THREAD

**Issue by thearrival** [gwen001/offsectools_www#1324]
[link]https://github.com/thearrival/IsmailScript[/link]
[tags]scanner,information_gathering,python,dns,ip,http,subdomains,whois,websockets[/tags]
[short_descr]Fast and customizable information gathering to enable a penetration tester to save a time and performing a full Reconnaissance and Information Gathering on any Web Application Server (Whois information
server banners
Open Ports / servives running
DNS server infomation
DNS Zone Transfer
Scrapping all URLs of the website
Service version info (if applicable).[/short_descr]
[long_descr]IsmailScript is used to gather information about any webserver [/long_descr] 
[image][a link or an attached image (required)](https://user-images.githubusercontent.com/27915465/151691466-a70eb52e-229b-410c-93c0-fd0f9cb8652b.jpg)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
