### ISSUE TITLE
[addtool] cook

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#133]
[link]https://github.com/glitchedgitz/cook[/link]
[short_descr]An overpower wordlist generator, splitter, merger, finder, saver, create words permutation and combinations[/short_descr]
[tags]passwords,fuzzing[/tags]
[long_descr]An overpower wordlist generator, splitter, merger, finder, saver, create words permutation and combinations, apply different encoding/decoding and everything you need.

Frustration killer! & Customizable!
<b>Customizable</b>

Cook is highly customizable and it depends on cook-ingredients. Cook Ingredients consists YAML Collection of word-sets, extensions, funcitons to generate pattern and wordlists.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207517744-5005498c-cc4c-4840-8c5c-b7ed0b35d044.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/cook

Thank you!
