### ISSUE TITLE
[addtool] Subcriminalip

### ISSUE THREAD

**Issue by KamilDogo** [gwen001/offsectools_www#1331]
[link]https://github.com/KamilDogo/subcriminalip[/link]
[link]https://www.criminalip.io[/link]
[tags] subdomain, reconnaissance, dns, osint, ips [/tags] 
[short_descr]Subcriminal: Python tool using Criminal IP API to extract domain data efficiently.[/short_descr]
[long_descr]Subcriminal is a powerful Python 3 tool that utilizes the CriminalIP API to effortlessly discover subdomains, domains, organization names, and IP addresses associated with a specific domain. It offers a straightforward approach to identify and extract valuable information from the target domain. 
With Subcriminal, users from diverse security disciplines such as pentesters, bugbounty hunters, security researchers, OSINT practitioners, and red teamers can effectively and efficiently gather relevant data for their respective purposes.[/long_descr] 
[image]https://raw.githubusercontent.com/KamilDogo/subcriminalip/main/Subcriminalip.png[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by KamilDogo** [comment]
Hello Gwen, 
I have just inserted the link for the image. 
Hope all the guidelines are met now. 
Sincerely,
KamilDogo

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
