### ISSUE TITLE
[addtool] ClownSearcher

### ISSUE THREAD

**Issue by SexyClown** [gwen001/offsectools_www#1337]
[link][homepage of the tool: https://... (required)](https://github.com/SexyClown/ClownSearcher)[/link]
[link][another link: https://... (optional)](https://medium.com/@noorsyafzati/share-clownsearcher-bbab3a7bf02c)[/link]
[tags]scanner,domains(required)[/tags]
[short_descr]This tool is created to facilitate our dorking process, making it faster than manual dorking.[/short_descr]
[long_descr]The available feature:

Single dork
list dork

HOW TO INSTALL

download : https://www.mediafire.com/file/di2r52xkl5evwke/sexyclown.pyc/file

run in terminal :
-pip3 install google

-python3 sexyclown.pyc
[/long_descr] 
[image]![image](https://github.com/gwen001/offsectools_www/assets/52460802/f30a6882-f4b6-4c0d-bc09-c2cf4f299329)[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
