### ISSUE TITLE
[addtool] mksub

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#134]
[link]https://github.com/trickest/mksub[/link]
[short_descr] Generate tens of thousands of subdomain combinations in a matter of seconds [/short_descr]
[tags]subdomain[/tags]
[long_descr]Read a wordlist file and generate subdomain combinations for a given domain or list of domains. Input from the wordlist file is lowercased and only unique words are processed. Additionally, wordlist can be filtered using regex.

When you use mksub's -l parameter, it will generate all subdomain combinations up to the specified level, including all lower levels, using words from the wordlist. For instance, with -l 2, it will generate len(permutation_list)^2 + len(permutation_list) results, which is:

    30 combinations for a 5-word wordlist.
    10100 combinations for a 100-word wordlist.
    250500 combinations for a 500-word wordlist.[/long_descr]

![image](https://user-images.githubusercontent.com/32585833/207624238-a303b20c-93e9-4cb1-8f8c-f309c82be300.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
