### ISSUE TITLE
[addtool] Tool PwnDoc

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [gwen001/offsectools_www#1346]
[link] https://github.com/pwndoc/pwndoc [/link]
[link] https://pwndoc.github.io/pwndoc/#/ [/link]
[tags]list of tags separated by comma: resources,reports[/tags]
[short_descr]Web application (GUI) to automate report generation (as docx files) using the docxtemplater templating engine.[/short_descr]

[long_descr]
- Once you have the syntax down, can work with MS Word's inconsistent formatting rules, and have a template that you like to use, you can generate reports very quickly. Very little editing will need to be done within the docx file that is generated.
  - Very easy to use custom templates to include custom sections, tables, logos, etc... 
- This report generator is primarily written in JavaScript and is packaged as a docker file. So, the software and reports take up very little space. 
- This tool also allows for multiple people to work on the report at the same time as opposed to having reporters share a docx file via OneDrive or similar. This means that users will no longer have a 'locked file' issue when they want to contribute to the report. 
- Users can add their own reusable language (instead of having to copy/paste the same generic vulnerability definitions for each report). These generic statements can then be selected for use at a later time. 
- There is a built-in CVSS calculator. You can choose to have the vulnerabilities sorted by severity (CVSS score) in the generated report, if that is appropriate for the use case. 
- Evidence images can be copy/pasted.
  - Some other report generators require users to import images as files to then insert within the report. Some report generators do not allow images to be added thereby requiring users to add images in the generated docx file. Copy/pasting images can be a big time saver.[/long_descr]

[image]https://raw.githubusercontent.com/pwndoc/pwndoc/master/demos/shared_audit_demo.gif [/image]
[image]https://raw.githubusercontent.com/pwndoc/pwndoc/master/demos/audit_finding_demo.gif [/image]
[image]https://raw.githubusercontent.com/pwndoc/pwndoc/master/demos/create_and_update_finding.gif [/image]

Edit: I don't know how to fix the issues with the listed fields. I updated my initial comment, accidentally clicked on the 'close with comment' button (whoops), and reopened this issue. I hope that I didn't break anything. 

Also, I found a very similar project that may merit some attention (https://github.com/pwndoc-ng/pwndoc-ng). I just learned about this today. So, I am not entirely certain what the differences are between PwnDoc and PwnDoc-ng.

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `short_descr` not found
- `tags` not found
- `link` not found
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `link` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Did you check one of 1200 issues already handled ? This could give yo a pretty good idea of how to do it.

**Comment by BetaMaxHeadroom** [comment]
> Did you check one of 1200 issues already handled ? This could give yo a pretty good idea of how to do it.

Yup. I did. I just must not have paid enough attention.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pwndoc

Thank you for your contribution!
