### ISSUE TITLE
[addtool] CybersecQ Quizzes

### ISSUE THREAD

**Issue by andreasc1** [gwen001/offsectools_www#1348]
[link]homepage of the tool: https://www.cybersecq.com[/link]
[tags]list of tags separated by comma: testengine, quizzer, certifications, testknowledge[/tags]
[short_descr]short description of the tool (max:100): CybersecQ is a test engine for various cybersecurity certifications. It helps people test their knoweledge on various cybersecurity. Is community driven and people can also submit their own quesitons. [/short_descr]
[image]a link or an attached image (required): https://www.cybersecq.com/images/cybersecq_small_logo.png[/image]
[image]another link or an attached image (optional) 
![cybersecq_logo](https://github.com/gwen001/offsectools_www/assets/2643858/f89d8021-7bec-4ac5-85a2-98b0d8fec7f7)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cybersec-quizzes

Thank you for your contribution!
