### ISSUE TITLE
[addtool] Get - ACQ

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#135]
[link]https://github.com/HanibalAntePortas/get-acq[/link]
[short_descr] GET-ACQ is a python tool used to gather all companies acquired by a given company domain name. It is done by calling SecurityTrails API. [/short_descr]
[tags]subdomains[/tags]
[long_descr] GET-ACQ is a python tool used to gather all companies acquired by a given company domain name. It is done by calling SecurityTrails API. [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207625306-a3ff8187-9bf2-4321-bdaf-89514c524b33.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
