### ISSUE TITLE
[addtool] Rengine

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#136]
[link]https://github.com/yogeshojha/rengine[/link]
[short_descr]reNgine is an automated reconnaissance framework for web applications[/short_descr]
[tags]scanner[/tags]
[long_descr] reNgine is an automated reconnaissance framework for web applications with a focus on highly configurable streamlined recon process via Engines, recon data correlation and organization, continuous monitoring, backed by a database, and simple yet intuitive User Interface. reNgine makes it easy for penetration testers to gather reconnaissance with… [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207627719-8f17ae57-5a81-4e2c-81b6-6b19c2cbbcf9.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/rengine

Thank you!
