### ISSUE TITLE
[addtool] SMBAT

### ISSUE THREAD

**Issue by oldboy21** [gwen001/offsectools_www#1365]
[link]https://github.com/oldboy21/SMBAT [/link]
[tags]smb.secrets,discovery,enum,permission[/tags]
[short_descr]Find secrets in file and secret files among the SMB target shares. Also assess the rights on any file[/short_descr]
[long_descr]Tools enums the target (IP list, CIDR, UNCPaths, etc) to discover accessible SMB shares. Multithread enum the file and the content of the file to discover secrets. Secrets discovery is based on exact string patch and regular expression. Furthermore the tool can be used to assess the WRITE permission on the files among the shares.[/long_descr] 
![smbmap-logo](https://github.com/gwen001/offsectools_www/assets/87986485/9485e398-f4ef-4bec-9c78-d70f6164592d)

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/smbat

Thank you for your contribution!
