### ISSUE TITLE
[addtool] RustScan

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#137]
[link]https://github.com/RustScan/RustScan[/link]
[short_descr]The Modern Port Scanner[/short_descr]
[tags]network[/tags]
[long_descr]The Modern Port Scanner. Find ports quickly (3 seconds at its fastest). Run scripts through our scripting engine (Python, Lua, Shell supported).[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207628425-a05ea7bc-e034-49af-832a-ee4d95e0af44.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/rustscan

Thank you!
