### ISSUE TITLE
Server Error - Site Error/Outage - Expired Certificate

### ISSUE THREAD

**Issue by BetaMaxHeadroom** [gwen001/offsectools_www#1370]
Hi,

I hate to be annoying. I just wanted to let you know that the site (https://offsec.tools/) is unresponsive at the moment. 

My assumption is that this is likely from the certificate expiring earlier today:
## Chrome
![image](https://github.com/gwen001/offsectools_www/assets/29237899/67c6887d-5fbc-48de-9665-a2c1611f7f34)
## Firefox 
![image](https://github.com/gwen001/offsectools_www/assets/29237899/bfe59d79-fa03-4c65-8fba-061e37189355)

Having said that, I love that you set this up for everyone. I love the site.

**Comment by gwen001** [comment]
Yes certificate was expired. It's ok now, thank you.
