### ISSUE TITLE
[addtool] nmap

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#138]
[link]https://github.com/nmap/nmap[/link]
[short_descr] Nmap - the Network Mapper. Github mirror of official SVN repository. [/short_descr]
[tags]network[/tags]
[long_descr]Nmap is released under a custom license, which is based on (but not compatible with) GPLv2. The Nmap license allows free usage by end users, and we also offer a commercial license for companies that wish to redistribute Nmap technology with their products. See Nmap Copyright and Licensing for full details.

The latest version of this software as well as binary installers for Windows, macOS, and Linux (RPM) are available from Nmap.org

Full documentation is also available on the Nmap.org website.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207630535-b533a85e-8986-44f3-996b-0d62f95569a4.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/nmap

Thank you!
