### ISSUE TITLE
[addtool] xurlfind3r

### ISSUE THREAD

**Issue by enenumxela** [gwen001/offsectools_www#1385]
[link] https://github.com/hueristiq/xurlfind3r (required)[/link]
[tags] urls,endpoints,crawler (required)[/tags]
[short_descr] A CLI utility to find domain's known URLs from curated passive online sources. (required)[/short_descr]
[long_descr] A command-line interface (CLI) utility to find domain's known URLs from curated passive online sources. (optional, but nice to have)[/long_descr]
[image] https://github.com/gwen001/offsectools_www/assets/62714471/ebe2cff9-0535-4f2c-853c-2b7ca3da4bcc (required)[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/xurlfind3r

Thank you for your contribution!
