### ISSUE TITLE
[addtool] Cake Fuzzer

### ISSUE THREAD

**Issue by zigrin-team** [gwen001/offsectools_www#1386]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://zigrin.com/tools/cake-fuzzer/ (required)[/link]
[link]another link: https://github.com/Zigrin-Security/CakeFuzzer (optional)[/link]
[link]another link: https://... (optional)[/link]
[tags]list of tags separated by comma: cybersecurity, vulnerabilities, scanner, IAST, vulnerabilities scanner (required)[/tags]
[short_descr]short description of the tool (max:100) Security testing tool for CakePHP-based web applications (required)[/short_descr]
[long_descr]a bigger description (optional, but nice to have) Cake Fuzzer is a project designed to automate the continuous discovery of vulnerabilities in web applications developed using specific frameworks. Our approach minimizes false positives, ensuring reliable results. Currently, our focus is on supporting the Cake PHP framework, but soon, it will also be available to other web application frameworks.

Cake Fuzzer is based on the concept of Interactive Application Security Testing (IAST). Our approach achieves the following objectives:
- automated vulnerability discovery for CakePHP-based applications;
- elimination of application-specific knowledge or pre-configuration requirements;
- minimal or zero false positives in the results;
- a user-friendly scanner that requires only basic security knowledge. [/long_descr] 
[image]a link or an attached image 
![cake-fuzzer (1)](https://github.com/gwen001/offsectools_www/assets/119972359/a92218d5-37c9-4c87-bdeb-b33ba3943e73)
(required)[/image]
[image]another link or an attached image (optional)[/image]
[image]another link or an attached image (optional)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cake-fuzzer

Thank you for your contribution!
