### ISSUE TITLE
[addtool] HackBot

### ISSUE THREAD

**Issue by morpheuslord** [gwen001/offsectools_www#1388]
[link]homepage of the tool: https://github.com/morpheuslord/HackBot[/link]
[tags]ai,llm,llama2,cybersecurity,automation,chatbot[/tags]
[short_descr]AI-powered cybersecurity chatbot designed to provide helpful and accurate answers to your cybersecurity-related queries[/short_descr]
[long_descr]HackBot utilizes the powerful language model Meta-LLama2 through the "LlamaCpp" library. This allows HackBot to respond to your questions in a coherent and relevant manner. Please make sure to keep your queries in English and adhere to the guidelines provided to get the best results from HackBot.[/long_descr] 
[image]
![image](https://github.com/gwen001/offsectools_www/assets/70637311/9d973ab4-ccb5-4579-9992-86bbe0e591eb)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
