### ISSUE TITLE
[addtool] VHostScan

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#139]
[link]https://github.com/codingo/VHostScan[/link]
[short_descr]A virtual host scanner that performs reverse lookups, can be used with pivot tools[/short_descr]
[tags]network[/tags]
[long_descr] A virtual host scanner that performs reverse lookups, can be used with pivot tools, detect catch-all scenarios, work around wildcards, aliases and dynamic default pages. 
A virtual host scanner that can be used with pivot tools, detect catch-all scenarios, aliases and dynamic default pages. First presented at SecTalks BNE in September 2017 (slidedeck).[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207630681-9e99e0dc-cfd4-48d5-8b17-3362cae4af6b.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/vhostscan

Thank you!
