### ISSUE TITLE
[addtool] hash-cracker

### ISSUE THREAD

**Issue by crypt0rr** [gwen001/offsectools_www#1395]
[link]homepage of the tool: (https://github.com/sensepost/hash-cracker) [/link]
[link]another link: (https://github.com/sensepost/hash-cracker-apple-silicon) [/link]
[tags]list of tags separated by comma: hash-cracking,hashcat,passwordcracking, passwords[/tags]
[short_descr]short description of the tool (max:100) tool that helps you cracking hashes more efficiently with a lot of techniques and attack vectors embedded.[/short_descr]
[image]https://avatars.githubusercontent.com/u/1193973?s=200&v=4 [/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
