### ISSUE TITLE
[addtool] RsaCracker

### ISSUE THREAD

**Issue by skyf0l** [gwen001/offsectools_www#1396]
[link]https://github.com/skyf0l/RsaCracker[/link]
[link]https://crates.io/crates/rsacracker[/link]
[tags] all, cryptography, RSA [/tags]
[short_descr]Powerful RSA cracker for CTFs. Supports RSA, X509, OPENSSH in PEM and DER formats.[/short_descr]
[long_descr]Powerful RSA cracker for CTFs. Supports RSA, X509, OPENSSH in PEM and DER formats.

RsaCracker provides a simple interface to crack RSA keys and ciphers. With a collection of thousands of attacks, no key can survive against RsaCracker![/long_descr] 
![RsaCracker](https://github.com/gwen001/offsectools_www/assets/5347721/926b746a-16c5-415a-85c0-61bdeb9cbbf0)

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
