### ISSUE TITLE
[addtool] BackupKiller

### ISSUE THREAD

**Issue by Q0120S** [gwen001/offsectools_www#1398]
[link]https://github.com/Q0120S/BackupKiller[/link]
[tags]backup, file_and_directory_information_exposure, security, bugbounty[/tags]
[short_descr]BackupKiller is a comprehensive tool to generate list of urls based on the URLs to find backup, installation, etc files.[/short_descr]
[image]https://ibb.co/WngLkK6[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `short_descr` not found
- `tags` not found
- `link` not found
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `image` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/backupkiller

Thank you for your contribution!
