### ISSUE TITLE
[addtool] subzy

### ISSUE THREAD

**Issue by LukaSikic** [gwen001/offsectools_www#1399]
[link]homepage of the tool: https://github.com/PentestPad/subzy (required)[/link]
[tags]list of tags separated by comma: subdomain takeover, subzy (required)[/tags]
[short_descr] Subdomain takeover tool [/short_descr]
[image]https://camo.githubusercontent.com/7eb71cec29bb280302099c49aebed865f6035ec99baeb12ca61cf8c51f87bd21/68747470733a2f2f692e696d6775722e636f6d2f676742387a4b782e706e67[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/subzy

Thank you for your contribution!
