### ISSUE TITLE
[addtool] cloud_enum

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#140]
[link]https://github.com/codingo/cloud_enum[/link]
[short_descr] Multi-cloud OSINT tool. Enumerate public resources in AWS, Azure, and Google Cloud. [/short_descr]
[tags]cloud[/tags]
[long_descr]Multi-cloud OSINT tool. Enumerate public resources in AWS, Azure, and Google Cloud.

Currently enumerates the following:

Amazon Web Services:

    Open S3 Buckets
    Protected S3 Buckets

Microsoft Azure:

    Storage Accounts
    Open Blob Storage Containers
    Hosted Databases
    Virtual Machines
    Web Apps

Google Cloud Platform

    Open GCP Buckets
    Protected GCP Buckets
    Google App Engine sites

By "open" buckets/containers, I mean those that allow anonymous users to list contents. if you discover a protected bucket/container, it is still worth trying to brute force the contents with another tool.
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207630777-67f164fa-e903-423c-8f90-e0d43ce84a98.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/cloud_enum

Thank you!
