### ISSUE TITLE
[addtool] Tool fscan

### ISSUE THREAD

**Issue by kunpen** [gwen001/offsectools_www#1400]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/shadow1ng/fscan/blob/main/README_EN.md][/link]
[tags]list of tags separated by comma: fscan 1.8.2][/tags]
[short_descr]Kscan is an asset mapping tool [/short_descr]
[long_descr]Kscan is an asset mapping tool that can perform port scanning, TCP fingerprinting and banner capture for specified assets, and obtain as much port information as possible without sending more packets. It can perform automatic brute force cracking on scan results, and is the first open source RDP brute force cracking tool on the go platform.[/long_descr]
[image]https://github.com/shadow1ng/fscan/blob/main/image/1.png[/image]

**Comment by gwen001** [comment]
Problem occured with the following fields:
- `short_descr` not found
- `tags` not found
- `link` not found

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) or [use the template](https://github.com/gwen001/offsectools_www/issues/new/choose) created for that purpose.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/fscan

Thank you for your contribution!
