### ISSUE TITLE
[addtool] crlfuzz

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#142]
[link]https://github.com/dwisiswant0/crlfuzz[/link]
[short_descr] A fast tool to scan CRLF vulnerability written in Go [/short_descr]
[tags]fuzzing[/tags]
[long_descr]A fast tool to scan CRLF vulnerability written in Go[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207643272-42607cc8-dd2f-458c-97c5-bee265dfcef9.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/crlfuzz

Thank you!
