### ISSUE TITLE
[addtool] attackgen

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1427]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/mrwadams/attackgen (required)[/link]
[tags]list of tags separated by comma: AttackGen,Mitre Att&CK Framework (required)[/tags]
[short_descr] AttackGen is a cybersecurity incident response testing tool that leverages the power of large language models and the comprehensive MITRE ATT&CK framework. The tool generates tailored incident response scenarios based on user-selected threat actor groups and  (required)[/short_descr]
[image] https://github.com/mrwadams/attackgen/raw/main/images/screenshot.jpg (required) [/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1427
