### ISSUE TITLE
[addtool] waf-bypass

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1428]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/nemesida-waf/waf-bypass (required)[/link]
[tags]list of tags separated by comma: WAF,Bypass (required)[/tags]
[short_descr] WAF bypass Tool is an open source tool to analyze the security of any WAF for False Positives and False Negatives using predefined and customizable payloads. Check your WAF before an attacker does. WAF Bypass Tool is developed by Nemesida WAF team with the participation of community. (required)[/short_descr]
[image] https://user-images.githubusercontent.com/99513957/223762773-e7f875dc-671e-4c14-a9ae-9bb1c6258da2.png (required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/waf-bypass

Thank you for your contribution!
