### ISSUE TITLE
[addtool] PurpleOps

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1429]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/CyberCX-STA/PurpleOps (required)[/link]
[tags]list of tags separated by comma: PutpleOS, PurpleTeam, RedTeam, BlueTeam(required)[/tags]
[short_descr] An open-source self-hosted purple team management web application. (required)[/short_descr]
[image] https://github.com/CyberCX-STA/PurpleOps/raw/main/static/images/demo.gif (required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/purpleops

Thank you for your contribution!
