### ISSUE TITLE
[addtool] smap

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#143]
[link]https://github.com/s0md3v/Smap[/link]
[short_descr] a drop-in replacement for Nmap powered by shodan.io [/short_descr]
[tags]network[/tags]
[long_descr]passive Nmap like scanner built with shodan.io.
Smap is a port scanner built with shodan.io's free API. It takes same command line arguments as Nmap and produces the same output which makes it a drop-in replacament for Nmap.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207648788-143e3db8-6441-4dfa-a249-a723fbcc27c5.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/smap

Thank you!
