### ISSUE TITLE
[addtool] dot

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1430]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/sensity-ai/dot (required)[/link]
[tags]list of tags separated by comma: Deepfake,biometrics  (required)[/tags]
[short_descr] dot (aka Deepfake Offensive Toolkit) makes real-time, controllable deepfakes ready for virtual cameras injection. dot is created for performing penetration testing against e.g. identity verification and video conferencing systems, for the use by security analysts, Red Team members, and biometrics researchers. (required)[/short_descr]
[image] https://github.com/sensity-ai/dot/raw/main/assets/gui_dot_demo.gif (required)[/image]
[image] https://github.com/sensity-ai/dot/raw/main/assets/dot_run.gif (optional)[/image]
[image] https://github.com/sensity-ai/dot/raw/main/assets/dot_demo.gif(optional)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/dot

Thank you for your contribution!
