### ISSUE TITLE
[addtool] TEx

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1431]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/guibacellar/TEx (required)[/link]
[link]another link: https://telegramexplorer.readthedocs.io/en/latest/ (optional)[/link]
[link]another link: https://theobservator.net/threat-intel-tool-telegram-explorer/ (optional)[/link]
[tags]list of tags separated by comma: TEx,Telegram,Explorer,OSINT (required)[/tags]
[short_descr] TEx is a Telegram Explorer tool created to help Researchers, Investigators and Law Enforcement Agents to Collect and Process the Huge Amount of Data Generated from Criminal, Fraud, Security and Others Telegram Groups. (required)[/short_descr]
[image] https://telegramexplorer.readthedocs.io/en/latest/media/how_text_works.png (required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/tex

Thank you for your contribution!
