### ISSUE TITLE
[addtool] atop_maltego

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1432]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/aaarghhh/atop_maltego (required)[/link]
[tags]list of tags separated by comma: ATOP,Maltego,TON, DNS (required)[/tags]
[short_descr] A new Maltego transform useful to make investigations on TON assets like TON nickname, TON DNS and TON Telephone Number. These kinds of entities are NFT based on TON network. The transform is base on ATOP. (required)[/short_descr]
[image] https://user-images.githubusercontent.com/968839/218277566-6ba9d4bf-4d48-4b35-83e3-278e0dbd7263.png (required)[/image]
[image] https://user-images.githubusercontent.com/968839/218276997-a2f36ce8-706b-456e-bdfb-53fc6b518a82.png (optional)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
