### ISSUE TITLE
[addtool] a_TON_of_privacy

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1433]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/aaarghhh/a_TON_of_privacy (required)[/link]
[tags]list of tags separated by comma: TON,Privacy, OSINT (required)[/tags]
[short_descr] A TON of Privacy" formally called ATOP ... is a tool for conducting OSINT investigations on TON (Telegram) NFTs.(required)[/short_descr]
[image] https://camo.githubusercontent.com/a8585456dd382a598556cbc04fa1b3971c1ee39c08f9537db4d0791b25c71c5b/68747470733a2f2f6769746875622d70726f64756374696f6e2d757365722d61737365742d3632313064662e73332e616d617a6f6e6177732e636f6d2f3936383833392f3237313733313632362d373 (required)[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1433
