### ISSUE TITLE
[addtool] PersistenceSniper

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1434]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/last-byte/PersistenceSniper (required)[/link]
[tags]list of tags separated by comma: tag1,tag2,tag3... (required)[/tags]
[short_descr] PersistenceSniper is a Powershell module that can be used by Blue Teams, Incident Responders and System Administrators to hunt persistences implanted in Windows machines. (required)[/short_descr]
[image] https://camo.githubusercontent.com/f0f368ee5b88a055a76eaf211e8e78c1a61af1a67a9ed993b5f8a8f9bdd2fd14/68747470733a2f2f626c6f672e6e6f74736f2e70726f2f696d672f7073736e6970657276616c69646174657365742e676966 (required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/persistencesniper

Thank you for your contribution!
