### ISSUE TITLE
[addtool] RMS-Runtime-Mobile-Security

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1435]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security (required)[/link]
[tags]list of tags separated by comma: RMS,Runtime,Frida,Mobile (required)[/tags]
[short_descr] With RMS you can easily dump all loaded classes and relative methods, hook everything on the fly, trace methods args and return value, load custom scripts and many other useful stuff. (required)[/short_descr]
[image] https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security/raw/master/DEMO/Android/DEMO_3_Massive_Hook.gif(required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
