### ISSUE TITLE
[addtool] Inspeckage

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1436]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/ac-pm/Inspeckage (required)[/link]
[tags]list of tags separated by comma: Inspeckage,Mobile,Hooks,Frida (required)[/tags]
[short_descr] Inspeckage is a tool developed to offer dynamic analysis of Android applications. By applying hooks to functions of the Android API, Inspeckage will help you understand what an Android application is doing at runtime. (required)[/short_descr]
[image] https://camo.githubusercontent.com/d70134a19fcf43fcf3e275dbf417675398ed3783f4ba46de385c4cbc7dc51823/687474703a2f2f692e696d6775722e636f6d2f534768587230652e706e67 (required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/inspeckage

Thank you for your contribution!
