### ISSUE TITLE
[addtool] haktrails

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1437]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

[link]homepage of the tool: https://github.com/hakluke/haktrails (required)[/link]
[tags]list of tags separated by comma: haktrails,bugbounty,Security Trails (required)[/tags]
[short_descr] haktrails is a Golang client for querying SecurityTrails API data, sponsored by SecurityTrails. (required)[/short_descr]
[image] https://github.com/hakluke/haktrails/raw/main/haktrails.png (required)[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1130
