### ISSUE TITLE
[addtool] Arjun

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#144]
[link]https://github.com/s0md3v/Arjun[/link]
[short_descr] HTTP parameter discovery suite. [/short_descr]
[tags]endpoint,fuzzing[/tags]
[long_descr]Arjun can find query parameters for URL endpoints.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207649501-19c0eee0-8af0-41bb-9544-40d61238d7fe.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/arjun

Thank you!
