### ISSUE TITLE
[addtool] Burp-Encode-IP

### ISSUE THREAD

**Issue by gwen001** [gwen001/offsectools_www#1444]
[tags]burpsuite,encoding,ip,utils[/tags]
[short_descr]Burp Suite extension to encode an IP address focused to bypass application IP/domain blacklist.[/short_descr]
[link] https://github.com/e1abrador/Burp-Encode-IP [/link]
[long_descr]
This extension will encode an IP address into a bunch of less known encoding techniques.

This technique is focused on testing vulnerabilities such as SSRF [Server-Side Request Forgery], Open Redirect or RFI [Remote File Inclusion].
[/long_descr]
[image] https://raw.githubusercontent.com/gwen001/offsectools_www/main/tmp/ed728dd6b351784923c9611ccea5d1cb.png [/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/burp-encode-ip

Thank you for your contribution!

**Comment by e1abrador** [comment]
Good days,

Remember that in order to make an easier installation the tool is now available on BApp from BurpSuite ; )

![image](https://github.com/gwen001/offsectools_www/assets/74373745/5d36e911-64cf-4d9a-afea-7a5269341f4e)
