### ISSUE TITLE
[addtool] bxss.net

### ISSUE THREAD

**Issue by thistehneisen** [gwen001/offsectools_www#1448]
[link]homepage of the tool: https://bxss.net/ (required)[/link]
[link]another link: https://bxss.org/ (optional)[/link]
[link]another link: https://bxss.icu/ (optional)[/link]
[tags]bxss, xss, blind xss, cross-site scripting (required)[/tags]
[short_descr]BXSS is a web service that allows for detection Blind XSS vulnerabilities within web applications. (max:100) (required)[/short_descr]
[long_descr]BXSS is a web service that allows for detection Blind XSS vulnerabilities within web applications. The project has the aim of being a framework for both in educational purposes and ethical hacking (penetration testing) so that a researcher can be notified when a blind XSS vulnerability is executed. Understandably, the same payloads that are provided can be used to detect also regular and stored XSS.[/long_descr] 
[image]https://bxss.net/img/BXSS_logo.png (required)[/image]
[image]another link or an attached image (optional)[/image]
[image]another link or an attached image (optional)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/bxss.net

Thank you for your contribution!
