### ISSUE TITLE
[addtool] cve-collector

### ISSUE THREAD

**Issue by password123456** [gwen001/offsectools_www#1449]
[link] https://github.com/password123456/cve-collector [/link]
[tags] cve, cve-collector, latest-cve [/tags]
[short_descr] Simple Latest CVE Collector Written in Python [/short_descr]
[image] https://github.com/password123456/cve-collector/blob/main/preview.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cve-collector

Thank you for your contribution!
