### ISSUE TITLE
[addtool] gospider

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#145]
[link]https://github.com/jaeles-project/gospider[/link]
[short_descr]GoSpider - Fast web spider written in Go[/short_descr]
[tags]directories,endpoints[/tags]
[long_descr]
    <b>Features</b>
    Fast web crawling
    Brute force and parse sitemap.xml
    Parse robots.txt
    Generate and verify link from JavaScript files
    Link Finder
    Find AWS-S3 from response source
    Find subdomains from response source
    Get URLs from Wayback Machine, Common Crawl, Virus Total, Alien Vault
    Format output easy to Grep
    Support Burp input
    Crawl multiple sites in parallel
    Random mobile/web User-Agent
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207652210-3ac83814-c4af-4b7e-8e51-0dd88e67b2f1.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/gospider

Thank you!
