### ISSUE TITLE
[addtool] HasMySecretLeaked

### ISSUE THREAD

**Issue by ggjey** [gwen001/offsectools_www#1456]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

Put your data between the `[opening-tags]` and the `[/closing-tags]`.

Link to the tool: https://... (minimum 1 required):
[link]https://gitguardian.com/hasmysecretleaked[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]supply chain security, github, secrets, leak, credentials, scanner, development[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Search across 20 million exposed secrets in public GitHub repositories, gists, issues,and comment[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]HasMySecretLeaked is a project from GitGuardian that aims to help individual users and organizations verify if their developer secrets have leaked on public repositories, gists, and issues on GitHub projects.[/long_descr]

A link or an attached image (minimum 1 required):
[image]https://blog.gitguardian.com/content/images/2023/10/HMSL_1.png[/image]
[image]https://blog.gitguardian.com/content/images/2023/10/HMSL_2.png[/image]
[image]https://blog.gitguardian.com/content/images/2023/10/HMSL_3.png[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hasmysecretleaked

Thank you for your contribution!
