### ISSUE TITLE
[addtool] openbuckets.io

### ISSUE THREAD

**Issue by openbuckets-admin** [gwen001/offsectools_www#1466]
[link]homepage of the tool: https://openbuckets.io (required)[/link]
[tags]OpenBuckets, Cloud Storage, Open Bucket Search, Exposed Data Discovery (required)[/tags]
[short_descr]OpenBuckets is an online platform for finding open buckets in cloud storage systems effortlessly. (max:100) (required)[/short_descr]
[long_descr]OpenBuckets provides a robust platform to easily find open buckets in cloud storage with a quick search. Additionally, it facilitates targeted file type searches within these buckets, proving invaluable for security experts, researchers, and individuals keen on discovering exposed data. (required)[/long_descr]
[image]https://imageupload.io/ib/UdoAOw0yyQd4h9f_1698426073.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/openbuckets.io

Thank you for your contribution!
