### ISSUE TITLE
[addtool] dnstake

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#147]
[link]https://github.com/pwnesia/dnstake[/link]
[short_descr]A fast tool to check missing hosted DNS zones that can lead to subdomain takeover [/short_descr]
[tags]dns,subdomains[/tags]
[long_descr]DNS takeover vulnerabilities occur when a subdomain (subdomain.example.com) or domain has its authoritative nameserver set to a provider (e.g. AWS Route 53, Akamai, Microsoft Azure, etc.) but the hosted zone has been removed or deleted. Consequently, when making a request for DNS records the server responds with a SERVFAIL error. This allows an attacker to create the missing hosted zone on the service that was being used and thus control all DNS records for that (sub)domain.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207657970-484e7493-e05f-4a23-b51b-6dba19fd5149.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/dnstake

Thank you!
