### ISSUE TITLE
[addtool] PrivacyNet

### ISSUE THREAD

**Issue by HalilDeniz** [gwen001/offsectools_www#1477]
[tags]privacy,hidden,anonmous,tor[/tags]
[short_descr]PricacyNet: Privacy Network.[/short_descr]
[link]https://github.com/HalilDeniz/PrivacyNet[/link]
[long_descr]PrivacyNet is an anonymization tool that configures iptables and Tor to route all services, traffic and DNS through the Tor network. This tool allows users to route internet traffic through Tor and hide their real IP address.[/long_descr]
Features
- Installing and removing iptables rules
- Connecting to the Tor network to get its IP address and geolocate it
- Changing circuit with a new IP
- Automatic IP change at a specified interval
- Fast and easy to use
[image]https://github.com/HalilDeniz/PrivacyNet/raw/main/source/privacynet.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/privacynet

Thank you for your contribution!
