### ISSUE TITLE
[addtool] BounceBack

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#1478]
[homepage]https://github.com/D00Movenok/BounceBack [/homepage]
[tags]proxy,waf,redteam[/tags]
[short_descr]Stealth redirector for your red team operation security.[/short_descr]
[long_descr] BounceBack is a powerful, highly customizable and configurable reverse proxy with WAF functionality for hiding your C2/phishing/etc infrastructure from blue teams, sandboxes, scanners, etc. It uses real-time traffic analysis through various filters and their combinations to hide your tools from illegitimate visitors.[/long_descr] 
![image](https://github.com/D00Movenok/BounceBack/raw/main/assets/architecture.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/bounceback

Thank you for your contribution!
