### ISSUE TITLE
[addtool] dnsx

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#148]
[link]https://github.com/projectdiscovery/dnsx[/link]
[short_descr]A fast and multi-purpose DNS toolkit designed for running DNS queries[/short_descr]
[tags]dns,subdomains[/tags]
[long_descr] dnsx is a fast and multi-purpose DNS toolkit allow to run multiple DNS queries of your choice with a list of user-supplied resolvers. [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207764460-d68f8a81-b078-4ec7-9e04-f8e3ea83c19f.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/dnsx

Thank you!
