### ISSUE TITLE
[addtool] tlsx

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#149]
[link]https://github.com/projectdiscovery/tlsx[/link]
[short_descr] Fast and configurable TLS grabber focused on TLS based data collection.[/short_descr]
[tags]dns,subdomains[/tags]
[long_descr]A fast and configurable TLS grabber focused on TLS based data collection and analysis.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207764772-1b1945b4-b731-4c86-8470-580b22537566.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/tlsx

Thank you!
