### ISSUE TITLE
[addtool] xsubfind3r

### ISSUE THREAD

**Issue by enenumxela** [gwen001/offsectools_www#1497]
[link]https://github.com/hueristiq/xsubfind3r[/link]
[tags]subdomains[/tags]
[short_descr]xsubfind3r is a command-line interface (CLI) based passive subdomain discovery utility.[/short_descr]
[long_descr]xsubfind3r is a command-line interface (CLI) based passive subdomain discovery utility. It is designed to efficiently identify known subdomains of given domains by tapping into a multitude of curated online passive sources.[/long_descr]
[image]https://github.com/gwen001/offsectools_www/assets/62714471/b710935f-710f-4810-98fb-91cf91c97c7d[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
