### ISSUE TITLE
[addtool] asnmap

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#150]
[link]https://github.com/projectdiscovery/asnmap[/link]
[short_descr] Go CLI and Library for quickly mapping organization network ranges using ASN information. [/short_descr]
[tags]dns,ips[/tags]
[long_descr]
    **ASN to CIDR Lookup
    ORG to CIDR Lookup
    DNS to CIDR Lookup
    IP to CIDR Lookup
    ASN/DNS/IP/ORG input
    JSON/CSV/TEXT output
    STD IN/OUT support**
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207765135-87b62408-b720-40a1-96e0-5cdc8a697df2.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused, feel free to contact the team if you're not happy with that.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/asnmap

Thank you!
