### ISSUE TITLE
[addtool] SJ (Swagger Jacker)

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#1521]
[homepage] https://github.com/BishopFox/sj [/homepage]
[tags] api,swagger [/tags]
[short_descr] sj (Swagger Jacker)) is a command line tool designed to assist with auditing of exposed Swagger/OpenAPI definition files by checking the associated API endpoints for weak authentication. It also provides command templates for manual vulnerability testing..
It does this by parsing the definition file for paths, parameters, and accepted methods before using the results with one of three commands:

    automate - Crafts a series of requests and analyzes the status code of the response.
    prepare - Generates a list of commands to use for manual testing.
    endpoints - Generates a list of raw API routes. Path values will not be replaced with test data. 
[/short_descr]
![image](https://github.com/gwen001/offsectools_www/assets/32585833/3f2c5982-c489-4ac0-a994-c018ba28da9b)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/swagger-jacker

Thank you for your contribution!
