### ISSUE TITLE
[addtool] sudomy

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#153]
[link]https://github.com/screetsec/Sudomy[/link]
[short_descr]Subdomain Enumeration & Analysis[/short_descr]
[tags]subdomains,recon[/tags]
[long_descr] Sudomy is a subdomain enumeration tool to collect subdomains and analyzing domains performing automated reconnaissance (recon) for bug hunting / pentesting [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207768165-4f2f7a84-9788-44b4-9f41-0baf79412abe.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/sudomy

Thank you!
