### ISSUE TITLE
[addtool] MapperPlus

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#1536]
[homepage] https://github.com/midoxnet/mapperplus [/homepage]
[tags] javascript, sourcemapper, map [/tags]
[short_descr] An advanced source map extractor based on headless browser. [/short_descr]
 [long_descr] 
MapperPlus facilitates the validation and retrieval of all .js/.js.map files from a specified target or a list of targets. It subsequently employs SourceMapper to extract source code for all your designated targets.
MapperPlus utilizes a Chrome Headless browser to intercept every request and response, ensuring the download of JavaScript files goes beyond heuristic scans or regular expressions, and includes the handling of all requested JS files.
MapperPlus is based on an already existing tool called SourceMapper which helps you extract the source code from a single .map file. [/long_descr]
![image](https://github.com/gwen001/offsectools_www/assets/32585833/5c1bd2b3-d9fb-4055-8d71-75f903370fe5)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/mapperplus

Thank you for your contribution!
