### ISSUE TITLE
[addtool] Gowitness

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#154]
[link]https://github.com/sensepost/gowitness[/link]
[short_descr]gowitness- a golang, web screenshot utility using Chrome Headless [/short_descr]
[tags]network,scanner,screenshot[/tags]
[long_descr]gowitness is a website screenshot utility written in Golang, that uses Chrome Headless to generate screenshots of web interfaces using the command line, with a handy report viewer to process results. Both Linux and macOS is supported, with Windows support mostly working.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207771620-43686a2a-effe-44e7-ba61-20699616627a.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/gowitness

Thank you!
