### ISSUE TITLE
[addtool] dnsReaper

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#155]
[link]https://github.com/punk-security/dnsReaper[/link]
[short_descr]subdomain takeover tool for attackers, bug bounty hunters and the blue team! [/short_descr]
[tags]dns,subdomains[/tags]
[long_descr]DNS Reaper is yet another sub-domain takeover tool, but with an emphasis on accuracy, speed and the number of signatures in our arsenal!

We can scan around 50 subdomains per second, testing each one with over 50 takeover signatures. This means most organisations can scan their entire DNS estate in less than 10 seconds.

DNS Reaper detects a if domain has a broken cname record and can be taken over by registering the domain's cname[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207771909-d100a379-f799-4c93-ac99-ea3355fe4959.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/dnsreaper

Thank you!
