### ISSUE TITLE
[addtool] osintname

### ISSUE THREAD

**Issue by yuyudhn** [gwen001/offsectools_www#1553]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

Put your data between the `[opening-tags]` and the `[/closing-tags]`.

Link to the tool: https://... (minimum 1 required):
[link]https://github.com/yuyudhn/osintname[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]osint, osint-tools, username-generator[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Generate Emails and Usernames from Provided Lists of Names.[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]simple tool to generate a username list by permutating from a provided list of names. This tool will generate a list of usernames in the following formats: firstname.lastname, firstnamelastname, lastname.firstname, lastnamefirstname, lastname, firstname[/long_descr]

A link or an attached image (minimum 1 required):
[image]https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEidNjFPK8Ad7gCc_173oSnf-wiV8qBJzaK_9q_TTcIpqjblbjzBc-FHLtduzDk6uO25fkfZYfQCMwOIF2BHWTVn0eS0_5p3r8nVZ4hw04m27iOqtJh9ep0Lu60ATfp12q2xdxbICQthU55pei0qmMzdujxx-LIrtSHNG5asdCMOYexBhyphenhyphenOa8BkXliuZOteH/s1544[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/osintname

Thank you for your contribution!
