### ISSUE TITLE
[addtool] secret-magpie-cl

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#156]
[link]https://github.com/punk-security/secret-magpie-cli[/link]
[short_descr] Secret Magpie - Secret Detection Tool [/short_descr]
[tags]git,secrets[/tags]
[long_descr]SecretMagpie is a secret detection tool that hunts out all the secrets hiding in your GitHub repositories. It uses multiple tools in one convenient package to scan every branch of every repository in an organisation. It then smooshes all those results together into a lovely json output and reports some big ticket stats right to the screen.

By making use of the opensource tools Trufflehog pig and Gitleaks, SecretMagpie can highlight a variety of different secrets and ensure that nothing is missed![/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207772517-9aa642a1-553d-484b-8fab-d07c38c22986.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/secretmagpie

Thank you!
