### ISSUE TITLE
[addtool] DataExtractor

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#158]
[link]https://github.com/gwen001/DataExtractor[/link]
[short_descr]A Burp Suite extension to extract data from source code while browsing.[/short_descr]
[tags]burpsuite_extension,regex[/tags]
[long_descr]
<b>Features</b>
    in scope parsing
    file extensions to ignore
    files exclusion based on regexp
    multi tabs for multiple purpose
    data extraction based on regexp
    results exclusion based on regexp
    data export
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208080639-fa5d4122-d8bb-4922-9f88-f939b79b1927.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/dataextractor

Thank you!
