### ISSUE TITLE
[addtool] s3-xplode

### ISSUE THREAD

**Issue by halencarjunior** [gwen001/offsectools_www#1588]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/halencarjunior/s3-xplode[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]aws,s3,audit[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]S3-xplode is a script that will scan a public s3 bucket for secrets using Regex[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]S3-xplode is a script that will scan a public s3 bucket for secrets using Regex. So, what is the main difference between others: It will do everything "on the fly". No files are saved on the disk,and no third-party software.[/long_descr]

[image]https://i.imgur.com/yP8wzo4.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
