### ISSUE TITLE
[addtool] pphack

### ISSUE THREAD

**Issue by edoardottt** [gwen001/offsectools_www#1589]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

Put your data between the `[opening-tags]` and the `[/closing-tags]`.

Link to the tool: https://... (minimum 1 required):
[link]https://github.com/edoardottt/pphack[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]prototypepollution, prototype-pollution, frontend, websec[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]The Most Advanced Client-Side Prototype Pollution Scanner[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]pphack is a CLI tool for scanning websites for client-side prototype pollution vulnerabilities.[/long_descr]

A link or an attached image (minimum 1 required):
[image]https://pbs.twimg.com/card_img/1754175226395414528/T_B5Uccx?format=jpg&name=small[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pphack

Thank you for your contribution!
