### ISSUE TITLE
[addtool] Crawlergo

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#159]
[link]https://github.com/Qianlitp/crawlergo[/link]]
[short_descr] A powerful browser crawler for web vulnerability scanners [/short_descr]
[tags]scanner,scanner,fuzzer[/tags]
[long_descr]crawlergo is a browser crawler that uses chrome headless mode for URL collection. It hooks key positions of the whole web page with DOM rendering stage, automatically fills and submits forms, with intelligent JS event triggering, and collects as many entries exposed by the website as possible. The built-in URL de-duplication module filters out a large number of pseudo-static URLs, still maintains a fast parsing and crawling speed for large websites, and finally gets a high-quality collection of request results.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208144599-652493b9-d1d7-4c11-a65e-b02fd5b3b9e5.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/crawlergo

Thank you!

**Comment by gwen001** [comment]
Tool has been refused, feel free to contact the team if you're not happy with that.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/crawlergo

Thank you!

**Comment by gwen001** [comment]
Tool has been refused, feel free to contact the team if you're not happy with that.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/crawlergo

Thank you!
