### ISSUE TITLE
[addtool] The HTTP Garden

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#1603]
[homepage] https://github.com/narfindustries/http-garden [/homepage]
[tags] fuzzing, http, proxy [/tags]
[short_descr]  Differential testing and fuzzing of HTTP servers and proxies [/short_descr]
 [long_descr] 
The HTTP Garden is a collection of HTTP servers and proxies configured to be composable, along with scripts to interact with them in a way that makes finding vulnerabilities much much easier.
 [/long_descr]
![image](https://github.com/gwen001/offsectools_www/assets/32585833/d91b5814-9f09-4174-b074-cd6ac6862752)

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/the-http-garden

Thank you for your contribution!
