### ISSUE TITLE
[addtool] reconftw

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#161]
[link]https://github.com/six2dez/reconftw[/link]]
[short_descr]reconFTW is a tool designed to perform automated recon on a target domain[/short_descr]
[tags]scanner,vulnerabilities[/tags]
[long_descr]ReconFTW automates the entire process of reconnaissance for you. It outperforms the work of subdomain enumeration along with various vulnerability checks and obtaining maximum information about your target.

ReconFTW uses a lot of techniques (passive, bruteforce, permutations, certificate transparency, source code scraping, analytics, DNS records...) for subdomain enumeration which helps you to get the maximum and the most interesting subdomains so that you be ahead of the competition.

It also performs various vulnerability checks like XSS, Open Redirects, SSRF, CRLF, LFI, SQLi, SSL tests, SSTI, DNS zone transfers, and much more. Along with these, it performs OSINT techniques, directory fuzzing, dorking, ports scanning, screenshots, nuclei scan on your target.

So, what are you waiting for? Go! Go! Go![/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208145340-7c89a634-e31a-4ac5-b490-b24192383974.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/reconftw

Thank you!
