### ISSUE TITLE
[addtool] GSB

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#1615]
Before you fill all the informations here, please give a read at the guidelines:
https://github.com/gwen001/offsectools_www/issues/1

Put your data between the `[opening-tags]` and the `[/closing-tags]`.

Link to the tool: https://... (minimum 1 required):
[link]https://github.com/100security/gsb[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]gsb,google safe browsing,http code,safe,unsafe[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Google Safe Browsing is a tool developed by Google aimed at enhancing internet safety by identifying and alerting users about potentially dangerous websites.[/short_descr]

A bigger description (optional, but nice to have):
[long_descr][/long_descr]

A link or an attached image (minimum 1 required):
[image]https://www.100security.com.br/images/gsb-13.png[/image]
[image]https://www.100security.com.br/images/gsb-23.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
