### ISSUE TITLE
[addtool] cero

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#162]
[link]https://github.com/glebarez/cero[/link]
[short_descr] Scrape domain names from SSL certificates of arbitrary hosts [/short_descr]
[tags]subdomains,dns,[/tags]
[long_descr]Cero will connect to remote hosts, and read domain names from the certificates provided during TLS handshake.
It is not limited to only HTTPS, and will scrape certificates from any protocol that works over TLS (e.g. SMTPS) - just give it the right ports to connect to.
Cero allows flexible specification of targets, including domain names, IP addresses, and CIDR ranges, with full support for IPv6.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208252032-4d78ca08-81ff-4520-9e82-113ea9e427b4.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/cero

Thank you!
