### ISSUE TITLE
[addtool] cloudscraper

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#164]
[link]https://github.com/jordanpotti/cloudscraper[/link]
[short_descr]Tool to enumerate targets in search of cloud resources. S3 Buckets,Azure Blobs,Digital Ocean Storage Space[/short_descr]
[tags]cloud,aws,azure,gcp[/tags]
[long_descr]CloudScraper is a Tool to spider and scrape targets in search of cloud resources. Plug in a URL and it will spider and search the source of spidered pages for strings such as 's3.amazonaws.com', 'windows.net' and 'digitaloceanspaces'. AWS, Azure, Digital Ocean resources are currently supported.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208282492-269ebd75-f287-4fb3-802d-0892b225368b.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/cloudscraper

Thank you!
