### ISSUE TITLE
[addtool] NetInspect

### ISSUE THREAD

**Issue by secnextechnologies** [gwen001/offsectools_www#1643]
[tags] recon,status_code,cms,content_length [/tags]

[short_descr] Information gathering of IPs or domains [/short_descr]

[link] https://www.secnextech.com/ [/link]
[link] https://github.com/secnextechnologies/NetInspect [/link]

[long_descr] This script is designed to scan IPs or domains, providing detailed service information such as server details, HTTP status codes, and content length. It also performs CMS fingerprinting to identify common content management systems.

- Scan single IPs, domains, or entire subnets
- Multi-threaded scanning for efficient performance
- Support for HTTP and HTTPS services
- CMS fingerprinting for popular content management systems
[/long_descr]

A link or an attached image (minimum 1 required):
[image] https://github.com/secnextechnologies/NetInspect/blob/main/banner.png [/image]

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
