### ISSUE TITLE
[addtool] WinFiHack

### ISSUE THREAD

**Issue by morpheuslord** [gwen001/offsectools_www#1644]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/morpheuslord/WinFiHack [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows,wifi,network-security,network [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] This is an implementation of an old method which uses Windows native networking tools to do brute force. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] This is an implementation of an old method which uses Windows native networking tools to do brute force. This is an old and not-so-valid option to do wifi hacking but is a reminder and testament to old ways of hacking. [/long_descr]

A link or an attached image (minimum 1 required):
[image]https://github.com/gwen001/offsectools_www/assets/70637311/1bb09259-7709-4e8a-afb8-6366937ec7c0 [/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/winfihack

Thank you for your contribution!
