### ISSUE TITLE
[addtool] HARpwn

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1648]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/HCRitter/HARpwn [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] HTTP , windows, token, HAR [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] HARpwn - HARToken Extraction and Sanitization Module; HARpwn is a PowerShell module designed to streamline the extraction and sanitization of HARTokens from HTTP Archive (HAR) files. Simplify the process of retrieving valuable data and ensure your HAR files are safe and secure with HARpwn, where HARTokens meet 'pwnage' with a touch of humor. [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ebca75a7-0449-40af-ae38-01ca0d87d558)

[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/harpwn

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/harpwn

Thank you for your contribution!
