### ISSUE TITLE
[addtool] autoNTDS

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1649]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/hmaverickadams/autoNTDS [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] cracking, passwords, hashcat [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] autoNTDS is an automation script designed to simplify the process of dumping and cracking NTDS hashes using secretsdump.py and hashcat. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7877c9fc-fc4a-4d32-8c79-7b5840904cef)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
