### ISSUE TITLE
[addtool] CRLFMap

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#165]
[link]https://github.com/ryandamour/crlfmap[/link]
[short_descr] CRLFMap is a tool to find HTTP Splitting vulnerabilities [/short_descr]
[tags]vulnerabilities,fuzzing[/tags]
[long_descr]CRLFMap is a tool to find HTTP Splitting vulnerabilities[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208282529-44cecb74-6b8a-4652-aaf0-f8436927eb42.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/crlfmap

Thank you!
