### ISSUE TITLE
[addtool] brutas

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1651]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/tasooshi/brutas[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] wordlists [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] handcrafted Wordlists [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ccb92771-36f3-4c1a-8cb2-b188fea81b6a)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/brutas

Thank you for your contribution!
