### ISSUE TITLE
[addtool] pentesting-bootstrap

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1652]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/tasooshi/pentesting-bootstrap[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] vm, setup [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Fast and easy way of setting up a hardened pentesting environment with Kali Linux[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9a4deae6-9191-40e4-891d-817768430419)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
