### ISSUE TITLE
[addtool] some-tweak-to-hide-jwt-payload-values

### ISSUE THREAD

**Issue by password123456** [gwen001/offsectools_www#1653]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/password123456/some-tweak-to-hide-jwt-payload-values [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] jwt-payload-easy-obfuscation,jwt-token-encrypt,jwt-encryption,jwt-payload-encrypt-tweaks [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] a handful of tweaks and ideas to safeguard the JWT payload [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] a handful of tweaks and ideas to safeguard the JWT payload, making it futile to attempt decoding by constantly altering its value, ensuring the decoded output remains unintelligible while imposing minimal performance overhead. [/long_descr]

A link or an attached image (minimum 1 required):
[image] https://github.com/password123456/some-tweak-to-hide-jwt-payload-values/blob/main/run.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
