### ISSUE TITLE
[addtool] LocalPotato

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1657]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/decoder-it/LocalPotato [/link]
[link] https://decoder.cloud/2023/11/03/localpotato-http-edition/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Potato, windows, privesc [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] The LocalPotato attack is a type of NTLM reflection attack that targets local authentication. This attack allows for arbitrary file read/write and elevation of privilege. [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1df506f8-bdd9-45f2-99b9-d962abcc66ac)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/localpotato

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/localpotato

Thank you for your contribution!
