### ISSUE TITLE
[addtool] findom-xss

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#166]
[link]https://github.com/dwisiswant0/findom-xss[/link]
[short_descr] A fast DOM based XSS vulnerability scanner with simplicity. [/short_descr]
[tags]fuzzing,vulnerabilities[/tags]
[long_descr]FinDOM-XSS is a tool that allows you to finding for possible and/ potential DOM based XSS vulnerability in a fast manner.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208282602-d2ac78a3-4c9e-4527-add5-583f6544d5ec.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/findom-xss

Thank you!
