### ISSUE TITLE
[addtool] Honeypots-Detection

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1660]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/UnaPibaGeek/honeypots-detection [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] honeypots, scanner, Nuclei [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Nuclei templates for honeypots detection. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] This repository contains Nuclei templates to detect several well-known open-source honeypots, such as: ADBHoney, Conpot, Cowrie, Dionaea (multiple services), ElasticPot, Mailoney, Redis Honeypot, Snare, among others. [/long_descr]

A link or an attached image (minimum 1 required):
[image]  
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f5ceb8ae-a10c-4a2d-8817-fa397a146485)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
