### ISSUE TITLE
[addtool] Mosint

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1661]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/alpkeskin/mosint [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] email, osint[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]An automated e-mail OSINT tool[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]Mosint is an automated email osint tool written in Go that allows you investigate for target emails in a fast and efficient manner. It consolidates numerous services, enabling security researchers to swiftly access a wealth of information.[/long_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7bf385ea-e044-4f6e-9fc3-cec8c9aebd51)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/5d70bae3-5806-4288-a57b-20f20b5d6551)
[/image]

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/mosint

Thank you for your contribution!
