### ISSUE TITLE
[addtool] ShodanX

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1663]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/sanjai-AK47/ShodanX [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] shodan [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]ShodanX is a tool to gather information of targets using shodan dorks⚡.[/short_descr]

A bigger description (optional, but nice to have):
[long_descr]Shodanx ⚡ is a great tool and its uses the shodan facet data then extracts results for given targets by user and ShodanX is fully upto users queries. By making a super queries and use good facets queries to get more results about your targets, users can use different modes with proper shodan facets for queries to get lot of information about your target.[/long_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4239be3c-ee8b-4da4-9e5b-8b1ad62f5bbf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
