### ISSUE TITLE
[addtool] CrossLinked

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1664]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/m8sec/CrossLinked [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] linkedin,enumeration [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]CrossLinked is a LinkedIn enumeration tool that uses search engine scraping to collect valid employee names from an organization. This technique provides accurate results without the use of API keys, credentials, or accessing LinkedIn directly!/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/add2cc4d-74b5-46e1-9193-365f21b5aa98)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/70b5dee2-461e-4d20-868b-c1176c543aa1)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1342
