### ISSUE TITLE
[addtool] badgerDAPS

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1665]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/johnjhacking/badgerDAPS[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags]windows, LDAP, enumeration [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Brute Ratel LDAP filtering and sorting tool. Easily take BR log output and pull hostnames for ease of use with other red team tooling. Supports OU filtering and removes disabled hosts.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/72e3b251-85ab-45a7-b978-29f793675698)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
