### ISSUE TITLE
[addtool] Dome

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1669]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/v4d1/Dome [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] subdomain, enumeration [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Subdomain Enumeration Tool. Fast and reliable python script that makes active and/or passive scan to obtain subdomains and search for open ports. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/40c9c56e-3315-40bc-88c4-a898846df60b)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a34bafd1-6f59-4126-ba90-9be2d6e8a93a)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/834
