### ISSUE TITLE
[addtool] http-request-smuggling

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#167]
[link]https://github.com/anshumanpattnaik/http-request-smuggling[/link]
[short_descr] HTTP Request Smuggling Detection Tool[/short_descr]
[tags]fuzzing,vulnerabilities[/tags]
[long_descr]HTTP request smuggling is a high severity vulnerability which is a technique where an attacker smuggles an ambiguous HTTP request to bypass security controls and gain unauthorized access to performs malicious activities, the vulnerability was discovered back in 2005 by [watchfire](https://www.cgisecurity.com/lib/HTTP-Request-Smuggling.pdf) and later in August 2019 it re-discovered by [James Kettle - (albinowax)](https://twitter.com/albinowax) and presented at [DEF CON 27](https://www.youtube.com/watch?v=w-eJM2Pc0KI) and [Black-Hat USA](https://www.youtube.com/watch?v=_A04msdplXs), to know more about this vulnerability you can refer his well-documented research blogs at [Portswigger website](https://portswigger.net/research/http-desync-attacks-request-smuggling-reborn). So the idea behind this security tool is to detect HRS vulnerability for a given host and the detection happens based on the time delay technique with the given permutes, so to know more about this tool I'll highly encourage you to read my [blog](https://hackbotone.com/blog/http-request-smuggling-detection-tool) post about this tool.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208282854-3a59aa1b-0d8c-40a1-9192-bd3111e8de69.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/http-request-smuggling

Thank you!
