### ISSUE TITLE
[addtool] Arsenal

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1670]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/Orange-Cyberdefense/arsenal [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] terminal, commands, 
[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Arsenal is just a quick inventory, reminder and launcher for pentest commands.
This project written by pentesters for pentesters simplify the use of all the hard-to-remember commands [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/071e1226-1f18-4bd9-9dfe-3be07a0f4a1c)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/arsenal

Thank you for your contribution!
