### ISSUE TITLE
[addtool] LEAKEY

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1671]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/rohsec/LEAKEY [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] credentials, leakedcreds
[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] LEAKEY is a bash script which checks and validates for leaked credentials. The idea behind LEAKEY is to make it highly customizable and easy to add checks for new services. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] LEAKEY is a tool is for validation of leaked API tokens/keys found during pentesting and Red Team Enegagments.
The script is really useful for Bug Hunters inorder to validate and determine the impact of leaked credentials.

LEAKEY uses a json based signature file located at ~/.leakey/signatures.json
The idea behind LEAKEY is to make it highly customizable and easy to add new services/checks once they are discovered.
[/long_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f3b85c62-32cc-4ff3-be92-59485bfa3d01)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/04def637-c4a3-4573-95a0-21be6c62fb99)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/leakey

Thank you for your contribution!
