### ISSUE TITLE
[addtool] MetaDetective

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1673]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/franckferman/MetaDetective [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] metadata [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Unleash Metadata Intelligence with MetaDetective. Bridging the chasm in metadata extraction and analysis. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4a54ec94-1921-4df4-9ff6-f647a41ddfa5)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1ecfc94c-0f7d-492e-9977-63990cb28f16)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/metadetective

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/metadetective

Thank you for your contribution!
