### ISSUE TITLE
[addtool] urlhunter

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1678]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/utkusen/urlhunter [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] bitly, goo.gl
[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] urlhunter is a recon tool that allows searching on URLs that are exposed via shortener services such as bit.ly and goo.gl. The project is written in Go.
[/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1ffb6b78-fcdb-44fc-a39d-36a9ad610896)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/urlhunter

Thank you for your contribution!
