### ISSUE TITLE
[addtool] GPPDeception

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1679]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/RedSiege/GPPDeception [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] usercreaction, groups,xml
[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] This script generates a groups.xml file that mimics a real GPP to create a new user on domain-joined computers 
 [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/c8c79142-07b8-4f44-b8e0-5526bdf5dd76)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
