### ISSUE TITLE
[addtool] NtlmThief

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1680]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/MzHmO/NtlmThief [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] NTLM, NetNTLM, hash
[/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Extracting NetNTLM without touching lsass.exe [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] This is a C++ implementation of the Internal Monologue attack. It allows to get NetNTLM hashes of users using SSPI. [/long_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/068d0962-b906-4f43-80c6-28c90ed6ce25)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
