### ISSUE TITLE
[addtool] van-gonography

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1681]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/JoshuaKasa/van-gonography [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] steganography [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Hide any type of files inside a image of your choice [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6aeb37bb-04f5-4638-afde-9e414f99f986)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4cda8e8f-ada7-4984-b3f9-656a4c5f5f51)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
