### ISSUE TITLE
[addtool] RunWithDll

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1682]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/TimMisiak/RunWithDll [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] dll, windows, DLLinjection [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A utility that can be used to launch an executable with a DLL injected. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/8e6c6dca-b7b7-4721-bbee-b39551c7cc91)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
