### ISSUE TITLE
[addtool] ADHunt 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1684]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/asmtlab/ADHunt[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD, windows, enumeration [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A tool for enumerating Active Directory Enviroments looking for interesting AD objects, vulnerabilities, and misconfigurations. It currently uses a combination ldap queries and available tooling. It was built as a follow up to LinWinPwn. [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/3e113a78-fa7a-4120-bbbd-1935a2660967)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
