### ISSUE TITLE
[addtool] Unshackle

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1685]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/Fadi002/unshackle[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] usb, windows, linux, password [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Open-source tool to bypass windows and linux passwords from bootable usb[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6b5dab30-8203-43ae-af09-5e651ca64b70)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/unshackle

Thank you for your contribution!
