### ISSUE TITLE
[addtool] Web Check

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1686]
Link to the tool: https://... (minimum 1 required):
[link]https://web-check.xyz/[/link]
[link]https://web-check.xyz/about#api-documentation[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] OSINT [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]All-in-one OSINT tool for analysing any website[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1716a880-cd35-4303-b745-b7c71157624c)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/web-check

Thank you for your contribution!
