### ISSUE TITLE
[addtool] PowerTools

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1687]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/gustanini/PowerTools[/link]
[link][/link]
[link][/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] powershell, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Powershell tools used for Red Team / Pentesting. As of Nov 23 2023 all tools are unified into a script named PowerTools for ease of use.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/3c54f0e6-65a7-4abe-913a-60abea5e0f43)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
