### ISSUE TITLE
[addtool] kxss

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#169]
[link]https://github.com/Emoe/kxss[/link]
[short_descr] This a adaption of tomnomnom's kxss tool with a different output format [/short_descr]
[tags]fuzzing,vulnerabilities[/tags]
[long_descr]This a adaption of tomnomnom's kxss tool with a different output format. I didn't want to fork his whole Hacks-Repository so created my Own ;-)
All Credit for this Code goes to [Tomnomnom](https://github.com/tomnomnom/)[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208283115-20328b7a-0eee-43cb-9c48-677dcc40beb0.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/kxss

Thank you!
