### ISSUE TITLE
[addtool] DomainTrail

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1695]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/gatete/DomainTrail[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] subdomain [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]DomainTrail is a fast subdomain enumeration tool that uses effective passive and active techniques.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2587588c-beb5-49e0-9b54-a2a7c01ccb7b)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
