### ISSUE TITLE
[addtool] SessionProbe 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1696]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/dub-flow/sessionprobe[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] session, webapp, privilege [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]SessionProbe is a multi-threaded tool designed for penetration testing and bug bounty hunting. It evaluates user privileges in web applications by taking a session token and checking access across a list of URLs, highlighting potential authorization issues.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7d07421a-4cb8-49d4-bf43-8d1c707e2109)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/sessionprobe

Thank you for your contribution!
