### ISSUE TITLE
[addtool] ScrapedIn

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1697]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/dchrastil/ScrapedIn[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] LinkedIn [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A tool to scrape LinkedIn without API restrictions for data reconnaissance[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/54c9d952-f288-413f-9a23-72ad9fc5b458)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4fb59d04-6b81-4a67-bb2b-072375861b57)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/scrapedin

Thank you for your contribution!
