### ISSUE TITLE
[addtool] VectorKernel

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1698]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/daem0nc0re/VectorKernel[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] rootkits, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]PoCs for Kernelmode rootkit techniques research or education. Currently focusing on Windows OS. All modules support 64bit OS only.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e7276dda-ac71-40bf-8b48-ae895c55bcdf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
