### ISSUE TITLE
[addtool] OpenRedireX

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#170]
[link]https://github.com/devanshbatham/OpenRedireX[/link]
[short_descr] A Fuzzer for OpenRedirect issues.[/short_descr]
[tags]fuzzing,vulnerabilities[/tags]
[long_descr]OpenRedireX : Asynchronous Open redirect Fuzzer for Humans[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208283163-4d5147a0-0e40-4865-a905-9cbb37188ef4.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/openredirex

Thank you!
