### ISSUE TITLE
[addtool] Gel4y Mini Shell Backdoor

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1700]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/22XploiterCrew-Team/Gel4y-Mini-Shell-Backdoor[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] shell, backdoor [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A webshell that can bypass some system security, all code has been obfuscated to bypass malware scans freely.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9eb4bd7b-8902-47ac-8d04-27bb7d8e964e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
