### ISSUE TITLE
[addtool] SharpTokenFinder

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1701]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/HuskyHacks/SharpTokenFinder[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] microsoft365, token [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]C# implementation of TokenFinder. Steal M365 access tokens from Office Desktop apps[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/541bbdc1-0e2b-40f4-913a-ea48e623a4d5)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
