### ISSUE TITLE
[addtool] Invoke-DHCPCheckup

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1702]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/akamai/Invoke-DHCPCheckup[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] powershell, windows, AD [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Invoke-DHCPCheckup is a tool meant to identify risky DHCP and DNS configurations in Active Directory environments.  [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/65b4dc4f-aebb-4fb7-8329-5f13f916c46e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
