### ISSUE TITLE
[addtool] godap

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1704]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/Macmod/godap[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] LDAP [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A complete TUI for LDAP.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/476ca66f-3eac-4ac5-b7ae-be52da20ba57)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/godap

Thank you for your contribution!
