### ISSUE TITLE
[addtool] Goosle

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1706]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/adegans/Goosle[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] searchengine [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A Meta Search engine with privacy and ease of use in mind[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9fd0d3a3-4bf0-4dce-951c-5921a2d58bbe)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
