### ISSUE TITLE
[addtool] Adcshunter

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1708]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/danti1988/adcshunter[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Uses rpcdump to locate the ADCS server, and identify if ESC8 is vulnerable from unauthenticated perspective.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/fa7118cd-bbae-4c28-98dc-42e27d99bcef)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
