### ISSUE TITLE
[addtool] RustHound

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1709]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/NH-RED-TEAM/RustHound[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Rust, AD, BloodHound [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Active Directory data collector for BloodHound written in Rust. 🦀[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/118626cd-155a-4ef1-820d-71bcebe66344)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1441
