### ISSUE TITLE
[addtool] Juumla

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1710]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/oppsec/juumla[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] joomla [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A python tool created to identify Joomla version, scan for vulnerabilities and sensitive files.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/5ff11e73-2f0b-4fd8-9380-b59961cb790d)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/juumla

Thank you for your contribution!
