### ISSUE TITLE
[addtool] TInjA

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1712]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/Hackmanit/TInjA[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] template-injection [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]TInjA is a CLI tool for testing web pages for template injection vulnerabilities.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/324b09fc-410a-446a-abbc-a13f0d38cac7)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/tinja

Thank you for your contribution!
