### ISSUE TITLE
[addtool] DeepSecrets 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1716]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/ntoskernel/deepsecrets[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] secret [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]A better tool for secret scanning.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/d9f5cb28-9266-48d9-8eb4-138eeac97fa1)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/deepsecrets

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/deepsecrets

Thank you for your contribution!
