### ISSUE TITLE
[addtool] uro

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#172]
[link]https://github.com/s0md3v/uro[/link]
[short_descr] declutters url lists for crawling/pentesting [/short_descr]
[tags]endpoints[/tags]
[long_descr]Using a URL list for security testing can be painful as there are a lot of URLs that have uninteresting/duplicate content; uro aims to solve that.

It doesn't make any http requests to the URLs and removes:

    human written content e.g. blog posts
    urls with same path but parameter value difference
    incremental urls e.g. /cat/1/ and /cat/2/
    image, js, css and other static files
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208372665-396f7ee3-c262-4e5b-b6c9-466a4f1b9e67.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/uro

Thank you!
