### ISSUE TITLE
[addtool] secbutler

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1721]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/groundsec/secbutler[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] CTF, Misc [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] The perfect butler for pentesters, bug-bounty hunters and security researchers. [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/61fd803a-bd8a-4102-b7ba-c1af495161b4)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9724f66e-5e56-4cb2-805b-df9498cd4762)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/secbutler

Thank you for your contribution!
