### ISSUE TITLE
[addtool] Artillery

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1722]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/hackerhouse-opensource/Artillery[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, system32, UAC [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]CIA UAC bypass implementation that utilizes elevated COM object to write to System32 and an auto-elevated process to execute as administrator.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/dc6f84a7-e7ae-45d0-900e-1d362520d6de)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
