### ISSUE TITLE
[addtool] Stinger

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1726]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/hackerhouse-opensource/Stinger[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] UAC [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]CIA UAC bypass implementation of Stinger that obtains the token from an auto-elevated process, modifies it, and reuses it to execute as Administrator.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b8f1bc47-b963-4ad4-970a-6436554287a9)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
