### ISSUE TITLE
[addtool] GTFONow

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1727]
Link to the tool: https://... (minimum 1 required):
[link]https://github.com/Frissi0n/GTFONow[/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] GTFO [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Automatic privilege escalation for misconfigured capabilities, sudo and suid binaries using GTFOBins.[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a60e7af6-a05d-4158-8c4e-4ef6c993e507)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/92ff571e-e12e-4e1d-9932-9d5b780adfa4)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/gtfonow

Thank you for your contribution!
