### ISSUE TITLE
[addtool] fuzzagotchi

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#173]
[link]https://github.com/hideckies/fuzzagotchi[/link]
[short_descr] A fuzzing tool written in Go. It helps your pentesting journey. [/short_descr]
[tags]fuzzing,endpoints[/tags]
[long_descr]A fuzzing tool written in Go. It helps to discover directories, files, parameters, etc. in web applications.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208372955-4a828507-b30b-4ae8-a03b-8d44a053f6a8.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/fuzzagotchi

Thank you!
