### ISSUE TITLE
[addtool] gron

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#174]
[link]https://github.com/tomnomnom/gron[/link]
[short_descr] Make JSON greppable! [/short_descr]
[tags]endpoints[/tags]
[long_descr]gron transforms JSON into discrete assignments to make it easier to grep for what you want and see the absolute 'path' to it. It eases the exploration of APIs that return large blobs of JSON but have terrible documentation.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208373301-475d55d7-9184-4541-a53f-428d39c7f9e0.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused, feel free to contact the team if you're not happy with that.

Thank you!
