### ISSUE TITLE
[addtool] SOAPHound 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1740]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/FalconForceTeam/SOAPHound [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD, windows, enumeration, Bloodhound [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] SOAPHound is a custom-developed .NET data collector tool which can be used to enumerate Active Directory environments via the Active Directory Web Services (ADWS) protocol. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4256c51d-a189-4e7f-a6a3-d26212d7d50d)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6e2b3a9b-0a59-48db-81ac-f899b96d7bdc)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/soaphound

Thank you for your contribution!
