### ISSUE TITLE
[addtool] Certify

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1741]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/GhostPack/Certify [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD, certificate [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Active Directory certificate abuse. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/60f2fab8-c735-4c21-9e1c-0955cbc8fdfd)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/certify

Thank you for your contribution!
