### ISSUE TITLE
[addtool] Automated Multi UAC bypass

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1742]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] UAC-Bypass, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Automated os version selector to run UAC based on OS versions. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/52fb7333-5b45-4d50-9825-f96d5c984981)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
