### ISSUE TITLE
[addtool] CVEMap

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1744]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/projectdiscovery/cvemap [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] CVE [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Navigate the Common Vulnerabilities and Exposures (CVE) jungle with ease using CVEMAP, a command-line interface (CLI) tool designed to provide a structured and easily navigable interface to various vulnerability databases. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/192e88bd-3bbd-481d-801c-8df9bfdac024)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2ed28c86-b8bd-4f99-9f40-e0c156b563bb)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cvemap

Thank you for your contribution!
