### ISSUE TITLE
[addtool] CLZero

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1745]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/Moopinger/CLZero [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Request-Smuggling, web [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A project for fuzzing HTTP/1.1 CL.0 Request Smuggling Attack Vectors [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/dd6b70e2-111d-4541-8b0d-4e78382ed779)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b281dc44-2c77-4646-b7ef-dd202fdd4722)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1498
