### ISSUE TITLE
[addtool] SQLi_Sleeps

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1746]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/HernanRodriguez1/SQLi_Sleeps [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] SQli, sql-injection, web [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] It is a simple script that allows to find SQLi vulnerabilities, obtaining the response time greater than 20 seconds per medium and time-based injection. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/476edee9-4f94-4982-aadd-99841c360acb)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/17c698e6-04a2-4802-8b33-f52f7295b1d3)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e57fc909-3661-4994-b98b-35ecc1c1534a)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
