### ISSUE TITLE
[addtool] SmuggleFuzz

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1747]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/Moopinger/smugglefuzz [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] smuggler [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] HTTP/2 based downgrade and smuggle scanner [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b342b439-485b-435a-93c5-ccc704c2b919)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/72054d1f-97ff-47c0-ab7e-8739b4295ecc)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/smugglefuzz

Thank you for your contribution!
