### ISSUE TITLE
[addtool] OSX Password Dumper Script

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1749]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/JeanPeyreMesMots/osx-password-dumper [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] MACOS, OSX, password, credentials [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A bash script to retrieve user's .plist files on a macOS system and to convert the data inside it to a crackable hash format. (to use with John The Ripper or Hashcat) [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/397654f7-4a87-42ac-bdbc-17f98931bf0b)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f5af9a14-ea6f-4f01-bf4b-3e1e07a83ab8)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/osx-password-dumper

Thank you for your contribution!
