### ISSUE TITLE
[addtool] mx-takeover

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#175]
[link]https://github.com/musana/mx-takeover[/link]
[short_descr] mx-takeover focuses DNS MX records and detects misconfigured MX records.[/short_descr]
[tags]vulnerabilities,subdomains[/tags]
[long_descr]mx-takeover focuses DNS MX records and detects misconfigured MX records. It currently support three technique. These are,

    MX domains that will expire soon
    Unregistered MX domains
    Domains that points to not currently in use by mailgun.
[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/208381290-33aab775-72d2-4321-a937-6c31167e7fe6.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/mx-takeover

Thank you!
