### ISSUE TITLE
[addtool] PacketSpy

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1750]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/HalilDeniz/PacketSpy [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Packet, network-traffic [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] PacketSpy is a powerful network packet sniffing tool designed to capture and analyze network traffic. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/c6daf485-1b36-4458-9985-4e0a2a55f05f)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/5cf7657a-f515-49cb-b2ba-ecfa9202079b)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
