### ISSUE TITLE
[addtool] NetProbe

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1751]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/HalilDeniz/NetProbe [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] network, prober [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] a tool you can use to scan for devices on your network [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] NetProbe is a tool you can use to scan for devices on your network. The program sends ARP requests to any IP address on your network and lists the IP addresses, MAC addresses, manufacturers, and device models of the responding devices. [/long_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4cda460d-d187-4b55-802e-9837f66ef3c3)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/8563ed77-ebba-4e71-a037-7cdebbd692bf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/netprobe

Thank you for your contribution!
