### ISSUE TITLE
[addtool] pphack

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1753]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/edoardottt/pphack [/link]
[link] https://edoardottt.github.io/pp-test/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] prototype-pollution [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] The Most Advanced Client-Side Prototype Pollution Scanner [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/01c27ea9-48f2-4a8c-98d0-df03ef9ad731)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1589
