### ISSUE TITLE
[addtool] Coerced potato

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1758]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/hackvens/CoercedPotato [/link]
[link] https://blog.hackvens.fr/articles/CoercedPotato.html [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, potato, privesc [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] New tool for local privilege escalation on a Windows machine, from a service account to NT SYSTEM. Should work on any recent versions of Windows. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/15f82c40-72d9-4783-a7fe-176b6e1d3b95)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/712ba949-9d55-4409-8bf5-74ea4cfa8c6d)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/coerced-potato

Thank you for your contribution!
