### ISSUE TITLE
[addtool] Pop

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1761]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/charmbracelet/pop [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] email, misc, timesaving [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Send emails from your terminal 📬 [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b40ee3d0-2e79-43c2-a462-de7063cd6753)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2c4d2498-7e62-49bf-a756-f61808c9b9b4)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pop

Thank you for your contribution!
