### ISSUE TITLE
[addtool] OS-Downloads

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1762]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/mrrobot1o1/OS-Downloads [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Download, OS  [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Links Of Windows/Linux/OFFICE ISOs Files using official Links. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/57621ba7-0ecc-4775-88f0-c8fa46182fb7)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
