### ISSUE TITLE
[addtool] wezterm

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1763]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/wez/wezterm [/link]
[link] [wezfurlong.org/wezterm/](https://wezfurlong.org/wezterm/) [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] terminal-emulator [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A GPU-accelerated cross-platform terminal emulator and multiplexer written by @wez and implemented in Rust.  [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2b9b4f45-3025-48bd-b9d5-0dce706dfdfe)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
