### ISSUE TITLE
[addtool] Superman

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1764]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/b1-team/superman [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, process-killer [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]🤖 Kill The Protected Process 🤖 [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ecc44436-b6b9-4003-917a-4b49c31188f0)
[/image]
[image]
![demo](https://github.com/gwen001/offsectools_www/assets/98208035/03641ffe-1d1b-4243-9733-e263affa008d)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
