### ISSUE TITLE
[addtool] huntkit

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1765]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/mcnamee/huntkit [/link]
[link] https://hub.docker.com/r/mcnamee/huntkit [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] tools, wordlists [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Docker - Ubuntu with a bunch of PenTesting tools and wordlists [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/179647fa-eb56-4167-a753-b0414b5af5e9)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/67e91234-180a-4aa5-b055-39de65c329bf)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
