### ISSUE TITLE
[addtool] spoofcheck

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1766]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/BishopFox/spoofcheck [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] email, spoof [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Simple script that checks a domain for email protection. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] A program that checks if a domain can be spoofed from. The program checks SPF and DMARC records for weak configurations that allow spoofing.

Additionally it will alert if the domain has DMARC configuration that sends mail or HTTP requests on failed SPF/DKIM emails. 
 [/long_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e94c1300-29f8-4c17-9269-4693c9b0d9da)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/spoofcheck

Thank you for your contribution!
