### ISSUE TITLE
[addtool] Chimera

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1767]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/tokyoneon/Chimera [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] powershell, obfuscation  [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Chimera is a PowerShell obfuscation script designed to bypass AMSI and commercial antivirus solutions. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/006cb929-30e0-428a-bc01-c1c907881d29)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/chimera

Thank you for your contribution!
