### ISSUE TITLE
[addtool] ligolo-ng

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1770]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/nicocha30/ligolo-ng [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] tunneling [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] An advanced, yet simple, tunneling/pivoting tool that uses a TUN interface. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2bb14b4b-c344-47ec-9279-1e1f4126870e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ligolo-ng

Thank you for your contribution!
