### ISSUE TITLE
[addtool] Linux-smart-enumeration

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1771]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/diego-treitos/linux-smart-enumeration [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] linux, privesc [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Linux enumeration tool for pentesting and CTFs with verbosity levels [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/3724f401-e1c7-4f61-a8ec-e831ba19dd9b)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/linux-smart-enumeration

Thank you for your contribution!
