### ISSUE TITLE
[addtool] Eviltree

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1774]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/t3l3machus/eviltree [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] privesc, credentails, linux [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A python3 remake of the classic "tree" command with the additional feature of searching for user provided keywords/regex in files, highlighting those that contain matches. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/d160caf3-096f-4d05-a5e4-b2c112717854)
[/image]
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/974cf2ee-306f-42d4-b06b-d30693701f78)
[/image]

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
