### ISSUE TITLE
[addtool] Seatbelt

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1775]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/GhostPack/Seatbelt [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, linux, enumeration, privesc [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Seatbelt is a C# project that performs a number of security oriented host-survey "safety checks" relevant from both offensive and defensive security perspectives. [/short_descr]

A link or an attached image (minimum 1 required):
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1caf5882-0536-4f91-bc7b-c5c5f0d9361b)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/seatbelt

Thank you for your contribution!
