### ISSUE TITLE
[addtool] Keres

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1778]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/ELMERIKH/Keres [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] powershell, presistance, backdoor, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Keres a is Powershell rev-shell backdoor with persistence for windows and linux (pwsh) [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4d23d329-9e19-4603-a0b7-74d6e163f914)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ebbe9437-5955-4f1a-b96d-ec7f8303d248)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1711
