### ISSUE TITLE
[addtool] Netscout

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1780]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/caio-ishikawa/netscout [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] OSINT [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] OSINT tool that finds domains, subdomains, directories, endpoints and files for a given seed URL. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e3b6b0cc-2209-463d-a30d-9b2a656101cd)
[/image]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2522462f-a63f-4dd8-a416-02e771fa6dd4)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
