### ISSUE TITLE
[addtool] CyberXS

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1781]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/thecybertix/CyberXS [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] XSS, Bug-Bounty [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] CyberXS is an XSS Vulnerability Automation Tool made with multiple Oneliners. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f14adefc-749f-4652-8b93-3014442af858)
[/image]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/0bd5f814-cc69-4348-bc2d-8ddfcd825e85)
[/image]

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
