### ISSUE TITLE
[addtool] ADExplorer

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1783]
Link to the tool: https://... (minimum 1 required):
[link]  https://live.sysinternals.com/ [/link]
Link to the tool: https://... (minimum 1 required):
[link]  https://live.sysinternals.com/ADExplorer.exe [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Active Directory Explorer. Display Active Directory tree in a Finder-like column view. [/short_descr]

A bigger description (optional, but nice to have):
[long_descr]
Execution
============
1. Copy it to the system
2. Download / run it from `https://live.sysinternals.com/ADExplorer.exe`
3. Load it into memory from Microsoft's site via UNC path: Type \\live.sysinternals.com\Tools\ADExplorer.exe within the Run box or Explorer!

[/long_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a5973991-4914-4f5a-9927-0177de1d0a73)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
