### ISSUE TITLE
[addtool] ADFind

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1784]
Link to the tool: https://... (minimum 1 required):
[link]  https://www.joeware.net/freetools/tools/adfind/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] SeekOut Valuable AD Information [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9ded9d8a-a3e9-4fe8-883b-029157fbd82e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
