### ISSUE TITLE
[addtool] Powermad

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1785]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/Kevin-Robertson/Powermad [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Powershell, AD [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Go Mad With PowerShell - Conquer AD With Ease! [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/90bc91ff-d5eb-43d5-993b-bf1ed77f219f)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/powermad

Thank you for your contribution!
