### ISSUE TITLE
[addtool] Kekeo

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1787]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/gentilkiwi/kekeo [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD, Kerberos [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A little toolbox to play with Microsoft Kerberos in C [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a10e097f-b0b5-4d12-a248-f845d6a20ba8)
[/image]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/495ee208-00a4-4ce4-b259-92ea9bdc6aca)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/kekeo

Thank you for your contribution!
