### ISSUE TITLE
[addtool] Invoke-ACLPwn

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1788]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/fox-it/Invoke-ACLPwn [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AD, ACLs [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A tool that automates the discovery and pwnage of ACLs in Active Directory that are unsafe configured. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b1be69ae-39d9-4f80-a3ee-2ccdeb5bea66)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/invoke-aclpwn

Thank you for your contribution!
