### ISSUE TITLE
[addtool] Rubeus

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1789]
Link to the tool: https://... (minimum 1 required):                   
[link]  https://github.com/GhostPack/Rubeus [/link]                   
                                                                      
List of tags separated by comma: tag1,tag2,tag3... (required):        
[tags] kerberos, AD, windows [/tags]                                  
                                                                      
Short description of the tool (required, maximum 100 characters):     
[short_descr] Trying to tame the three-headed dog. [/short_descr]     
                                                                      
[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b54e0b36-27f1-487d-aef2-9ac4bdc04e3b)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/619
