### ISSUE TITLE
[addtool] uro

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1792]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/s0md3v/uro [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] declutter, web [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] declutters url lists for crawling/pentesting [/short_descr]

A bigger description (optional, but nice to have):
[long_descr] Using a URL list for security testing can be painful as there are a lot of URLs that have uninteresting/duplicate content; uro aims to solve that. [/long_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/62be3e65-5d3c-46b9-a21c-b4c5d4e6a298)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/172
