### ISSUE TITLE
[addtool] Genzai 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1795]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/umair9747/Genzai [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] iot [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] The IoT security toolkit to help identify IoT related dashboards and scan them for default passwords and vulnerabilities. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a4583b40-1477-4c82-9ada-c36a2b8259d2)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f702b7df-6d87-4676-8fa0-0dd3e8d6a58e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/genzai

Thank you for your contribution!
