### ISSUE TITLE
[addtool] hashcracker

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1796]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/BLACKHATSGODBOLTE/hashcracker [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] password-cracker, cracker [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A POWERFULL BRUTEFORCING TOOL TO BRUTE FORCE THE ALGORITHM WHICH IS SEEN IN PRANKX SIMULATOR [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/62ad43bb-0be7-4975-ad5a-2e6456960b19)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
