### ISSUE TITLE
[addtool] Sentinel

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1800]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/6abd/sentinel [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] digital-forensics, forensics [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] an all-in-one encompassing tool for investigations assistance, from API leveraging to compiling data too [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4a4ab8a2-8518-4da4-961e-fb943792cabe)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/58698be2-46d9-414f-8e9a-09a1df3a1135)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
