### ISSUE TITLE
[addtool] Damn-Vulnerable-RESTaurant-API-Game

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1801]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/theowni/Damn-Vulnerable-RESTaurant-API-Game [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] resources [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Damn Vulnerable Restaurant is an intentionally vulnerable Web API game for learning and training purposes dedicated to developers, ethical hackers and security engineers. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/d406bbe5-0aad-4fc3-80b8-04d1c16089ea)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/damn-vulnerable-restaurant

Thank you for your contribution!
