### ISSUE TITLE
[addtool] LetMeowIn

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1802]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/Meowmycks/LetMeowIn [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, lsass [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A sophisticated, covert Windows-based credential dumper using C++ and MASM x64. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/85984341-e809-44f2-b3dc-4021e6f84c34)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1f531756-da6b-43c0-99b6-3784876f5fe3)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
