### ISSUE TITLE
[addtool] KExecDD

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1803]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/floesen/KExecDD [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] kernal, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Admin to Kernel code execution using the KSecDD driver [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/d242ade6-24a2-43b8-a7bb-77cb5449feb1)
[/image]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a07e4078-0dd8-4dc9-bc84-899f8ed5851f)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
