### ISSUE TITLE
[addtool] Subprober 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1804]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/sanjai-AK47/Subprober [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] subdomains, probing [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A Fast Multi-Purpose Http Probing Tool for Penetration Testing [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ca7182f4-f387-4fbf-8452-c446444dc7d5)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/86b30c2b-8181-4907-8db1-ba8701aba313)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
