### ISSUE TITLE
[addtool] NoArgs

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1809]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/oh-az/NoArgs?tab=readme-ov-file [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, process-hiding [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Manipulating and Hiding Process Arguments [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/632b45ff-4e83-425b-be51-316dad9c9f12)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
