### ISSUE TITLE
[addtool] HackerToolkit

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1811]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/ChrisJr404/HackerToolkit [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] tools, hacking [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] HackerToolkit offers a curated selection of tools designed to enhance your hacking capabilities. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/268e464b-164c-49c2-bc8a-0f19cf9ddf29)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
