### ISSUE TITLE
[addtool] check_mdi

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1812]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/expl0itabl3/check_mdi [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Microsoft-365 [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Python script to enumerate valid Microsoft 365 domains, retrieve tenant name, and check for an MDI instance.

 [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/6764c0e0-3f55-4fb4-89b0-8ff3f37ac419)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
