### ISSUE TITLE
[addtool] jsluice

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1813]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/BishopFox/jsluice [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] js, secrets [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Extract URLs, paths, secrets, and other interesting bits from JavaScript [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/f85a3bd9-97d4-44fa-93ec-43785ae48e57)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1405
