### ISSUE TITLE
[addtool] CloudRecon

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1814]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/g0ldencybersec/CloudRecon [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] subdomains [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Finding assets and subdomains from certificates! Scan the web! [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/cf564cdf-e921-4b96-ba70-14193d1c8384)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cloudrecon

Thank you for your contribution!
