### ISSUE TITLE
[addtool] Cookie-Editor

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1815]
Link to the tool: https://... (minimum 1 required):
[link]  https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Browser-Extensions [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Efficiently create, edit and delete a cookie for the current tab. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/73dfdb3c-5256-4566-b217-cc2f4645e31c)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
