### ISSUE TITLE
[addtool] Open Multiple URLs

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1818]
Link to the tool: https://... (minimum 1 required):
[link]  https://addons.mozilla.org/en-US/firefox/addon/open-multiple-urls/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Browser-Extensions [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Opens a list of URLs at once [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a96bf5f3-e4ac-4965-b1f6-cc9f4ab3f79d)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
