### ISSUE TITLE
[addtool] PwnFox

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1819]
Link to the tool: https://... (minimum 1 required):                                                         
[link]  https://addons.mozilla.org/en-US/firefox/addon/pwnfox/ [/link]                                      
                                                                                                            
List of tags separated by comma: tag1,tag2,tag3... (required):                                              
[tags] Browser-Extensions [/tags]                                                                           
                                                                                                            
Short description of the tool (required, maximum 100 characters):                                           
[short_descr] a Firefox/Burp extension that provide usefull tools for your security audit. [/short_descr]   
                                                                                                            
[image]   
![image](https://github.com/gwen001/offsectools_www/assets/98208035/b9a9f3db-69d1-446e-b751-a1c78cee8924)
                                                                                                 
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/731
