### ISSUE TITLE
[addtool] WhatRuns

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1820]
Link to the tool: https://... (minimum 1 required):
[link]  https://addons.mozilla.org/en-US/firefox/addon/whatruns/ [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Browser-Extensions [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Discover what runs a website [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7cf66618-a044-43b3-a743-4ec4e2aa1ce7)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/whatruns

Thank you for your contribution!
