### ISSUE TITLE
[addtool] ASPJinjaObfuscator

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1821]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/fin3ss3g0d/ASPJinjaObfuscator [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] asp-obfuscator, obfuscator [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Heavily obfuscated ASP web shell generation tool. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/29089b18-6e5e-440d-89bc-9b738f82cb73)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
