### ISSUE TITLE
[addtool] OWASP OFFAT

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1822]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/OWASP/OFFAT [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] rest-api [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] The OWASP OFFAT tool autonomously assesses your API for prevalent vulnerabilities, though full compatibility with OAS v3 is pending. The project remains a work in progress, continuously evolving towards completion [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/9a6151bb-96ac-471e-a35f-2391ee9ffd6f)
[/image]
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/4edb463a-adb3-4986-8152-f1c29c5dce5f)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/offat

Thank you for your contribution!
