### ISSUE TITLE
[addtool] Ominis OSINT

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1823]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/AnonCatalyst/Ominis-Osint [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] OSINT, reconnasance [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] This Python script is an #OSINT tool. It performs online information gathering by querying Google for search results related to a user-inputted query. The tool extracts relevant information such as titles, URLs, and potential mentions of the query in the results. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/10dea24d-8867-4f87-b33a-2c2de679a3d0)
[/image]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/99ab5c2a-ccbe-4161-b89d-353fd23b65f2)

[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ominis-osint

Thank you for your contribution!
