### ISSUE TITLE
[addtool] WinDefenderKiller

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1824]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/S12cybersecurity/WinDefenderKiller [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] windows, defender , difender-killer [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Windows Defender Killer | C++ Code Disabling Permanently Windows Defender using Registry Keys[/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/2e592111-312f-4fa1-9254-c8f44a777227)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
