### ISSUE TITLE
[addtool] AutoAppDomainHijack

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1825]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/nbaertsch/AutoAppDomainHijack [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] AppDomain-hijack, .net, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Automated .NET AppDomain hijack payload generation [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/7e4570ce-f5f7-43bf-86fa-8887586b1639)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
