### ISSUE TITLE
[addtool] Google Recaptcha Solver

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1826]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/sarperavci/GoogleRecaptchaBypass [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] reCAPTCHA [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Solve Google reCAPTCHA in less than 5 seconds! 🚀 [/short_descr]

A link or an attached image (minimum 1 required):
[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/a13fd9bc-0d81-4566-bc87-bf8207631bf7)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/google-recaptcha-solver

Thank you for your contribution!
