### ISSUE TITLE
[addtool] creepyCrawler

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1827]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/chm0dx/creepyCrawler [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] OSINT, crawler, recon [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] OSINT tool to crawl a site and extract useful recon info. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/8fc0ad2c-d808-43f1-bea0-b4334e93a983)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/creepycrawler

Thank you for your contribution!
