### ISSUE TITLE
[addtool] Dropper

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1828]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/SaadAhla/dropper [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Office-macro [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] Project that generates Malicious Office Macro Enabled Dropper for DLL SideLoading and Embed it in Lnk file to bypass MOTW  [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/ea1286e2-e9de-4ca5-9ed6-61babba6c367)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
