### ISSUE TITLE
[addtool] NucleiScanner 

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1830]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/0xKayala/NucleiScanner [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] Vulnerabilities, Scanner, Nuclei [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] NucleiScanner = Nuclei + Subfinder + Gau + Paramspider + httpx [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/d347b684-a142-4666-94ed-1705b8ad735e)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
