### ISSUE TITLE
[addtool] wlgen

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1831]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/ztgrace/wlgen [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] wordlist-generator [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr]Script to automate building wordlists for AppSec directory/resource bruting.[/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/229accc2-59e9-41ce-bd9f-21f772aae219)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wlgen

Thank you for your contribution!
