### ISSUE TITLE
[addtool] changeme

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1832]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/ztgrace/changeme [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] default-credential [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] A default credential scanner. [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/97c519ce-ca4e-4d3a-a448-f1bc8ac586b4)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/351
