### ISSUE TITLE
[addtool] go-secdump

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1833]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/jfjallid/go-secdump [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] SAM, registry, secret-dump, windows [/tags]

Short description of the tool (required, maximum 100 characters):
[short_descr] a tool built to remotely extract hashes from the SAM registry hive as well as LSA secrets and cached hashes from the SECURITY hive without any remote agent and without touching disk. [/short_descr]

[image] 
![image](https://github.com/gwen001/offsectools_www/assets/98208035/e9192af6-5e67-4ddd-a8ca-3895b85b3059)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/go-secdump

Thank you for your contribution!
