### ISSUE TITLE
[addtool] Web-Check

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#1849]
Link to the tool: https://... (minimum 1 required):
[link]  https://github.com/Lissy93/web-check [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] web, osint, scanner, enumeration [/tags]

Short description of the tool (required):
[short_descr] �️‍♂️ All-in-one OSINT tool for analysing any website [/short_descr]

[image]
![image](https://github.com/gwen001/offsectools_www/assets/98208035/1aa4f169-9398-45cd-b83b-a38f4489f624)
[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/1686
