### ISSUE TITLE
[addtool] UPEESCESS 

### ISSUE THREAD

**Issue by volksec** [gwen001/offsectools_www#1933]
Link to the tool: https://... (minimum 1 required):
[link] https://github.com/volksec/UPEESCESS [/link]

List of tags separated by comma: tag1,tag2,tag3... (required):
[tags] wp, wordpress, enum, pentest, redteam [/tags]

Short description of the tool (required):
[short_descr] Enumerate WordPress users by leveraging the /author/ endpoint. [/short_descr]

![image](https://github.com/user-attachments/assets/85057614-9e7a-40f3-b6cb-b8344f77a1b6)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
