### ISSUE TITLE
[addtool] GAP

### ISSUE THREAD

**Issue by xnl-h4ck3r** [gwen001/offsectools_www#213]
[short_descr]A Burp Suite extension to find potential endpoints and parameters.[/short_descr]
[link]https://github.com/xnl-h4ck3r/GAP-Burp-Extension[/link]
[tags]burpsuite,endpoints,parameters[/tags]
[image]https://raw.githubusercontent.com/xnl-h4ck3r/GAP-Burp-Extension/main/GAP/images/tab.png[/image]
[long_descr]For a full explanation of GAP features, see https://github.com/xnl-h4ck3r/GAP-Burp-Extension/blob/main/GAP%20Help.md[/long_descr]

**Comment by gwen001** [comment]
Hi,

As said in the [guidelines](https://github.com/gwen001/offsectools_www/issues/1):
```
The title of the issue is the name of the tool as it will be displayed in offsec.tools with the prefix [addtool].
```
Please add the prefix `[addtool]` in the title of the issue so it could be handled by the bot.
Thanks for your contribution.

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/gap

Thank you!
