### ISSUE TITLE
[addtool] GoCloud

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#214]
[link]https://github.com/MantisSTS/GoCloud[/link]
[short_descr] Checks whether a domain is hosted on a cloud service such as AWS, Azure or CloudFlare [/short_descr]
[tags]cloud,ips[/tags]
[long_descr]If you need to find out whether a domain resolves to a cloud hosted such as AWS, Azure, Cloudflare, etc, then you can put all of the domains into a file and run GoCloud which will let you know whether they resolve to a cloud service.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/209174247-755030ef-5e01-46c2-92e6-5689ec335c7a.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/gocloud

Thank you!
