### ISSUE TITLE
[addtool] ScrapeIn

### ISSUE THREAD

**Issue by landoncrabtree** [gwen001/offsectools_www#257]
[short_descr]OSINT gathering tool that allows you to compile a list of employee email addresses from a specific company via LinkedIn.[/short_descr]
[link]https://github.com/landoncrabtree/ScrapeIn[/link]
[tags]osint,crawler[/tags]
[image]https://camo.githubusercontent.com/7c202e98c5d97ab540a09a099aff8424fa5c9dbb0ffa5493d9388d49ee35ef7e/68747470733a2f2f692e696d6775722e636f6d2f664d37414947612e706e67[/image]
[long_descr]ScrapeIn generates an output of possible company-specific employee emails via scraping LinkedIn. This list of emails can be useful for curated phishing attacks or password spraying attacks. Further, it supports custom email formatting, allowing you to generate emails the way the company formats their employee emails (refer to Hunter.io). [/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/scrapein

Thank you!
