### ISSUE TITLE
AORT

### ISSUE THREAD

**Issue by AyoubNajim** [gwen001/offsectools_www#281]

**Comment by AyoubNajim** [comment]
Description : 
An easy-to-use python tool to perform dns recon, subdomain enumeration and much more
The purpouse of this tool is helping bug hunters and pentesters during reconnaissance.

Link : https://github.com/AyoubNajim/AORT

Tags : #subdomains #dns #ips #scanner

![image](https://user-images.githubusercontent.com/68334573/209541613-d95faf08-ddfb-4fff-9b4d-faf1a844017b.png)

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the guidelines here https://github.com/gwen001/offsectools_www/issues/1

Thank you for your understanding.

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/781
