### ISSUE TITLE
[addtool] BHHB

### ISSUE THREAD

**Issue by adityatelange** [gwen001/offsectools_www#314]
[short_descr]Tool to view HTTP history exported from Burp Suite Community Edition[/short_descr]
[link]https://github.com/adityatelange/bhhb[/link]
[tags]burpsuite[/tags]
[image]https://raw.githubusercontent.com/adityatelange/bhhb/main/src/assets/bhhb.png[/image]
[long_descr]

➡️ https://adityatelange.github.io/bhhb/

=> What problem does this solve?
- Burp Suite Community Edition has one BIG feature pay-walled - Disk-based projects 💾.
- Because of which Community Edition users cannot save their HTTP history and Sitemap info, which are destroyed after the temporary session is closed 🗑.
- Although this is a thing, users can export their Burp CE's HTTP history by selecting the records (Ctrl+A) and using Save items 💾 option in context menu of Proxy->HTTP history or Target->Sitemap or Logger.
- Using that Burp will export the HTTP history along with Requests and Responses into a XML file.
- BHHB can open these exported items, parse it and display them in a well-formatted manner. 📋
- This application is a PWA, which can be installed in any chromium based browser and could run offline, with all of the processing done on device itself ⚙️.

[/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
