### ISSUE TITLE
Faraday security

### ISSUE THREAD

**Issue by Flormigliorisi** [gwen001/offsectools_www#315]
[short_descr]Open Source Vulnerability Management and Orchestration Platform[/short_descr]
[link]https://faradaysec.com/[/link]
[tags]vulnerability management, cybersecurity, pentesting[/tags]
[image](https://user-images.githubusercontent.com/112972715/209679974-a34ab2c1-c141-4f10-b909-9709ab700b35.png)[/image]
[long_descr]A single platform for Vulnerability Management, built alongside security specialists and designed to speed up detection & triage of vulnerabilities. Scan, report, automate, and prioritize your actions with just a few clicks.
Make sense of today’s overwhelming number of tools. Faraday’s technology aligns +90 key plugins with your current needs, normalizing and deduplicating vulnerabilities.[/long_descr]

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

Thank you for your understanding.
