### ISSUE TITLE
[addtool] See-SURF

### ISSUE THREAD

**Issue by In3tinct** [gwen001/offsectools_www#337]
[short_descr] Detect Vulnerable SSRF parameters [/short_descr]
[link]https://github.com/In3tinct/See-SURF[/link]
[tags]ssrf, scanner[/tags]
[long_descr]A Python based scanner to find potential SSRF parameters in a web application. See-SURF helps you detect potential SSRF parameters and validates the finding it by making a DNS/HTTP request back to your server. It can be added to your arsenal of recon while doing bug hunting/web security testing. [/long_descr]
![61342277-849e2800-a7fe-11e9-832b-7de37cb027ff](https://user-images.githubusercontent.com/18059590/209733482-0756f53e-3409-4e54-972a-11638dda7e5d.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/see-surf

Thank you for your contribution!
