### ISSUE TITLE
[addtool] Oh365UserFinder

### ISSUE THREAD

**Issue by dievus** [gwen001/offsectools_www#346]
[short_descr] O365 user enumeration and password spraying tool written in Python3. [/short_descr]
[link] https://github.com/dievus/Oh365UserFinder [/link]
[tags] OSINT, passwords, password spraying, enumeration [/tags]
[image] https://github.com/dievus/Oh365UserFinder/blob/main/images/oh365userfinder1.jpg [/image]
[long_descr] Oh365UserFinder is used for identifying valid o365 accounts and domains without the risk of account lockouts.  The tool parses responses to identify the "IfExistsResult" flag is null or not, and responds appropriately if the user is valid.  The tool will attempt to identify false positives based on response, and either automatically create a waiting period to allow the throttling value to reset, or warn the user to increase timeouts between attempts.  

Oh365UserFinder can also easily identify if a domain exists in o365 using the -d or --domain flag.  This saves the trouble of copying the url from notes and entering it into the URL bar with the target domain.

With version 1.1.0, password spraying is now possible. If MFA is enabled, the tool SHOULD identify it when reporting a valid account. Keep in mind that account lockouts are possible if too many incorrect attempts are made. Make sure to consult with your client to determine the lockout policy if you have any concerns. [/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/oh365userfinder

Thank you for your contribution!
