### ISSUE TITLE
[addtool] MSDNSScan

### ISSUE THREAD

**Issue by dievus** [gwen001/offsectools_www#347]
[short_descr] MSDNSScan is used to identify DNS records for target domains, check for zone transfers and conduct subdomain enumeration [/short_descr]
[link] https://github.com/dievus/msdnsscan [/link]
[tags] dns, osint, crawler, subdomains [/tags]
[image] https://github.com/dievus/msdnsscan/blob/main/images/msdnsscan.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/msdnsscan

Thank you for your contribution!
