### ISSUE TITLE
[addtool] MSDorkDump

### ISSUE THREAD

**Issue by dievus** [gwen001/offsectools_www#348]
[short_descr] MSDorkDump queries a specified domain name and variety of file extensions, downloads, and then runs Exiftool on them [/short_descr]
[link] https://github.com/dievus/msdorkdump [/link]
[tags] osint, crawler, secrets [/tags]
[image] https://github.com/dievus/msdorkdump/blob/main/images/dorkdump.png [/image]
[long_descr] MSDorkDump is a Google Dork File Finder that queries a specified domain name and variety of file extensions (pdf, doc, docx, etc), downloads , and then runs Exiftool on them to enumerate metadata. Note that due to Google's built in rate limiting, queries may end up timed out if too many are made in a short amount of time. [/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/msdorkdump

Thank you for your contribution!
