### ISSUE TITLE
[addtool] Prowler

### ISSUE THREAD

**Issue by SantiEich** [gwen001/offsectools_www#367]
[short_descr] Open Source Security tool to perform Cloud Security best practices  [/short_descr]
[link] [https://github.com/prowler-cloud/prowler [/link]](https://github.com/prowler-cloud/prowler)
[tags] cloud,cybersecurity [/tags]
[image][https://user-images.githubusercontent.com/3985464/113734260-7ba06900-96fb-11eb-82bc-d4f68a1e2710.png[/image]](https://user-images.githubusercontent.com/3985464/113734260-7ba06900-96fb-11eb-82bc-d4f68a1e2710.png)
[long_descr] Prowler is an Open Source Security tool to perform Cloud Security best practices assessments, audits, incident response, continuous monitoring, hardening and forensics readiness. It contains hundreds of controls covering CIS, PCI-DSS, ISO27001, GDPR, HIPAA, FFIEC, SOC2, AWS FTR, ENS and custom security frameworks.  [/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/prowler

Thank you for your contribution!
