### ISSUE TITLE
[addtool] infoooze

### ISSUE THREAD

**Issue by devXprite** [gwen001/offsectools_www#395]
[short_descr]User-friendly OSINT tool that allows you to quickly and easily gather informations.[/short_descr]
[homepage]https://github.com/devXprite/infoooze[/homepage]
[tags]osint[/tags]
[long_descr]
Infoooze is a powerful and user-friendly OSINT (Open-Source Intelligence) tool that allows you to quickly and easily gather information about a specific target. With Infoooze, you can easily search for information about websites, IP addresses, usernames, and more, all from the convenience of a simple command-line interface.

One of the key features of Infoooze is its ability to work as a global package, allowing you to use it from any directory on your computer.It also has ability to automatically save the results of your searches to a text file. This means that you can easily access and refer to the information you have gathered at a later time.

Infoooze is easy to install and use, making it an ideal tool for anyone looking to gather information quickly and efficiently.
[/long_descr]

![logo-main](https://user-images.githubusercontent.com/5347721/217488551-223bb8f1-205c-43d1-993c-eafebfa8a63f.png)

**Comment by gwen001** [comment]
Sorry but the bot cannot handle this issue because it doesn't respect the required format.

Please edit the original issue according the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
You can also check one of the 300 issues already closed to see how it's supposed to be.

Thank you for your understanding.

**Comment by gwen001** [comment]
Problem occured with the following fields: homepage, picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Problem occured with the following fields: homepage

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/infoooze

Thank you for your contribution!
