### ISSUE TITLE
[addtool] scilla

### ISSUE THREAD

**Issue by edoardottt** [gwen001/offsectools_www#420]
[short_descr]Information Gathering tool - DNS / Subdomains / Ports / Directories enumeration[/short_descr]
[link]https://github.com/edoardottt/scilla[/link]
[tags]enumeration,subdomain,fuzzer,bruteforce,portscan,dns,http,web[/tags]
[image]https://raw.githubusercontent.com/edoardottt/images/main/scilla/logo.png[/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/211
