### ISSUE TITLE
[addtool] csprecon

### ISSUE THREAD

**Issue by edoardottt** [gwen001/offsectools_www#421]
[short_descr]Discover new target domains using Content Security Policy[/short_descr]
[link]https://github.com/edoardottt/csprecon[/link]
[tags]csp,subdomain,web,recon[/tags]
[image]https://pbs.twimg.com/card_img/1606386967452622848/xXi1C1sU?format=jpg&name=small[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/csprecon

Thank you for your contribution!
