### ISSUE TITLE
[addtool] mitmproxy

### ISSUE THREAD

**Issue by 0xPugazh** [gwen001/offsectools_www#467]
[link]https://github.com/mitmproxy/mitmproxy[/link]
[short_descr]An interactive TLS-capable intercepting HTTP proxy for penetration testers and software developers.[/short_descr]
[long_descr]mitmproxy is an interactive, SSL/TLS-capable intercepting proxy with a console interface for HTTP/1, HTTP/2, and WebSockets. mitmdump is the command-line version of mitmproxy. mitmweb is a web-based interface for mitmproxy.[/long_descr]
[tags]#proxy[/tags]
[image]https://user-images.githubusercontent.com/75373225/210199779-e562cd43-fb25-4dd1-a8b8-dbe5e5020865.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/mitmproxy

Thank you for your contribution!
