### ISSUE TITLE
[addtool] Betterscan.io

### ISSUE THREAD

**Issue by marcinguy** [gwen001/offsectools_www#468]
[short_descr]Code Scanning/SAST/Static Analysis/Linting using many tools/Scanners with One Report (Code, IaC)[/short_descr]
[link]https://github.com/marcinguy/betterscan-ce[/link]
[tags]code security, cloud security, SAST, DAST[/tags]
[image]https://uploads-ssl.webflow.com/6339e3b81867539b5fe2498d/6339e4ff689e383aa9acb1f9_mainscreen.png[/image]
[long_descr]A simple and powerful software to automate thousands of checks (orchestration) and eliminate human errors in Code and Cloud Infrastructure. Our software uses multiple very known and state of the art Open Source components as plugins (in that sense it is a "wrapper", "Meta" scanner) and provides you with unified one report and very fast results due to using of project state (no need to rescan the whole project every time) and unification (no duplicates). Software is very modular and any Open Source tool or proprietary check can be added as a plugin. Supports all major Programming languages and Cloud technologies. Software is available as Open Source in Community Edition and paid Professional/Business variants.[/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/betterscan

Thank you for your contribution!
