### ISSUE TITLE
[addtool] Simple Basic Malware Scanner

### ISSUE THREAD

**Issue by password123456** [gwen001/offsectools_www#475]
[short_descr]Simple Malware Scanner based on file hash scan[/short_descr]
[link]https://github.com/password123456/malwarescanner[/link]
[tags]scanner,malware,incident_response[/tags]
[image]https://github.com/password123456/malwarescanner/blob/main/preview.JPG[/image]
[long_descr]Simple Malware Scanner is a malware scanner based on file hash scan.
If you look for tools like this to use when security incident occurs,you may not actually be able to use them. this is used in that case. I had the same experience.you can modify and use the features that you want with a little modification. Good Luck to you.[/long_descr]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/simple-basic-malware-scanner

Thank you for your contribution!
