### ISSUE TITLE
[addtool] SprayCannon

### ISSUE THREAD

**Issue by CausticKirbyZ** [gwen001/offsectools_www#480]
[link] https://github.com/CausticKirbyZ/SprayCannon [/link]
[short_descr] Fast multithreaded password spraying tool with backend database. [/short_descr]
[long_descr] A fast multithreaded password spraying tool with delays, jitter, backend database, webhooks, previous spray detection, and more. Supports multiple spraying targets including O365 with user validation, mfa detection, and Conditional Access detection, Exchange EAS and OWA, vpns, esxi and more.  [/long_descr]
[tags] passwords,spraying,enumeration [/tags]
[image] https://raw.githubusercontent.com/CausticKirbyZ/SprayCannon/main/mdassets/spraycannon_art.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/spraycannon

Thank you for your contribution!
