### ISSUE TITLE
[addtool] dnsReaper

### ISSUE THREAD

**Issue by SimonGurney** [gwen001/offsectools_www#489]
[link]https://github.com/punk-security/dnsReaper[/link]
[tags]DNS,subdomain,hijack[/tags]
[short_descr]
dnsReaper is a subdomain takeover detection tool.  It doesn't do any brute forcing or enumeration.  It scans the provided domains and tests to see if you can take them over (GitHub pages, Netlify etc)[/short_descr]
[long_descr] [/long_descr] 
[image] [/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/155
