### ISSUE TITLE
[addtool] Spoofy

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#493]
[link] https://github.com/MattKeeley/Spoofy [/link]
[tags] all, vulnerabilities, domains, spoofing [/tags]
[short_descr] Spoofy is a program that checks if a list of domains can be spoofed based on SPF and DMARC records. [/short_descr]
[long_descr] Spoofy is a program that checks if a list of domains can be spoofed based on SPF and DMARC records. You may be asking, "Why do we need another tool that can check if a domain can be spoofed?" Well, Spoofy is different, and here is why: authoritative lookups on all lookups with known fallback (Cloudflare DNS), accurate bulk lookups, custom and manually tested spoof logic (No guessing or speculating, real-world test results), and SPF lookup counter.[/long_descr] 
[image] https://github.com/MattKeeley/Spoofy/blob/main/files/Spoofy.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/spoofy

Thank you for your contribution!
