### ISSUE TITLE
[addtool] ADReaper

### ISSUE THREAD

**Issue by ErwDt** [gwen001/offsectools_www#510]
[homepage]https://github.com/AidenPearce369/ADReaper[/homepage] 
    [tags]activedirectory,AD,windows,LDAP[/tags]
    [short_descr]ADReaper enumerates an Active Directory environment with LDAP queries [/short_descr]
    [long_descr]ADReaper performs enumeration with various commands that performs LDAP queries with respective to it (domain controllers,domain trust,users,computers,service principal objects,group policy objects,organizational units,MS-SQL servers,AS-REP roastable accounts,Unconstrained Delegated accounts...) [/long_descr]
[image]
![git](https://user-images.githubusercontent.com/11173666/211020455-228d8a35-08f2-453e-9b33-92547d6b5594.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/adreaper

Thank you for your contribution!
