### ISSUE TITLE
[addtool]SSH-PuTTY-login-bruteforcer 

### ISSUE THREAD

**Issue by ErwDt** [gwen001/offsectools_www#512]
[homepage]https://github.com/InfosecMatter/SSH-PuTTY-login-bruteforcer[/homepage]
[tags]windows,ssh,bruteforce,putty,plink[/tags]
[short_descr]The ssh-putty-brute is a wrapper script which uses PuTTY to perform SSH login bruteforce attacks.[/short_descr]
[long_descr]There are many great tools out there for performing SSH login brute forcing.
The problem with these tools is that they are all flagged by every decent Antivirus or endpoint protection solution. And in some situations that is a problem.
Only tool that we managed to sneak in was PuTTY SSH client. But for our purposes it was very impractical.
And that’s when we had an idea – can we somehow automate PuTTY and use it as an SSH login brute forcing tool?
Turns out with a little bit of PowerShell scripting, yes we can![/long_descr] 
[image]
![80275175-93e8c500-86f0-11ea-9838-346e68f404b5](https://user-images.githubusercontent.com/11173666/211032343-d7684be7-d0db-4e29-ad03-b48070af7ca6.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ssh-putty-login-bruteforcer

Thank you for your contribution!
