### ISSUE TITLE
[addtool] GitFive

### ISSUE THREAD

**Issue by ajmeese7** [gwen001/offsectools_www#532]
[homepage]https://github.com/mxrch/GitFive[/homepage]
[tags]git,osint[/tags]
[short_descr]GitFive is an OSINT tool to investigate GitHub profiles.[/short_descr]
[long_descr]Main features :

- Usernames / names history
- Usernames / names variations
- Email address to GitHub account
- Find GitHub's accounts from a list of email addresses
- Lists identities used by the target
- Clones and analyze every target's repos
- Highlights emails tied to GitHub's target account
- Finds local identities (UPNs, ex : [jeanpierre@My-Computer.local](mailto:jeanpierre@My-Computer.local))
- Finds potential secondary GitHub accounts
- Don't need repos to work (but better)
- Generates every possible email address combinations and looks for matchs
- Dumps SSH public keys
- JSON export
[/long_descr]
[image]https://github.com/mxrch/GitFive/raw/master/assets/banner.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/gitfive

Thank you for your contribution!

**Comment by ajmeese7** [comment]
@mxrch just wanted to give you a heads up about this, hopefully more people will find your awesome tool now!
