### ISSUE TITLE
[addtool] Injectify

### ISSUE THREAD

**Issue by ErwDt** [gwen001/offsectools_www#533]
[homepage]https://github.com/samdenty/injectify[/homepage]
[extra_link]https://injectify.js.org/demos/interface/[/extra_link]
[tags]MiMT,JS,[/tags]
[short_descr]Perform advanced MiTM attacks on websites with ease. [/short_descr]
[long_descr]Injectify is a web based MiTM tool, similiar to [BeEF](http://beefproject.com/) (although completely unrelated in terms of source code). It uses modern web technologies such as ReactJS, Redux, Typescript and Webpack.
What can it do?[¶](https://injectify.js.org/#what-can-it-do)

    ⚡ Create a reverse Javascript shell between the victim and the attacker.
    👻 PageGhost - see what's on the victims screen and interact with it in realtime
    🔧 Highly integrated Module platform, with a high-level API
    📑 Data extraction API - record custom data
        🔐 Extracts and logs saved passwords from the browser.[/long_descr] 
[image]
<img width="619" alt="Capture" src="https://user-images.githubusercontent.com/11173666/211276637-c5d79d73-591e-4a77-86ce-c5eb78630d5d.PNG">
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
