### ISSUE TITLE
[addtool]  ssh-audit

### ISSUE THREAD

**Issue by ErwDt** [gwen001/offsectools_www#559]
[homepage]https://github.com/arthepsy/ssh-audit[/homepage]
[tags]ssh,audit[/tags]
[short_descr]ssh-audit is a tool for ssh server auditing.[/short_descr]
[long_descr]Features :

    SSH1 and SSH2 protocol server support;
    grab banner, recognize device or software and operating system, detect compression;
    gather key-exchange, host-key, encryption and message authentication code algorithms;
    output algorithm information (available since, removed/disabled, unsafe/weak/legacy, etc);
    output algorithm recommendations (append or remove based on recognized software version);
    output security information (related issues, assigned CVE list, etc);
    analyze SSH version compatibility based on algorithm information;
    historical information from OpenSSH, Dropbear SSH and libssh;
    no dependencies, compatible with Python 2.6+, Python 3.x and PyPy;
[/long_descr] 
[image]
<img width="583" alt="Capture" src="https://user-images.githubusercontent.com/11173666/211512181-6a7c355e-03d5-448f-9be2-2ea92ac138e3.PNG">
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ssh-audit

Thank you for your contribution!
