### ISSUE TITLE
[addtool] Angry IP Scanner

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#579]
[homepage] https://angryip.org/ [/homepage]
[tags] all,scanner,ip,cross-platform [/tags]
[short_descr] Angry IP Scanner is a fast and simple-to-use open-source/cross-platform network scanner. [/short_descr]
[long_descr] Angry IP Scanner (or simply _ipscan_) is an open-source and cross-platform network scanner designed to be fast and simple to use. It is widely used by network administrators and just curious users around the world, including large and small enterprises, banks, and government agencies. It runs on Linux, Windows, and Mac OS X, possibly supporting other platforms as well. [/long_descr] 
[image] https://angryip.org/screenshots/ipscan-win10.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/angry-ip-scanner

Thank you for your contribution!
