### ISSUE TITLE
[addtool] WinPEAS

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#582]
[homepage] https://github.com/carlospolop/PEASS-ng/tree/master/winPEAS [/homepage]
[tags] all,vulnerabilities,scanner,windows [/tags]
[short_descr] WinPEAS is a script that searches for possible paths to escalate privileges on Windows hosts. [/short_descr]
[image] https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/raw/master/winPEAS/winPEASexe/images/winpeas.pn [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/winpeas

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool url is: https://offsec.tools/tool/peas-ng
