### ISSUE TITLE
[addtool] LinPEAS

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#583]
[homepage] https://github.com/carlospolop/PEASS-ng/tree/master/linPEAS [/homepage]
[tags] all,scanner,vulnerabilities,linux [/tags]
[short_descr] LinPEAS is a script that searches for possible paths to escalate privileges on Linux/Unix*/MacOS hosts.  [/short_descr]
[long_descr] Linux local Privilege Escalation Awesome Script (linPEAS) is a script that searches for possible paths to escalate privileges on Linux/Unix hosts. [/long_descr]
[image] https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite/raw/master/linPEAS/images/linpeas.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool url is: https://offsec.tools/tool/peas-ng
