### ISSUE TITLE
[addtool] rush

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#598]
[homepage]https://github.com/shenwei356/rush[/homepage]
[tags]parallel,jobs[/tags]
[short_descr]a cross-platform command-line tool for executing jobs in parallel[/short_descr]
[long_descr]rush is a tool similar to [GNU parallel](https://www.gnu.org/software/parallel/) and [gargs](https://github.com/brentp/gargs). rush borrows some idea from them and has some unique features, e.g., supporting custom defined variables, resuming multi-line commands, more advanced embeded replacement strings.[/long_descr] 
![image](https://user-images.githubusercontent.com/32585833/212253798-173adeea-ea70-4244-a0e4-1faaee0d1f3e.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/rush

Thank you for your contribution!
