### ISSUE TITLE
[addtool] Interlance

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#599]
[homepage]https://github.com/codingo/Interlace[/homepage]
[tags]parallel,jobs[/tags]
[short_descr]Easily turn single threaded command line applications into a fast[/short_descr]
[long_descr] Easily turn single threaded command line applications into a fast, multi-threaded application with CIDR and glob support. [/long_descr]
![image](https://user-images.githubusercontent.com/32585833/212254202-427caba3-222f-40df-9ae4-8d9832968911.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/interlance

Thank you for your contribution!

**Comment by gwen001** [comment]
Please take care of the data you submit. Name of the tool isn't correct, short description is truncated, and there is no point to copy the same text to the long description.

Please also note that the site tries to focus on security/hacking tools. Thank you for your contribution.

**Comment by mrrootsec** [comment]
Sorry my bad..
