### ISSUE TITLE
[addtool] linWinPwn

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#608]
[homepage] https://github.com/lefayjey/linWinPwn [/homepage]
[tags] all,enumerartion,AD (required)[/tags]
[short_descr] linWinPwn is a bash script that automates a number of Active Directory Enumeration and Vulnerability checks. [/short_descr]
[long_descr] linWinPwn is a bash script that automates a number of Active Directory Enumeration and Vulnerability checks. The script uses a number of tools and serves as a wrapper for them. Tools include: impacket, bloodhound, crackmapexec, ldapdomaindump, lsassy, smbmap, kerbrute, adidnsdump, certipy, silenthound, and others. [/long_descr] 
[image] https://ibb.co/1bMmL9k [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/linwinpwn

Thank you for your contribution!
