### ISSUE TITLE
[addtool] Malicious PDF Generator

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#610]
[homepage] https://github.com/jonaslejon/malicious-pdf [/homepage]
[tags] all,malicious,pdf [/tags]
[short_descr] Generates a bunch of malicious pdf files with phone-home functionality. [/short_descr]
[long_descr] Generate ten different malicious pdf files with phone-home functionality. Can be used with [Burp Collaborator](https://portswigger.net/burp/documentation/collaborator) or [Interact.sh](https://github.com/projectdiscovery/interactsh) [/long_descr] 
[image] https://camo.githubusercontent.com/fd7746aa5354c5ddde020f6a64249f69f1c122ed0a3cbf2643a0fbb16945d59e/68747470733a2f2f7472696f702e73652f77702d636f6e74656e742f75706c6f6164732f323032312f30382f6d616c6963696f75732d7064662d65313632393139373732363236302e706e67 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/malicious-pdf-generator

Thank you for your contribution!
