### ISSUE TITLE
[addtool] psudohash

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#612]
[homepage] https://github.com/t3l3machus/psudohash [/homepage]
[tags] all,password, bruteforce (required)[/tags]
[short_descr] psudohash is a password list generator for orchestrating brute force attacks. [/short_descr]
[long_descr] psudohash is a password list generator for orchestrating brute force attacks. It imitates certain password creation patterns commonly used by humans, like substituting a word's letters with symbols or numbers, using char-case variations, adding a common padding before or after the word and more. It is keyword-based and highly customizable. [/long_descr] 
[image] https://camo.githubusercontent.com/d31e900c0c8d74bcc16b709f91c3b2828c5b86fb76f31e96dc49ca364e895cc3/68747470733a2f2f7261772e6769746875622e636f6d2f74336c336d61636875732f707375646f686173682f6d61737465722f53637265656e73686f74732f6d732d6578616d706c652e706e67 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/psudohash

Thank you for your contribution!
