### ISSUE TITLE
[addtool] Demiguise

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#616]
[homepage] https://github.com/nccgroup/demiguise [/homepage]
[tags] all,cryptography,hta (required)[/tags]
[short_descr] HTA encryption tool for Red Teams. [/short_descr]
[long_descr] The aim of this project is to generate .html files that contain an encrypted HTA file. The idea is that when your target visits the page, the key is fetched and the HTA is decrypted dynamically within the browser and pushed directly to the user. This is an evasion technique to get round content / file-type inspection implemented by some security-appliances. [/long_descr] 
[image] https://camo.githubusercontent.com/1179607a6a9579383b9b704d0a55650ca9a73cceed70d0a15bbc16a47ee96708/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c314a334864586b6243436537737157592f67697068792e676966 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/demiguise

Thank you for your contribution!
