### ISSUE TITLE
[addtool] Covenant

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#617]
[homepage] https://github.com/cobbr/Covenant [/homepage]
[tags] all,redteam,c2,dotnet [/tags]
[short_descr] Covenant is a collaborative .NET C2 framework for red teamers. [/short_descr]
[long_descr] Covenant is a .NET command and control framework that aims to highlight the attack surface of .NET, make the use of offensive .NET tradecraft easier, and serve as a collaborative command and control platform for red teamers. [/long_descr] 
[image] https://github.com/cobbr/Covenant/wiki/images/covenant-gui-dashboard.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/covenant

Thank you for your contribution!
