### ISSUE TITLE
[addtool] EDD

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#618]
[homepage] https://github.com/FortyNorthSecurity/EDD [/homepage]
[tags] all,domains,enumeration,dotnet [/tags]
[short_descr] EDD (Enumerate Domain Data) is designed to be similar to Power View but in .NET. [/short_descr]
[long_descr] EDD (Enumerate Domain Data) is designed to be similar to Power View but in .NET. Power View is essentially the ultimate domain enumeration tool, and we wanted a .NET implementation that we worked on ourselves. This tool was largely put together by viewing implementations of different functionality across a wide range of existing projects and combining them into EDD. [/long_descr] 
[image] https://fortynorthsecurity.com/blog/content/images/size/w1000/2021/03/gethelp-inverted.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/edd

Thank you for your contribution!
