### ISSUE TITLE
[addtool] SubScout

### ISSUE THREAD

**Issue by 0xAkashsky** [gwen001/offsectools_www#652]
[homepage]https://github.com/0xAkashsky/sub-scout [/homepage]
[tags]recon, automation, subdomain, bruteforce, permutation[/tags]
[short_descr]
A simple bash script to automate your initial recon and extend your attack surface using popular tools made by infosec community.[/short_descr]
[long_descr]
What Sub-scout does ? 
Sub-scout generate keywords from known subdomain file
Makes its kind of own permutations list according to scope
Parses permutations list to regulator to make rules
builds final permutation list according to the rules using regulator
Resolves permutation subdomain list using PureDns
Parses PureDns resolved domain to httpx for http and https probing
Runs Aquatone on httpx results.
Runs Wayback on resolved domains.
Runs Katana on resolved domains.
Collect Javascript files by Combining wayback and katana output
Check live Javascript files using httpx
[/long_descr] 
[image] https://raw.githubusercontent.com/0xAkashsky/sub-scout/main/static/sub-scout-logo1.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
