### ISSUE TITLE
[addtool] lk_scraper

### ISSUE THREAD

**Issue by gwen001** [gwen001/offsectools_www#661]
[homepage]https://github.com/jqueguiner/lk_scraper[/homepage]
[tags]linkedin,scraper[/tags]
[short_descr]A fully configurable LinkedIn scraper: scrape anything within LinkedIn.[/short_descr]
[long_descr][/long_descr]
[image]https://raw.githubusercontent.com/gwen001/offsectools_www/main/e3cad63802a4b7a38e0edbc783d8c692.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/lk_scraper

Thank you for your contribution!

**Comment by Bilal815** [comment]
I recently tried Crawlbase to scrape LinkedIn and it worked like butter. Seems like nothing better than this API in the market. I have gone through their docs, it says that you need JS enabled to scrape dynamic sites. This is where it gets interesting https://crawlbase.com/docs/crawling-api/scrapers/#linkedin. They have the option to get data off both companies as well as profiles. Just make sure to signup.

**Comment by gwen001** [comment]
Thanks for the info, feel free to open a new issue to add the tool on offsec.tools.
