### ISSUE TITLE
[addtool] ADRT

### ISSUE THREAD

**Issue by 100security** [gwen001/offsectools_www#686]
[homepage]https://github.com/100security/adrt[/homepage]
[extra_link]https://www.100security.com.br/adrt[/extra_link]
[tags]adrt,powershell,active directory,users,objects,export,report,redteam,pentest,enumeration,information gathering,domain admins,domain users, passwords, all users, ous, gpos, dcs, lastlogon[/tags]
[short_descr]Active Directory Report Tool[/short_descr]
[long_descr]Tool used by network administrators and security analysts to extract information from Active Directory, such as: Users, Groups, Administrators, Domain Controllers, Password Never Expire, All Computers, All Servers, GPOs, Last Logon, Disabled Users, Member Groups and Inventory.[/long_descr]
[image]https://www.100security.com.br/images/adrt-02.jpg[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/adrt

Thank you for your contribution!
