### ISSUE TITLE
[addtool] Apidor

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#711]
[homepage] https://github.com/bm402/apidor [/homepage]
[tags] all,web,idor,scan [/tags]
[short_descr] Tool for automating the search for IDOR vulnerabilities in web applications and APIs. [/short_descr]
[image] https://ibb.co/R03CsXC [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/apidor

Thank you for your contribution!
