### ISSUE TITLE
[addtool] Up Http Server

### ISSUE THREAD

**Issue by 0dayCTF** [gwen001/offsectools_www#714]
[homepage]https://github.com/MuirlandOracle/up-http-tool[/homepage]
[extra_link][/extra_link]
[tags]linux,server,python,alias,bash,tools,webserver[/tags]
[short_descr]Simple HTTP listener for security testing[/short_descr]
[long_descr]Wrapper around Flask / Waitress, dropping in as a replacement for the classic "python3 -m http.server". Useful for security testing. This was originally written to assist with WEB-300 (OSWE) coursework, so you may find it useful if you're attempting that.[/long_descr] 
[image]https://i.imgur.com/bZ0V3db.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/up-http-server

Thank you for your contribution!

**Comment by 0dayCTF** [comment]
The homepage URL is broken https://github.com/MuirlandOracle/up-http-tool

**Comment by gwen001** [comment]
Fixed.
