### ISSUE TITLE
[addtool] WifiPass

### ISSUE THREAD

**Issue by bhanugoudm041** [gwen001/offsectools_www#717]
[homepage]https://github.com/bhanugoudm041/wifipass[/homepage]
[extra_link]https://github.com/bhanugoudm041/wifipass[/extra_link]
[tags]Wifi-Security,Network-Security[/tags]
[short_descr]A simple Wireless Networks Penetration Testing Toolkit[/short_descr]
[long_descr]WifiPass is a small wireless networks penetration testing toolkit. It has many feature such as enabling monitor mode,
disabling monitor mode, caputuring handshakes & also it can crack the wireless networks passwords. It also has a speacial feature that will rename the network interfaces[/long_descr] 
[image]
![image](https://user-images.githubusercontent.com/92798414/214571779-0838c08b-702e-451d-9662-829ef27b22c0.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/wifipass

Thank you for your contribution!
