### ISSUE TITLE
[addtool] Yara

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#719]
[homepage]https://virustotal.github.io/yara/ [/homepage]
[extra_link]https://github.com/virustotal/yara [/extra_link]
[tags]vulunerabilities,malware,yara[/tags]
[short_descr]The pattern matching swiss knife for malware researchers [/short_descr]
[long_descr]YARA is a tool aimed at helping malware researchers to identify and classify malware samples. With YARA you can create descriptions of malware families (or whatever you want to describe) based on textual or binary patterns. Each description, a.k.a rule, consists of a set of strings and a boolean expression which determine its logic. [/long_descr] 
[image]
![logo](https://user-images.githubusercontent.com/53378318/214808569-181ff64a-d167-45e6-af0d-c9baee8dc24e.jpg)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/yara

Thank you for your contribution!
