### ISSUE TITLE
[addtool] drek

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#720]
[homepage]https://github.com/chrisallenlane/drek[/homepage]
[tags]codeanalysis,vulnerabilities[/tags]
[short_descr]A static-code-analysis tool for performing security-focused code reviews.[/short_descr]
[long_descr] It enables an auditor to swiftly map the attack-surface of a large application, with an emphasis on identifying development anti-patterns and footguns.
Much like grep, drek scans a codebase for user-defined regular-expressions. Unlike grep, drek outputs its results into an ergonomic html report that allows for sorting, filtering, and annotating of points-of-interest.[/long_descr] 
![image](https://user-images.githubusercontent.com/32585833/215009156-f25276c6-bca9-4624-a4d7-57c760df2b99.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/drek

Thank you for your contribution!
