### ISSUE TITLE
[addtool] chisel

### ISSUE THREAD

**Issue by wetterSpitze** [gwen001/offsectools_www#721]
[homepage]https://github.com/jpillora/chisel[/homepage]
[tags]proxy,tunneling,pivoting,network[/tags]
[short_descr]Chisel is a fast TCP/UDP tunnel, transported over HTTP, secured via SSH. Single executable including both client and server. Written in Go (golang). Chisel is mainly useful for passing through firewalls, though it can also be used to provide a secure endpoint into your network.[/short_descr]

![68747470733a2f2f646f63732e676f6f676c652e636f6d2f64726177696e67732f642f317035335657787a474e667938726a722d6d5738707669734a6d686b6f4c6c383276416763744f5f366631772f7075623f773d39363026683d373230](https://user-images.githubusercontent.com/5347721/215327958-739448ed-29fa-47be-b0ed-288c440fec5f.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
