### ISSUE TITLE
[addtool] Legitify

### ISSUE THREAD

**Issue by royb-legit** [gwen001/offsectools_www#722]
[homepage]https://github.com/Legit-Labs/legitify[/homepage]
[extra_link]https://legitify.dev/[/extra_link]
[tags]misconfigurations,scanner,github,gitlab,scm[/tags]
[short_descr]Detect misconfigurations and security risks across GitHub and GitLab assets[/short_descr]
[image]
![image](https://user-images.githubusercontent.com/72736154/215319086-d0abfea5-29c6-456c-ad51-21d20a1832d0.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/legitify

Thank you for your contribution!
