### ISSUE TITLE
[addtool] Oculus

### ISSUE THREAD

**Issue by leddcode** [gwen001/offsectools_www#723]
[homepage]https://github.com/leddcode/Oculus[/homepage]
[tags]osint,fuzzing,cloud,subdomains,directories[/tags]
[short_descr]Domain OSINT tool.[/short_descr]
[long_descr]Oculus is a Domain OSINT Tool used to discover environments, directories, and subdomains of a particular domain. Additionally, it is useful for searching S3 Buckets, Azure Blob Containers, Firebase DBs, leaked email addresses and MX records of a domain.[/long_descr] 
[image]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/46251307/215345235-7d1645be-227b-4fda-a3de-fe90dfc5015e.png">
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/oculus

Thank you for your contribution!
