### ISSUE TITLE
[addtool] Aranea

### ISSUE THREAD

**Issue by leddcode** [gwen001/offsectools_www#726]
[homepage]https://github.com/leddcode/Aranea[/homepage]
[tags]crawler,parser,secrets,endpoints,javascript,angular,spa[/tags]
[short_descr]The OSINT tool used for web crawling or examining JavaScript files for likely useful data.[/short_descr]
[long_descr]The assessment generally starts with different recon steps, like scanning, URL crawling, fuzzing, and so on. In some cases, however, such as the testing of SPA applications, regular URL-crawling seems to be pretty meaningless, and fuzzing may not be "tester-friendly". 
This simple tool provides information about the app by parsing the JavaScript files and extracting API endpoints or other probably useful strings.
It can also be used as a regular URL crawler 🕷️[/long_descr] 
[image]<img width="951" alt="image" src="https://user-images.githubusercontent.com/46251307/215359339-cd9df5ca-f54a-4a6e-b6ba-7de797ca115c.png">[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/aranea

Thank you for your contribution!
