### ISSUE TITLE
[addtool] Malwoverview

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#727]
[homepage] https://awesomeopensource.com/project/alexandreborges/malwoverview [/homepage]
[extra_link] https://github.com/alexandreborges/malwoverview [/extra_link]
[tags]Malware,threat hunting[/tags]
[short_descr] Malwoverview is a first response tool used for threat hunting and offers intel information from Virus Total, Hybrid Analysis, URLHaus, Polyswarm, Malshare, Alien Vault, Malpedia, Malware Bazaar, ThreatFox, Triage, InQuest and it is able to scan Android devices against VT. [/short_descr]
[image]
![Malwoverview](https://user-images.githubusercontent.com/53378318/215429487-f40ed622-491b-4097-bb1c-795e1813eb93.jpg)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
