### ISSUE TITLE
[addtool] Evilgrade

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#743]
[homepage]https://github.com/infobyte/evilgrade [/homepage]
[extra_link]https://www.faradaysec.com/ [/extra_link]
[tags]vulnerabilities,framework,MITM[/tags]
[short_descr]Evilgrade is a modular framework that allows the user to take advantage of poor upgrade implementations by injecting fake updates. It comes with pre-made binaries (agents), a working default configuration for fast pentests, and has it's own WebServer and DNSServer modules. Easy to set up new settings, and has an autoconfiguration when new binary agents are set.[/short_descr]
[image]
![faraday](https://user-images.githubusercontent.com/53378318/215706971-edb77099-a39f-4dd9-9719-e1b169250e12.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
