### ISSUE TITLE
[addtool] Sub-Drill

### ISSUE THREAD

**Issue by Fadavvi** [gwen001/offsectools_www#744]
[homepage]https://github.com/Fadavvi/Sub-Drill [/homepage]
[tags]subdomains[/tags]
[short_descr]A very (very) FAST and simple subdomain finder based on online & free services. Without any configuration requirements[/short_descr]
[image]https://github.com/Fadavvi/Sub-Drill/blob/master/Logo.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/sub-drill

Thank you for your contribution!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/sub-drill

Thank you for your contribution!
