### ISSUE TITLE
[addtool] Onex

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#745]
[homepage] https://github.com/jackind424/onex     [/homepage]
[tags]vulunerabilities,linux,termux[/tags]
[short_descr]
onex is a hacking tool installer and package manager for hackers. Onex is a library of all hacking tools for Termux and other Linux distributions. onex can install any third party tool or any hacking tool for you. 
[/short_descr]
[image]
![1oneX](https://user-images.githubusercontent.com/53378318/215861848-6f46e07a-35bd-4399-8805-c5a694e0b554.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/onex

Thank you for your contribution!
