### ISSUE TITLE
[addtool] Scapy

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#748]
[homepage] https://github.com/secdev/scapy [/homepage]
[tags]Python,NetworkSecurity,Analysis[/tags]
[short_descr]Scapy is a powerful Python-based interactive packet manipulation program and library.[/short_descr]
[long_descr]
Scapy: the Python-based interactive packet manipulation program & library. 
It is able to forge or decode packets of a wide number of protocols, send them on the wire, capture them, store or read them using pcap files, match requests and replies, and much more. It is designed to allow fast packet prototyping by using default values that work.
It can easily handle most classical tasks like scanning, tracerouting, probing, unit tests, attacks or network discovery (it can replace hping, 85% of nmap, arpspoof, arp-sk, arping, tcpdump, wireshark, p0f, etc.). It also performs very well at a lot of other specific tasks that most other tools can't handle, like sending invalid frames, injecting your own 802.11 frames, combining techniques (VLAN hopping+ARP cache poisoning, VoIP decoding on WEP protected channel, ...), etc.
Scapy supports Python 2.7 and Python 3 (3.4 to 3.9). It's intended to be cross platform, and runs on many different platforms (Linux, OSX, *BSD, and Windows).
[/long_descr] 
[image]
![scapy_logo](https://user-images.githubusercontent.com/53378318/215978769-eb365612-268d-49f8-87ec-48535087b81f.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/scapy

Thank you for your contribution!
