### ISSUE TITLE
[addtool] OffensiveAzure

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#750]
[homepage] https://github.com/blacklanternsecurity/offensive-azure [/homepage]
[tags]Cloud,Azure,Python[/tags]
[short_descr]Collection of offensive tools targeting Microsoft Azure written in Python to be platform agnostic[/short_descr]
[image]
![azure](https://user-images.githubusercontent.com/53378318/215986131-253df145-e12a-4e70-8727-d821444f3b3a.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/offensiveazure

Thank you for your contribution!
