### ISSUE TITLE
[addtool] Vuls

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#751]
[homepage]https://vuls.io/ [/homepage]
[extra_link]https://github.com/future-architect/vuls [/extra_link]
[tags]Vulnerabilities,Scanner[/tags]
[short_descr]Agent-less vulnerability scanner for Linux, FreeBSD, Container, WordPress, Programming language libraries, Network devices. [/short_descr]
[image]
![vuls_logo](https://user-images.githubusercontent.com/53378318/216022163-523449a2-a7e9-428a-9936-3fd3f37f74d8.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/vuls

Thank you for your contribution!
