### ISSUE TITLE
[addtool] Pyramid

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#752]
[homepage] https://github.com/naksyn/Pyramid [/homepage]
[tags]Hacking,EDR,Python [/tags]
[short_descr]a tool to help operate in EDRs' blind spots [/short_descr]
[long_descr]Pyramid is a set of Python scripts and module dependencies that can be used to evade EDRs. The main purpose of the tool is to perform offensive tasks by leveraging some Python evasion properties and looking as a legit Python application usage[/long_descr] 
[image]
<img width="399" alt="py" src="https://user-images.githubusercontent.com/53378318/216023935-dd2c3df3-1ee8-4432-ac6d-40122ea53eca.png">
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
