### ISSUE TITLE
[addtool] RadareEye

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#753]
[homepage]https://github.com/souravbaghz/RadareEye [/homepage]
[tags]IOT,Wifi[/tags]
[short_descr]A tool for scanning nearby devices and execute command when the target device comes in between range.[/short_descr]
[image]
![eye](https://user-images.githubusercontent.com/53378318/216025968-3089a1a6-452a-4209-99ee-dc837e817465.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/radareeye

Thank you for your contribution!
