### ISSUE TITLE
[addtool] XSSRocket

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#756]
[homepage]    https://github.com/blackhatethicalhacking/XSSROCKET        [/homepage]
[tags]Web,XSS,ChatGPT[/tags]
[short_descr]XSS Rocket is written by Black Hat Ethical Hacking with the help of #ChatGPT as experimentation, with a lot of hours spent modifying the code generated by ChatGPT, and is designed for Offensive Security and XSS (Cross-Site Scripting) attacks.
[/short_descr]
[image]
![XSSRocket](https://user-images.githubusercontent.com/53378318/216273070-fe4bb1f8-fe5c-4c4b-ab18-051f9503056f.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/xssrocket

Thank you for your contribution!
