### ISSUE TITLE
[addtool] OrbitalDump

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#758]
[homepage] https://github.com/k4yt3x/orbitaldump [/homepage]
[tags]python,ssh,bruteforce[/tags]
[short_descr]A simple multi-threaded distributed SSH brute-forcing tool written in Python [/short_descr]
[image]
![orbitalDump](https://user-images.githubusercontent.com/53378318/216277092-0c7d267c-b1b6-4ed3-a336-b3a82325cd4d.png)
[/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/orbitaldump

Thank you for your contribution!
