### ISSUE TITLE
[addtool] Netlas.io

### ISSUE THREAD

**Issue by netlas-io** [gwen001/offsectools_www#782]
[homepage]https://app.netlas.io[/homepage]
[tags]cves,network,scanner,vulnerabilities,subdomains,osint,screenshots,dns[/tags]
[short_descr]Netlas.io is the network atlas of Internet. IP, DNS, Web, IoT devices, and etc.[/short_descr]
[long_descr]Netlas.io scans every IPv4 address and crawls every known website and web application utilizing such protocols as HTTP, FTP, SMTP, POP3, IMAP, SMB/CIFS, SSH, Telnet, SQL and others. Collected data is enriched with additional info and available in Netlas.io Search Engine.[/long_descr]
[image]
![image](https://user-images.githubusercontent.com/79084675/217500619-306de95e-7b31-4215-b9bb-4d352b626b3a.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/netlas.io

Thank you for your contribution!
