### ISSUE TITLE
[addtool] Pen-Andro

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#784]
[homepage]https://github.com/raoshaab/Pen-Andro [/homepage]
[link]https://github.com/raoshaab/Pen-Andro [/link]
[tags]burpsuite,proxy[/tags]
[short_descr]Script to Automate installtion of Apps ,frida server and moving Burpsuite certificate to root folder[/short_descr]
[long_descr]This Script will automate the process of installing all necessary tools & tasks for Android Pentesting i.e Moving Burpsuite Certificate ,Installing Adb frida server, APKs like proxy toggle, proxydroid, adbwifi.[/long_descr]
[image]https://github.com/raoshaab/Pen-Andro/blob/main/assets/animation.gif [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
