### ISSUE TITLE
[addtool] dBmonster

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#785]
[homepage]https://github.com/90N45-d3v/dBmonster [/homepage]
[link]https://github.com/90N45-d3v/dBmonster [/link]
[tags]wifi,tracking,proxy[/tags]
[short_descr]A Multitool For Tracking And Locating Nearby Devices Via Their RF Activities.[/short_descr]
[long_descr]With dBmonster, you are able to scan for nearby WiFi devices and track them through the signal strength (dBm) of their sent packets. Therefore, you can identify the exact location of nearby WiFi devices (use a directional WiFi antenna for the best results) or find out in which direction your (self made) antenna works the best (antenna radiation patterns).
In addition, there are features such as tracking the signal strength of packet types that are often abused in WiFi attacks (ex. Deauthentication Frames) to determine the location of someone attacking your network.
You can also check for devices that are sending Probe Requests for an unusual long time. You will then be notified when dBmonster detects that a stalker’s device is following you (inspiration: Matt Edmondson’s BlackHat article).
All in all, it's a multitool for tracking and locating nearby devices via their activities in the radio frequency range.[/long_descr]
[image]https://user-images.githubusercontent.com/79598596/181930036-ebc45598-d6dd-4291-9c4b-05f7b03bde38.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/dbmonster

Thank you for your contribution!
