### ISSUE TITLE
[addtool] GitGuardian - ggshield

### ISSUE THREAD

**Issue by ridershow** [gwen001/offsectools_www#797]
[homepage][homepage of the tool (required)](https://github.com/GitGuardian/ggshield)[/homepage]
[extra_link][gitguardian.com](https://gitguardian.com/)[/extra_link]
[tags]credentials, iac, infrastructure-as-code, scanning, apikey, precommit , devsecops, secrets-management, secrets-detection, iac-security[/tags]
[short_descr]Find and fix 350+ types of hardcoded secrets & 70+ types of infrastructure-as-code misconfigurations(required)[/short_descr]
[long_descr]A CLI application that runs in your local environment or in a CI environment to help you detect more than 350 types of secrets, as well as other potential security vulnerabilities or policy breaks.(optional)[/long_descr] 
[image]![ggshield-hero-ilustration](https://user-images.githubusercontent.com/31700505/218052217-bc47e0fa-9906-4f63-9044-ffac3d6696b9.svg)(required)[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ggshield

Thank you for your contribution!
