### ISSUE TITLE
[addtool] undetected-chromedriver

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#804]
[homepage] https://github.com/ultrafunkamsterdam/undetected-chromedriver [/homepage]
[tags] all,automation,bot,bypass [/tags]
[short_descr] Optimized Selenium Chromedriver patch which does not trigger anti-bot services. [/short_descr]
[image] https://camo.githubusercontent.com/273a1dc3ef95703c36d999479bfee115039a5b96c0abf19f45b88a175afe0e62/68747470733a2f2f692e696d6775722e636f6d2f3531416e6736522e676966 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/undetected-chromedriver

Thank you for your contribution!
