### ISSUE TITLE
[addtool] PipeViewer

### ISSUE THREAD

**Issue by rtcms** [gwen001/offsectools_www#809]
[homepage]https://github.com/cyberark/PipeViewer[/homepage]
[tags]windows,pipes,named pipes,[/tags]
[short_descr]A tool that shows detailed information about named pipes in Windows[/short_descr]
[image]https://raw.githubusercontent.com/cyberark/PipeViewer/assets/pipeviewer_logo.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pipeviewer

Thank you for your contribution!
