### ISSUE TITLE
[addtool] autossrf

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#812]
[homepage]https://github.com/Th0h0/autossrf [/homepage]
[link]https://github.com/Th0h0/autossrf [/link]
[tags]ssrf [/tags]
[short_descr]Smart context-based SSRF vulnerability scanner.[/short_descr]
[long_descr]autoSSRF is your best ally for identifying SSRF vulnerabilities at scale. Different from other ssrf automation tools, this one comes with the two following original features :

**Smart fuzzing on relevant SSRF GET parameters**

When fuzzing, autoSSRF only focuses on the common parameters related to SSRF (?url=, ?uri=, ..) and doesn’t interfere with everything else. This ensures that the original URL is still correctly understood by the tested web-application, something that might doesn’t happen with a tool which is blindly spraying query parameters.

**Context-based dynamic payloads generation**

For the given URL : https://host.com/?fileURL=https://authorizedhost.com, autoSSRF would recognize authorizedhost.com as a potentially white-listed host for the web-application, and generate payloads dynamically based on that, attempting to bypass the white-listing validation. It would result to interesting payloads such as : http://authorizedhost.attacker.com, http://authorizedhost%252F@attacker.com, etc.

Furthermore, this tool guarantees almost no false-positives. The detection relies on the great ProjectDiscovery’s interactsh, allowing autoSSRF to confidently identify out-of-band DNS/HTTP interactions.

[/long_descr]
[image]https://opengraph.githubassets.com/6292e19ade30cb8a953bb91fc410d11b8a29d9bb5ad297cda583ee307a5f0818/xd20111/autossrf [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
