### ISSUE TITLE
[addtool] ShadowSpray 

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#813]
[homepage]https://github.com/Dec0ne/ShadowSpray [/homepage]
[link]https://github.com/Dec0ne/ShadowSpray [/link]
[tags]domain,enumeration,scanner [/tags]
[short_descr]A tool to spray Shadow Credentials across an entire domain in hopes of abusing long forgotten GenericWrite/GenericAll DACLs over other objects in the domain.[/short_descr]
[image]https://github.com/Dec0ne/ShadowSpray/raw/master/Images/bloodhound.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
