### ISSUE TITLE
[addtool] AORT

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#814]
[homepage]https://github.com/D3Ext/AORT [/homepage]
[link]https://github.com/D3Ext/AORT [/link]
[tags]domain,enumeration,scanner,osint,recon [/tags]
[short_descr]All in One Recon Tool for Bug Bounty [/short_descr]
[image]https://raw.githubusercontent.com/D3Ext/AORT/main/demo.png [/image]

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/781
