### ISSUE TITLE
[addtool] Villain 

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#815]
[homepage]https://github.com/t3l3machus/Villain [/homepage]
[link]https://github.com/t3l3machus/Villain [/link]
[tags]backdoor, [/tags]
[short_descr]Villain is a Windows & Linux backdoor generator and multi-session handler that allows users to connect with sibling servers (other machines running Villain) and share their backdoor sessions, handy for working as a team. [/short_descr]
[long_descr]Villain is a Windows & Linux backdoor generator and multi-session handler that allows users to connect with sibling servers (other machines running Villain) and share their backdoor sessions, handy for working as a team.

The main idea behind the payloads generated by this tool is inherited from HoaxShell. One could say that Villain is an evolved, steroid-induced version of it.[/long_descr]
[image]https://user-images.githubusercontent.com/75489922/201544082-e1233421-f319-47b5-9e5e-d95647026dc0.png [/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/villain

Thank you for your contribution!
