### ISSUE TITLE
[addtool] bypass-url-parser

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#816]
[homepage]https://github.com/laluka/bypass-url-parser [/homepage]
[link]https://github.com/laluka/bypass-url-parser [/link]
[tags]bypass,40x [/tags]
[short_descr]Tool that tests MANY url bypasses to reach a 40X protected page. [/short_descr]
[image]https://opengraph.githubassets.com/04b605e33aab2273125362e3fd531c8a388e9b89f15dc5b837189d44031e7975/xd20111/bypass-url-parser [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/bypass-url-parser

Thank you for your contribution!
