### ISSUE TITLE
[addtool] malicious-pdf

### ISSUE THREAD

**Issue by xd20111** [gwen001/offsectools_www#819]
[homepage]https://github.com/jonaslejon/malicious-pdf [/homepage]
[link]https://github.com/jonaslejon/malicious-pdf [/link]
[tags]bypass,pdf,backdoor [/tags]
[short_descr]💀 Generate a bunch of malicious pdf files with phone-home functionality. Can be used with Burp Collaborator or Interact.sh [/long_descr]
[long_descr]Generate ten different malicious pdf files with phone-home functionality. Can be used with Burp Collaborator or Interact.sh[/long_descr] 
[image]https://camo.githubusercontent.com/fd7746aa5354c5ddde020f6a64249f69f1c122ed0a3cbf2643a0fbb16945d59e/68747470733a2f2f7472696f702e73652f77702d636f6e74656e742f75706c6f6164732f323032312f30382f6d616c6963696f75732d7064662d65313632393139373732363236302e706e67 [/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: short_descr

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).
