### ISSUE TITLE
[addtool] qsfuzz

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#82]
[short_descr]qsfuzz is a tool that allows to write simple rules in YAML that define what value to inject[/short_descr]
[link][https://github.com/ameenmaali/qsfuzz[/link]](https://github.com/ameenmaali/qsfuzz%5B/link%5D)
[tags]fuzzing[/tags]
[long_descr]qsfuzz is a tool that allows you to write simple rules in YAML that define what value you want to inject, and what is the outcome you expect if that injection is successful. Pass in a list of URLs, with query strings, and qsfuzz will replace the query string values with your injections to determine if it's vulnerable.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207260521-4178b4c4-06fb-435d-8822-4e6f9c902509.png)

**Comment by gwen001** [comment]
Duplicate of https://github.com/gwen001/offsectools_www/issues/81
