### ISSUE TITLE
[addtool] GitHarvester

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#822]
[homepage]https://github.com/metac0rtex/GitHarvester [/homepage]
[tags]git,python,[/tags]
[short_descr]This tool is used for harvesting information from GitHub. By default it looks
for code with the filename of 'wp-config.php' and pulls out auth info.[/short_descr]
[image]
![githarverster](https://user-images.githubusercontent.com/53378318/218703987-ec07c6bb-89b0-4fea-8862-ec3e428cd3a9.PNG)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/githarvester

Thank you for your contribution!
