### ISSUE TITLE
[addtool] Metabigor

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#824]
[homepage]https://github.com/j3ssie/metabigor [/homepage]
[tags]OSINT[/tags]
[short_descr]Metabigor is Intelligence tool, its goal is to do OSINT tasks and more but without any API key.[/short_descr]
[image]
![metabigor](https://user-images.githubusercontent.com/53378318/218706105-d93ded46-f204-4717-a2ed-bd656d894542.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/metabigor

Thank you for your contribution!
