### ISSUE TITLE
[addtool] Skanuvaty

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#825]
[homepage]https://github.com/Esc4iCEscEsc/skanuvaty [/homepage]
[tags]Scanner,DNS,Rust[/tags]
[short_descr]Dangerously fast DNS/network/port scanner[/short_descr]
[image]
![sky](https://user-images.githubusercontent.com/53378318/218706883-42694741-48bf-44dd-ab31-07afb1265525.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/skanuvaty

Thank you for your contribution!
