### ISSUE TITLE
[addtool] Mortar

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#827]
[homepage]https://github.com/0xsp-SRD/mortar [/homepage]
[tags]EDR,XDR,Bypass[/tags]
[short_descr]red teaming evasion technique to defeat and divert detection and prevention of security products.Mortar Loader performs encryption and decryption of selected binary inside the memory streams and execute it directly with out writing any malicious indicator into the hard-drive. Mortar is able to bypass modern anti-virus products and advanced XDR solutions[/short_descr]
[image]
![mortar](https://user-images.githubusercontent.com/53378318/218970366-f4c63aee-0675-4d30-8474-ade2695d168e.PNG)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
