### ISSUE TITLE
[addtool] PyCript

### ISSUE THREAD

**Issue by Anof-cyber** [gwen001/offsectools_www#829]
[homepage] https://github.com/Anof-cyber/PyCript [/homepage]
[tags] burpsuite, cryptography, encryption [/tags]
[short_descr] Burp Suite extension that bypasses client-side encryption using custom logic for manual and automation testing. [/short_descr]
[long_descr] The Pycript extension for Burp Suite is a valuable tool for penetration testing and security professionals. It enables easy encryption and decryption of requests during testing, which can help evade detection and bypass security measures. The extension also offers the ability to customize the encryption and decryption process by writing custom logic using JavaScript and Node.js, making it a highly adaptable tool for various needs. Additionally, it supports both manual and automated testing, as well as custom encryption/decryption plugins, making it a versatile solution for different penetration testing scenarios. [/long_descr] 
[image] https://user-images.githubusercontent.com/39705906/219716700-28dc12e5-153b-406c-a138-8d069022be15.png [/image]

**Comment by gwen001** [comment]
Problem occured with the following fields: short_descr, homepage, tags, picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pycript

Thank you for your contribution!
