### ISSUE TITLE
[addtool]jaeles-project

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#83]
[short_descr]The Swiss Army knife for automated Web Application Testing [/short_descr]
[link]https://github.com/jaeles-project/jaeles[/link]
[tags]recon,fuzzing[/tags]
[long_descr]Jaeles is a powerful, flexible and easily extensible framework written in Go for building your own Web Application Scanner.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207271752-0e34e6d8-a45e-416b-968d-f336dbc17e4e.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for validation.
