### ISSUE TITLE
[addtool] Pentest Mapper

### ISSUE THREAD

**Issue by Anof-cyber** [gwen001/offsectools_www#830]
[homepage] https://github.com/Anof-cyber/Pentest-Mapper [/homepage]
[tags] burpsuite, mapping [/tags]
[short_descr] A Burp Suite Extension for Application Penetration Testing to write test cases and map flows and vulnerabilities [/short_descr]
[image] https://github.com/PortSwigger/pentest-mapper/raw/main/images/APIMapper.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pentest-mapper

Thank you for your contribution!
