### ISSUE TITLE
[addtool] APTRS

### ISSUE THREAD

**Issue by Anof-cyber** [gwen001/offsectools_www#831]
[homepage] https://github.com/Anof-cyber/APTRS [/homepage]
[tags] reports, vulnerabilities, pdf, docx, management [/tags]
[short_descr] Automated Penetration Testing Reporting System. The tool allows the pentester to create reports, manage projects and vulnerabilities [/short_descr] 
[image] https://repository-images.githubusercontent.com/558932728/e8ff2c72-3797-41ab-9505-90c9008cc472 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/aptrs

Thank you for your contribution!
