### ISSUE TITLE
[addtool] Osmedeus

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#84]
[short_descr]A Workflow Engine for Offensive Security[/short_descr]
[link]https://github.com/j3ssie/osmedeus[/link]
[tags]recon,fuzzing,scanner[/tags]
[long_descr]Osmedeus is a Workflow Engine for Offensive Security. It was designed to build a foundation with the capability and flexibility that allows you to build your own reconnaissance system and run it on a large number of targets.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207272362-a438faaa-b7be-41f2-b4d3-1b17ecb3df40.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/osmedeus

Thank you!
