### ISSUE TITLE
[addtool] Graphicator

### ISSUE THREAD

**Issue by cybervelia** [gwen001/offsectools_www#875]
[homepage][https://github.com/cybervelia/graphicator](https://github.com/cybervelia/graphicator)[/homepage]
[tags]graphql,scanner,crawler,directories[/tags]
[short_descr]Enumerate and extract GraphQL APIs.[/short_descr]
[long_descr]
The tool iterates over the introspection document returned by the targeted GraphQL endpoint, and then re-structures the schema in an internal form so it can re-create the supported queries. When such queries are created is using them to send requests to the endpoint and saves the returned response to a file.

Erroneous responses are not saved. By default the tool caches the correct responses and also caches the errors, thus when re-running the tool it won't go into the same queries again.
[/long_descr]
[picture]
![graphicator](https://user-images.githubusercontent.com/122566153/220428515-3ef74061-f07f-4e52-8166-9c8dd1521f03.png)
[/picture]

**Comment by gwen001** [comment]
Problem occured with the following fields: homepage, picture

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/graphicator

Thank you for your contribution!
