### ISSUE TITLE
[addtool] Tool Flameshot

### ISSUE THREAD

**Issue by piyush-security** [gwen001/offsectools_www#877]
homepage = https://flameshot.org/
#54, #screenshot, #flameshot
![image](https://user-images.githubusercontent.com/98208035/220677099-33f75bf7-92af-4479-8cca-86b69cba974b.png)

**Comment by gwen001** [comment]
Problem occured with the following fields: short_descr, homepage, tags

Check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1).

**Comment by gwen001** [comment]
Your issue cannot be properly handled by the bot, please check the [guidelines](https://github.com/gwen001/offsectools_www/issues/1) to be sure to respect the correct format.

Or take a look at one of the previous issue so you can see how it should be, thank you.
