### ISSUE TITLE
[addtool] Spy Extension

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#888]
[homepage] https://github.com/msfrisbie/spy-extension [/homepage]
[extra_link] https://mattfrisbie.substack.com/p/spy-chrome-extension [/extra_link]
[tags] all,chrome,extension [/tags]
[short_descr] This Chrome extension will read literally everything it can. [/short_descr]
[image] https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F8f0e4276-498c-4d46-80fb-466437307695_2184x1426.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/spy-extension

Thank you for your contribution!
