### ISSUE TITLE
[addtool] Tool hunter.how

### ISSUE THREAD

**Issue by rtcms** [gwen001/offsectools_www#889]
[homepage]https://hunter.how/ [/homepage]
[tags]#cves,#dns,#ips ,#network,#online,#ports,#recon,#subdomains[/tags]
[short_descr]Internet Search Engines For Security Researchers.[/short_descr]
[image]https://offsec.tools/img/default-tool.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/hunter.how

Thank you for your contribution!

**Comment by gwen001** [comment]
Next time you want to add a tool please provide a real picture and a better description of the tool, empty information don't help anyone, neither the user nor the author. Thank you.
