### ISSUE TITLE
[addtool] recollapse

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#91]
[link]https://github.com/0xacb/recollapse[/link]
[short_descr]REcollapse is a helper tool for black-box regex fuzzing to bypass validations[/short_descr]
[tags]fuzzing[/tags]
[long_descr]REcollapse is a helper tool for black-box regex fuzzing to bypass validations and discover normalizations in web applications.

It can also be helpful to bypass WAFs and weak vulnerability mitigations. For more information, take a look at the REcollapse blog post.

The goal of this tool is to generate payloads for testing. Actual fuzzing shall be done with other tools like Burp (intruder), ffuf, or similar.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207288274-d77e9315-5e9b-44c8-8770-cd44f8352291.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/recollapse

Thank you!
