### ISSUE TITLE
[addtool] upload_bypass

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#913]
[homepage] https://github.com/sAjibuu/upload_bypass [/homepage]
[tags] all,file,upload,bypass,bugbounty [/tags]
[short_descr] File upload restrictions bypass by using different bug bounty techniques! [/short_descr]
[image] 
![image](https://user-images.githubusercontent.com/5957301/222080754-914777fa-72ed-4f65-8c70-a339987b9236.png)
 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/upload_bypass

Thank you for your contribution!
