### ISSUE TITLE
[addtool] Quickjack

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#914]
[homepage] https://github.com/samyk/quickjack [/homepage]
[extra_link] https://samy.pl/quickjack/ [/extra_link]
[tags] all,clickjacking,bugbounty [/tags]
[short_descr] Quickjack is a point-and-click tool for producing advanced clickjacking and frame-slicing attacks. [/short_descr]
[image] https://samy.pl/quickjack/qj1.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/quickjack

Thank you for your contribution!
