### ISSUE TITLE
[addtool] CDK

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#915]
[homepage] https://github.com/cdk-team/CDK [/homepage]
[tags] all,container,penetration,security [/tags]
[short_descr] CDK - Zero Dependency Container Penetration Toolkit [/short_descr]
[image] https://user-images.githubusercontent.com/7868679/177925206-8d83dc95-0f2f-4d61-9a45-0d43b1b0468f.png [/image]

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/cdk

Thank you for your contribution!
