### ISSUE TITLE
[addtool] CertVerify

### ISSUE THREAD

**Issue by password123456** [gwen001/offsectools_www#916]
[homepage]https://github.com/password123456/CertVerify[/homepage]
[tags]virus-scanner,owasp,antivirus,malware-analyzer,security-tools,malware-scanner,file-scan,codesigned-detection,leaked-certificate,untrusted-certificate,codesign-scanner[/tags]
[short_descr]The CertVerify is a tool designed to detect executable files (exe, dll, sys) that have been signed with untrusted or leaked code signing certificates. [/short_descr]
[long_descr]Executable files signed with compromised or untrusted code signing certificates can be used to distribute malware and other malicious software. Attackers can use these files to bypass security controls and to make their malware appear legitimate to victims. This tool helps to identify these files so that they can be removed or investigated further.
 As a continuous project of the previous [malware scanner](https://github.com/password123456/malwarescanner), i have created such a tool. This type of tool is also essential in the event of a security incident response.[/long_descr] 
[image]https://github.com/password123456/CertVerify/blob/main/preview.JPG[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
