### ISSUE TITLE
[addtool] jsfinder

### ISSUE THREAD

**Issue by kacakb** [gwen001/offsectools_www#917]
[homepage] https://github.com/kacakb/jsfinder [/homepage]
[tags]bugbounty,recon,javascript,js,scanner,crawler[/tags]
[short_descr]Fetches JavaScript files quickly and comprehensively from a defined list of URLs or domains.[/short_descr]
[image]https://user-images.githubusercontent.com/64865400/223352775-c745c4f8-0d94-4121-952a-b57f74ceadb5.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/jsfinder

Thank you for your contribution!
