### ISSUE TITLE
[addtool] AWSGoat

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#946]
[homepage]https://github.com/ine-labs/AWSGoat [/homepage]
[tags]cloud,xss,sqli[/tags]
[short_descr] A Damn Vulnerable AWS Infrastructure[/short_descr]
[long_descr]AWSGoat is a vulnerable by design infrastructure on AWS featuring the latest released OWASP Top 10 web application security risks (2021) and other misconfiguration based on services such as IAM, S3, API Gateway, Lambda, EC2, and ECS. AWSGoat mimics real-world infrastructure but with added vulnerabilities. It features multiple escalation paths and is focused on a black-box approach.[/long_descr] 
[image]
![awsgoat](https://user-images.githubusercontent.com/53378318/225840987-a7e20cc8-f8b0-4d8d-8610-f08ff4b56068.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/awsgoat

Thank you for your contribution!
