### ISSUE TITLE
[addtool] AzureGoat

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#947]
[homepage]https://github.com/ine-labs/AzureGoat [/homepage]
[tags]cloud,xss,sqli[/tags]
[short_descr]A Damn Vulnerable Azure Infrastructure[/short_descr]
[long_descr]AzureGoat is a vulnerable by design infrastructure on Azure featuring the latest released OWASP Top 10 web application security risks (2021) and other misconfiguration based on services such as App Functions, CosmosDB, Storage Accounts, Automation and Identities. AzureGoat mimics real-world infrastructure but with added vulnerabilities. It features multiple escalation paths and is focused on a black-box approach.
[/long_descr] 
[image]
![azuregoat](https://user-images.githubusercontent.com/53378318/225841646-e8bbf1ab-71cd-4814-8467-392f484eb4b7.png)
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/azuregoat

Thank you for your contribution!
