### ISSUE TITLE
[addtool] DVCA

### ISSUE THREAD

**Issue by SelmiAhmed** [gwen001/offsectools_www#950]
[homepage]https://github.com/m6a-UdS/dvca [/homepage]
[tags]cloud, xss,owasp10[/tags]
[short_descr]Damn Vulnerable Cloud Application[/short_descr]
[image]
<img width="1449" alt="DVCA" src="https://user-images.githubusercontent.com/53378318/225843020-2eabdb90-ac07-42b7-9f50-39b91508ed02.png">
[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/dvca

Thank you for your contribution!
