### ISSUE TITLE
[addtool] TerminatorZ

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#952]
[homepage] https://github.com/blackhatethicalhacking/TerminatorZ [/homepage]
[tags] all,scanning,CVEs [/tags]
[short_descr] TerminatorZ is a web security tool that scans web apps for vulnerabilities with known CVEs. [/short_descr]
[image] https://user-images.githubusercontent.com/13942386/222258110-a0c83c4c-80b1-4be2-83b9-06afb7b175b7.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/terminatorz

Thank you for your contribution!
