### ISSUE TITLE
[addtool] SSRFPwned

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#953]
[homepage] https://github.com/blackhatethicalhacking/SSRFPwned [/homepage]
[tags] all,SSRF,forgery [/tags]
[short_descr] Checks for SSRF using custom payloads after fetching URLs from sources & applying complex patterns. [/short_descr]
[image] https://user-images.githubusercontent.com/13942386/222452352-5b5df56d-0fe0-47e3-8a1d-4e4c87560791.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ssrfpwned

Thank you for your contribution!
