### ISSUE TITLE
[addtool] ScopeHunter

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#954]
[homepage] https://github.com/blackhatethicalhacking/ScopeHunter [/homepage]
[tags] all,scan,bugbounty [/tags]
[short_descr] ScopeHunter is a command-line tool for finding in-scope targets for bug bounty programs. [/short_descr]
[image] https://user-images.githubusercontent.com/13942386/216113965-4609c07b-7c8b-45f4-9575-4addef0623e8.png [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/scopehunter

Thank you for your contribution!
