### ISSUE TITLE
[addtool] Ciphey

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#955]
[homepage] https://github.com/Ciphey/Ciphey [/homepage]
[extra_link] https://github.com/Ciphey/Ciphey/wiki [/extra_link]
[tags] all,cryptography,crypto,decrypt [/tags]
[short_descr] Ciphey automates decryptions & decodings with encodings, classical ciphers, hashes, or more. [/short_descr]
[image] https://github.com/Ciphey/Ciphey/raw/master/Pictures_for_README/index.gif [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ciphey

Thank you for your contribution!
