### ISSUE TITLE
[addtool] Knoxnl

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#96]
[link]https://github.com/xnl-h4ck3r/knoxnl[/link]
[short_descr] This is a python wrapper around the amazing KNOXSS API by Brute Logic [/short_descr]
[tags]knoxss,xss,fuzzing[/tags]
[long_descr]This is a python wrapper around the amazing KNOXSS API by Brute Logic. To use this tool (and the underlying API), you must have a valid KNOXSS API key. Don't have one? Go visit https://knoxss.me and subscribe! This was inspired by the "knoxssme" tool by @edoardottt2, but developed to allow for greater options.[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207290510-b15264ab-4731-4d01-b758-a2a329c7ede0.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
