### ISSUE TITLE
[addtool] Tool LDAP-Password-Hunter

### ISSUE THREAD

**Issue by oldboy21** [gwen001/offsectools_www#973]
[homepage]https://github.com/oldboy21/LDAP-Password-Hunter [/homepage]
[tags]ldap,password,discovery,activedirectory,ad[/tags]
[short_descr]This tool helps finding secrets in the active directory database[/short_descr]
[long_descr]It happens that due to legacy services requirements or just bad security practices password are world-readable in the Active Directory database by any user who is able to authenticate. LDAP Password Hunter is a tool which wraps features of getTGT.py (Impacket) and ldapsearch in order to look up for password stored in AD database. Impacket getTGT.py script is used in order to authenticate the domain account used for enumeration and save its TGT kerberos ticket. TGT ticket is then exported in KRB5CCNAME variable which is used by ldapsearch script to authenticate and obtain TGS kerberos tickets for each domain/DC LDAP-Password-Hunter is ran for. Basing on the CN=Schema,CN=Configuration export results a custom list of attributes is built and filtered in order to identify a big query which might contains interesting results.[/long_descr] 
[image]a link OR an attached image (required)[/image]
![image](https://user-images.githubusercontent.com/87986485/227793025-17fbc0eb-b6de-46f3-b1bc-eacdc9e9dfd8.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/ldap-password-hunter

Thank you for your contribution!
