### ISSUE TITLE
[addtool] Waymore

### ISSUE THREAD

**Issue by mrrootsec** [gwen001/offsectools_www#98]
[link]https://github.com/xnl-h4ck3r/waymore[/link]
[short_descr]Find way more from the Wayback Machine! [/short_descr]
[tags]wayback,archive[/tags]
[long_descr]The idea behind waymore is to find even more links from the Wayback Machine than other existing tools.

point_right The biggest difference between waymore and other tools is that it can also download the archived responses for URLs on wayback machine so that you can then search these for even more links, developer comments, extra parameters, etc. etc.

Anyone who does bug bounty will have likely used the amazing waybackurls by @TomNomNoms. This tool gets URLs from web.archive.org and additional links (if any) from one of the index collections on index.commoncrawl.org. You would have also likely used the amazing gau by @hacker_ which also finds URL's from wayback archive, Common Crawl, but also from Alien Vault and URLScan. Now waymore gets URL's from ALL of those sources too (with ability to filter more to get what you want):

    Wayback Machine (web.archive.org)
    Common Crawl (index.commoncrawl.org)
    Alien Vault OTX (otx.alienvault.com)
    URLScan (urlscan.io)

point_right It's a point that many seem to miss, so I'll just add it again :) ... The biggest difference between waymore and other tools is that it can also download the archived responses for URLs on wayback machine so that you can then search these for even more links, developer comments, extra parameters, etc. etc.

point_right PLEASE READ ALL OF THE INFORMATION ON THIS PAGE TO MAKE THE MOST OF THIS TOOL, AND ESPECIALLY BEFORE RAISING ANY ISSUES metal

point_right THIS TOOL CAN BE VERY SLOW, BUT IT

IS MEANT FOR COVERAGE, NOT SPEED[/long_descr]
![image](https://user-images.githubusercontent.com/32585833/207290733-bf59694a-395b-4e53-8365-503cb2ce9e53.png)

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted: https://offsec.tools/tool/waymore

Thank you!
