### ISSUE TITLE
[addtool] SecretFinder

### ISSUE THREAD

**Issue by euriconicacio** [gwen001/offsectools_www#980]
[homepage] https://github.com/m4ll0k/SecretFinder[/homepage]
[tags] all,secrets,tokens,scanner,javascript [/tags]
[short_descr] SecretFinder is a script based on LinkFinder, written to find sensitive data in JavaScript files. [/short_descr]
[image] https://camo.githubusercontent.com/cee549e23300801733b1e80be14173f12eff71401d01b77c6bb5ce230161638c/68747470733a2f2f692e696d6775722e636f6d2f44374d54324b4c2e706e67 [/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/secretfinder

Thank you for your contribution!
