### ISSUE TITLE
[addtool] Dismap - Asset discovery and identification tool

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#986]
[homepage]https://github.com/zhzyker/dismap[/homepage]
[tags]all, discovery, proto, fingerprint, assets[/tags]
[short_descr]Dismap positioning is an asset discovery and identification tool. It can quickly identify protocols and fingerprint information such as web/tcp/udp, locate asset types, and is suitable for internal and external networks.[/short_descr]
[image]https://github.com/zhzyker/zhzyker/blob/main/dismap-images/dismap-0.3.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/dismap

Thank you for your contribution!
