### ISSUE TITLE
[addtool] PyExfil

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#988]
[homepage]https://github.com/ytisf/PyExfil[/homepage]
[tags]exfiltration, c&c, dns, redteam, python, http, slack, protocols (required)[/tags]
[short_descr]The purpose of PyExfil is to set as many exfiltration, techniques that CAN be used to bypass various detection tools[/short_descr]
[image]https://github.com/ytisf/PyExfil/blob/master/README.md[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/pyexfil

Thank you for your contribution!

**Comment by gwen001** [comment]
For your next contribution, please consider that the README.md is not a valid image.
Also, a long description would help people to understand what the tool really does.

Thank you.
