### ISSUE TITLE
[addtool] usbkill

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#992]
[homepage]https://github.com/hephaest0s/usbkill[/homepage]
[tags]anti-forensic, usb,  (required)[/tags]
[short_descr]« usbkill » is an anti-forensic kill-switch that waits for a change on your USB ports and then immediately shuts down your computer[/short_descr]
[long_descr]Some reasons to use this tool:

- In case the police or other thugs come busting in (or steal your laptop from you when you are at a public library, as happened to Ross). The police commonly uses a mouse jiggler to keep the screensaver and sleep mode from activating.

- You don’t want someone to add or copy documents to or from your computer via USB.

- You want to improve the security of your (encrypted) home or corporate server (e.g. Your Raspberry).[/long_descr] 

[image]https://github.com/hephaest0s/usbkill/blob/master/Resources/USBKillBanner.gif[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
