### ISSUE TITLE
[addtool] SlowLoris

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#993]
[homepage]https://github.com/gkbrk/slowloris[/homepage]
[tags]dos, ddos, botnet, availability[/tags]
[short_descr]Slowloris is basically an HTTP Denial of Service attack that affects threaded servers[/short_descr]
[long_descr]Slowloris is a type of denial-of-service (DoS) attack that involves sending HTTP requests to a web server in a way that ties up the server's resources, preventing it from being able to process legitimate requests.
This attack would typically be conducted with a botnet, it is designed to be difficult to detect and mitigate, as it uses a relatively small number of connections and does not generate a large amount of traffic.[/long_descr] 
[image]https://user-images.githubusercontent.com/100603074/210115630-b6541ee0-ad82-471a-9a7e-7f0ec028c67d.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been refused by the team, feel free to get in touch if you have any question.

Thank you!
