### ISSUE TITLE
[addtool] GD-Thief

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#994]
[homepage]https://github.com/antman1p/GD-Thief[/homepage]
[tags]goole, drive, google drive, exfiltration, data[/tags]
[short_descr]ool for exfiltrating files from a target's Google Drive that you have access to, via Google's API[/short_descr]
[long_descr]Red Team tool for exfiltrating files from a target's Google Drive that you(the attacker) has access to, via the Google Drive API. This includes includes all shared files, all files from shared drives, and all files from domain drives that the target has access to.[/long_descr] 
[image]https://github.com/antman1p/GD-Thief/blob/main/static/gd_thief-banner.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.

**Comment by gwen001** [comment]
Tool has been accepted by the team: https://offsec.tools/tool/gd-thief

Thank you for your contribution!
