### ISSUE TITLE
[addtool]  StormBreaker

### ISSUE THREAD

**Issue by zp-4** [gwen001/offsectools_www#995]
[homepage]https://github.com/ultrasecurity/Storm-Breaker[/homepage]
[tags]all, social engineering, python, webcam, geoip, geolocalization (required)[/tags]
[short_descr]Social engineering tool [Access Webcam & Microphone & Location Finder] With Python [/short_descr]
[long_descr]Social engineering tool written with Python that obtain device information without any permission, access location (work for smartphones), access webcam, access microphone[/long_descr] 
[image]https://github.com/ultrasecurity/Storm-Breaker/blob/main/.imgs/1demo.png[/image]

**Comment by gwen001** [comment]
Issue correctly handled, tool is waiting for human validation.
